import { 
  TenantConfig, 
  Branch,
  UserProfile, 
  Student, 
  Staff, 
  AcademicClass, 
  CoachingCourse, 
  CoachingBatch, 
  AttendanceRecord, 
  FeeStructure, 
  StudentFeeLedger, 
  PaymentTransaction, 
  Exam, 
  StudentExamResult, 
  TimetableSlot, 
  Homework, 
  Notice, 
  LeadCRM, 
  NotificationItem,
  AuditLog
} from '../types';

export const INITIAL_TENANTS: TenantConfig[] = [
  {
    id: 'tenant-school-1',
    name: 'Delhi International Public School',
    code: 'DIPS',
    tenantType: 'SCHOOL',
    status: 'active',
    logo: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?w=150&auto=format&fit=crop&q=80',
    tagline: 'Empowering Minds, Shaping Tomorrow',
    primaryColor: '#0284c7', // Sky blue
    secondaryColor: '#0369a1',
    accentColor: '#f59e0b',
    address: 'Plot 42, Institutional Area, Sector 14, Dwarka, New Delhi - 110075',
    phone: '+91 11 2808 4500',
    email: 'admissions@delhiinternationalschool.edu.in',
    website: 'https://delhiinternationalschool.edu.in',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata',
    academicYear: '2026-2027',
    planName: 'Enterprise School SaaS',
    subscriptionRenewalDate: '2027-03-31',
    labels: {
      group: 'Class',
      subgroup: 'Section',
      groupPlural: 'Classes',
      student: 'Student',
      studentPlural: 'Students',
      staff: 'Teacher',
      staffPlural: 'Teachers',
      admission: 'Admission',
      period: 'Academic Year',
      exam: 'Examination',
      examPlural: 'Examinations',
      reportCard: 'Report Card',
      homework: 'Homework / Assignment',
      feeStructure: 'Annual Fee Structure',
    },
    features: {
      attendance: true,
      qrAttendance: true,
      fees: true,
      onlinePayments: true,
      exams: true,
      reportCards: true,
      testSeries: false,
      rankComparison: false,
      homework: true,
      timetable: true,
      communication: true,
      whatsappAlerts: true,
      inquiryCrm: true,
      certificates: true,
      hrPayroll: true,
      aiAssistant: true,
      aiReportSummary: true,
      transport: true,
      library: true,
      hostel: false,
    },
  },
  {
    id: 'tenant-coaching-1',
    name: 'Apex IIT-JEE & Medical Academy',
    code: 'APEX',
    tenantType: 'COACHING',
    status: 'active',
    logo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=150&auto=format&fit=crop&q=80',
    tagline: 'Pioneering Excellence in National Competitive Exams',
    primaryColor: '#7c3aed', // Purple
    secondaryColor: '#6d28d9',
    accentColor: '#10b981',
    address: 'Apex Tower, 3rd Floor, Commercial Complex, Kalu Sarai, Hauz Khas, New Delhi',
    phone: '+91 98765 43210',
    email: 'info@apexacademy.co.in',
    website: 'https://apexacademy.co.in',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata',
    academicYear: 'Session 2026-2027',
    planName: 'Coaching Institute Pro',
    subscriptionRenewalDate: '2027-04-15',
    labels: {
      group: 'Batch',
      subgroup: 'Track',
      groupPlural: 'Batches',
      student: 'Learner',
      studentPlural: 'Learners',
      staff: 'Faculty',
      staffPlural: 'Faculty',
      admission: 'Enrollment',
      period: 'Course Session',
      exam: 'Test Series / Mock Test',
      examPlural: 'Test Series',
      reportCard: 'Rank & Performance Analytics',
      homework: 'Daily Practice Sheet (DPP)',
      feeStructure: 'Course Fee Installment Plan',
    },
    features: {
      attendance: true,
      qrAttendance: true,
      fees: true,
      onlinePayments: true,
      exams: true,
      reportCards: false,
      testSeries: true,
      rankComparison: true,
      homework: true,
      timetable: true,
      communication: true,
      whatsappAlerts: true,
      inquiryCrm: true,
      certificates: true,
      hrPayroll: false,
      aiAssistant: true,
      aiReportSummary: true,
      transport: false,
      library: false,
      hostel: false,
    },
  },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-school-main',
    tenantId: 'tenant-school-1',
    name: 'Main Campus (Dwarka)',
    code: 'DWK-MAIN',
    isMain: true,
    address: 'Plot 42, Institutional Area, Sector 14, Dwarka, New Delhi - 110075',
    phone: '+91 11 2808 4500',
    email: 'dwarka@delhiinternationalschool.edu.in',
  },
  {
    id: 'branch-school-south',
    tenantId: 'tenant-school-1',
    name: 'South Campus (Saket)',
    code: 'SKT-SOUTH',
    isMain: false,
    address: 'Community Center, Saket, New Delhi - 110017',
    phone: '+91 11 4100 8820',
    email: 'saket@delhiinternationalschool.edu.in',
  },
  {
    id: 'branch-coaching-hauz',
    tenantId: 'tenant-coaching-1',
    name: 'Hauz Khas (Central Center)',
    code: 'HK-01',
    isMain: true,
    address: 'Apex Tower, Kalu Sarai, Hauz Khas, New Delhi',
    phone: '+91 98765 43210',
    email: 'hauzkhas@apexacademy.co.in',
  },
  {
    id: 'branch-coaching-noida',
    tenantId: 'tenant-coaching-1',
    name: 'Noida Hub (Sector 62)',
    code: 'NOIDA-02',
    isMain: false,
    address: 'Knowledge Park II, Sector 62, Noida - 201309',
    phone: '+91 98765 43211',
    email: 'noida@apexacademy.co.in',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  // Super Admin
  {
    id: 'user-superadmin',
    tenantId: 'platform',
    email: 'superadmin@edunexus.io',
    name: 'Vikramaditya Sharma',
    phone: '+91 99999 00001',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    designation: 'Platform Director',
    createdAt: '2025-01-01T00:00:00Z',
  },
  // School Tenant Admin
  {
    id: 'user-school-admin',
    tenantId: 'tenant-school-1',
    email: 'principal@delhiinternationalschool.edu.in',
    name: 'Dr. Sunita Verma',
    phone: '+91 98111 22334',
    role: 'TENANT_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    designation: 'Principal & Chief Administrator',
    department: 'Administration',
    createdAt: '2025-02-01T00:00:00Z',
  },
  // School Teacher
  {
    id: 'user-school-teacher',
    tenantId: 'tenant-school-1',
    email: 'rajesh.sharma@delhiinternationalschool.edu.in',
    name: 'Rajesh Sharma',
    phone: '+91 98222 33445',
    role: 'TEACHER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    designation: 'Senior Physics PGT',
    department: 'Science',
    assignedGroupIds: ['class-10-a', 'class-12-a'],
    createdAt: '2025-02-15T00:00:00Z',
  },
  // School Accountant
  {
    id: 'user-school-accountant',
    tenantId: 'tenant-school-1',
    email: 'accounts@delhiinternationalschool.edu.in',
    name: 'Ramesh Kulkarni',
    phone: '+91 98111 55667',
    role: 'ACCOUNTANT',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    designation: 'Chief Accounts Officer & Bursar',
    department: 'Accounts & Finance',
    createdAt: '2025-02-10T00:00:00Z',
  },
  // School Receptionist / Staff
  {
    id: 'user-school-receptionist',
    tenantId: 'tenant-school-1',
    email: 'reception@delhiinternationalschool.edu.in',
    name: 'Pooja Bhatt',
    phone: '+91 98111 99000',
    role: 'STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    designation: 'Front Desk & Admissions Coordinator',
    department: 'Front Office',
    createdAt: '2025-02-12T00:00:00Z',
  },
  // School Parent (Multiple Children)
  {
    id: 'user-school-parent',
    tenantId: 'tenant-school-1',
    email: 'amit.kapoor@gmail.com',
    name: 'Amit Kapoor',
    phone: '+91 98333 44556',
    role: 'PARENT',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    designation: 'Parent',
    linkedStudentIds: ['student-101', 'student-102'], // Aarav Kapoor (Grade 10) & Ananya Kapoor (Grade 6)
    createdAt: '2025-03-01T00:00:00Z',
  },
  // School Student
  {
    id: 'user-school-student',
    tenantId: 'tenant-school-1',
    email: 'aarav.kapoor@student.dips.edu',
    name: 'Aarav Kapoor',
    phone: '+91 98444 55667',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    studentId: 'student-101',
    createdAt: '2025-03-01T00:00:00Z',
  },
  // Coaching Tenant Admin
  {
    id: 'user-coaching-admin',
    tenantId: 'tenant-coaching-1',
    email: 'director@apexacademy.co.in',
    name: 'Prof. Alok Singhal',
    phone: '+91 98555 66778',
    role: 'TENANT_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    designation: 'Managing Director & Academic Dean',
    createdAt: '2025-01-10T00:00:00Z',
  },
  // Coaching Faculty
  {
    id: 'user-coaching-faculty',
    tenantId: 'tenant-coaching-1',
    email: 'dr.neha.gupta@apexacademy.co.in',
    name: 'Dr. Neha Gupta',
    phone: '+91 98666 77889',
    role: 'TEACHER',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    designation: 'Head of Chemistry (Ex-IIT Delhi Faculty)',
    department: 'Organic & Inorganic Chemistry',
    assignedGroupIds: ['batch-jee-alpha', 'batch-neet-super30'],
    createdAt: '2025-01-15T00:00:00Z',
  },
  // Coaching Parent
  {
    id: 'user-coaching-parent',
    tenantId: 'tenant-coaching-1',
    email: 'sanjay.shukla@hotmail.com',
    name: 'Sanjay Shukla',
    phone: '+91 98777 88990',
    role: 'PARENT',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    designation: 'Parent',
    linkedStudentIds: ['student-201'],
    createdAt: '2025-02-01T00:00:00Z',
  },
  // Coaching Student
  {
    id: 'user-coaching-student',
    tenantId: 'tenant-coaching-1',
    email: 'rohan.shukla@apex.in',
    name: 'Rohan Shukla',
    phone: '+91 98888 99001',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    studentId: 'student-201',
    createdAt: '2025-02-01T00:00:00Z',
  },
];

export const INITIAL_SCHOOL_CLASSES: AcademicClass[] = [
  {
    id: 'class-9',
    tenantId: 'tenant-school-1',
    name: 'Class 9',
    numericGrade: 9,
    sections: [
      { id: 'class-9-a', name: 'Section A', capacity: 40, classTeacherId: 'staff-103' },
      { id: 'class-9-b', name: 'Section B', capacity: 40, classTeacherId: 'staff-104' },
    ],
  },
  {
    id: 'class-10',
    tenantId: 'tenant-school-1',
    name: 'Class 10',
    numericGrade: 10,
    sections: [
      { id: 'class-10-a', name: 'Section A', capacity: 40, classTeacherId: 'staff-101' },
      { id: 'class-10-b', name: 'Section B', capacity: 40, classTeacherId: 'staff-102' },
    ],
  },
  {
    id: 'class-12',
    tenantId: 'tenant-school-1',
    name: 'Class 12 - Science',
    numericGrade: 12,
    stream: 'PCM & PCB',
    sections: [
      { id: 'class-12-a', name: 'Section A (PCM)', capacity: 35, classTeacherId: 'staff-101' },
      { id: 'class-12-b', name: 'Section B (PCB)', capacity: 35, classTeacherId: 'staff-105' },
    ],
  },
];

export const INITIAL_COACHING_COURSES: CoachingCourse[] = [
  {
    id: 'course-jee-2yr',
    tenantId: 'tenant-coaching-1',
    name: 'IIT-JEE 2-Year Comprehensive Foundation',
    code: 'JEE-2Y-PINNACLE',
    durationMonths: 24,
    feeAmount: 165000,
    description: 'Targeted preparation for JEE Main & Advanced covering Class 11th & 12th syllabus with regular mock series.',
    targetExam: 'JEE Advanced 2027',
  },
  {
    id: 'course-neet-1yr',
    tenantId: 'tenant-coaching-1',
    name: 'NEET Super-30 Intensive Crash & Test Series',
    code: 'NEET-INT-1Y',
    durationMonths: 12,
    feeAmount: 95000,
    description: 'High-yield medical entrance coaching with daily DPPs, biological diagrams drill, and NTA pattern tests.',
    targetExam: 'NEET (UG) 2026',
  },
  {
    id: 'course-olympiad',
    tenantId: 'tenant-coaching-1',
    name: 'Junior Science & Math Olympiad (KVPY / NSEJS)',
    code: 'OLYMPIAD-FOUND',
    durationMonths: 6,
    feeAmount: 45000,
    description: 'Advanced problem solving and analytical thinking for Grades 8-10.',
    targetExam: 'NSEJS / RMO / IOQM',
  },
];

export const INITIAL_COACHING_BATCHES: CoachingBatch[] = [
  {
    id: 'batch-jee-alpha',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-jee-2yr',
    name: 'JEE Alpha 2027 (Morning Batch)',
    startDate: '2025-04-15',
    endDate: '2027-04-30',
    schedule: 'Mon, Wed, Fri (07:30 AM - 11:30 AM)',
    facultyIds: ['staff-201', 'staff-202'],
    roomNo: 'Hall 301 - Faraday Hall',
    capacity: 45,
    enrolledCount: 38,
  },
  {
    id: 'batch-neet-super30',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-neet-1yr',
    name: 'NEET Super-30 Rankers (Evening)',
    startDate: '2025-06-01',
    endDate: '2026-05-15',
    schedule: 'Tue, Thu, Sat (04:00 PM - 08:00 PM)',
    facultyIds: ['staff-202', 'staff-203'],
    roomNo: 'Hall 204 - Charaka Hall',
    capacity: 35,
    enrolledCount: 32,
  },
  {
    id: 'batch-weekend-math',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-olympiad',
    name: 'Advanced Calculus & Algebra Booster',
    startDate: '2025-08-01',
    endDate: '2026-02-28',
    schedule: 'Saturday & Sunday (10:00 AM - 01:00 PM)',
    facultyIds: ['staff-201'],
    roomNo: 'Studio Lab 1',
    capacity: 25,
    enrolledCount: 19,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  // School Students
  {
    id: 'student-101',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0481',
    rollNo: '101',
    firstName: 'Aarav',
    lastName: 'Kapoor',
    gender: 'MALE',
    dob: '2010-04-12',
    email: 'aarav.kapoor@student.dips.edu',
    phone: '+91 98444 55667',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    address: 'B-404, Palm Grove Apartments, Sector 12, Dwarka, New Delhi',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2021-04-01',
    parentName: 'Amit Kapoor',
    parentPhone: '+91 98333 44556',
    parentEmail: 'amit.kapoor@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-101-AARAV',
    bloodGroup: 'O+',
    emergencyContact: '+91 98333 44556',
  },
  {
    id: 'student-102',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0612',
    rollNo: '102',
    firstName: 'Ananya',
    lastName: 'Kapoor',
    gender: 'FEMALE',
    dob: '2014-08-22',
    email: 'ananya.kapoor@student.dips.edu',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: 'B-404, Palm Grove Apartments, Sector 12, Dwarka, New Delhi',
    status: 'ACTIVE',
    classId: 'class-9',
    sectionId: 'class-9-a',
    enrollmentDate: '2023-04-01',
    parentName: 'Amit Kapoor',
    parentPhone: '+91 98333 44556',
    parentEmail: 'amit.kapoor@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-102-ANANYA',
    bloodGroup: 'B+',
    emergencyContact: '+91 98333 44556',
  },
  {
    id: 'student-103',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0495',
    rollNo: '103',
    firstName: 'Dev',
    lastName: 'Malhotra',
    gender: 'MALE',
    dob: '2010-11-05',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    address: 'House 18, Block C, Vasant Kunj, New Delhi',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2022-04-01',
    parentName: 'Raman Malhotra',
    parentPhone: '+91 98111 88990',
    parentEmail: 'raman.malhotra@yahoo.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-103-DEV',
    bloodGroup: 'A+',
  },
  {
    id: 'student-104',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0502',
    rollNo: '104',
    firstName: 'Pooja',
    lastName: 'Rao',
    gender: 'FEMALE',
    dob: '2010-02-14',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    address: 'Flat 12A, Golf Course Road, Gurugram',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2021-04-01',
    parentName: 'Kavita Rao',
    parentPhone: '+91 98222 11223',
    parentEmail: 'kavita.rao@outlook.com',
    parentRelationship: 'MOTHER',
    qrCode: 'DIPS-STU-104-POOJA',
    bloodGroup: 'AB+',
  },

  // Coaching Students (Can belong to multiple batches!)
  {
    id: 'student-201',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-889',
    rollNo: 'J-01',
    firstName: 'Rohan',
    lastName: 'Shukla',
    gender: 'MALE',
    dob: '2008-06-18',
    email: 'rohan.shukla@apex.in',
    phone: '+91 98888 99001',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    address: '34, Anand Lok, August Kranti Marg, New Delhi',
    status: 'ACTIVE',
    courseIds: ['course-jee-2yr', 'course-olympiad'],
    batchIds: ['batch-jee-alpha', 'batch-weekend-math'], // In 2 simultaneous batches!
    enrollmentDate: '2025-04-18',
    parentName: 'Sanjay Shukla',
    parentPhone: '+91 98777 88990',
    parentEmail: 'sanjay.shukla@hotmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-201-ROHAN',
    bloodGroup: 'O+',
  },
  {
    id: 'student-202',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-902',
    rollNo: 'N-14',
    firstName: 'Ishita',
    lastName: 'Deshmukh',
    gender: 'FEMALE',
    dob: '2008-09-29',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    address: 'Sector 56, Sushant Lok Phase 2, Gurugram',
    status: 'ACTIVE',
    courseIds: ['course-neet-1yr'],
    batchIds: ['batch-neet-super30'],
    enrollmentDate: '2025-06-05',
    parentName: 'Dr. Anand Deshmukh',
    parentPhone: '+91 99110 33445',
    parentEmail: 'anand.deshmukh@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-202-ISHITA',
    bloodGroup: 'A+',
  },
  {
    id: 'student-203',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-915',
    rollNo: 'J-02',
    firstName: 'Kabir',
    lastName: 'Choudhury',
    gender: 'MALE',
    dob: '2008-03-11',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    address: 'C-7, Green Park Extension, New Delhi',
    status: 'ACTIVE',
    courseIds: ['course-jee-2yr'],
    batchIds: ['batch-jee-alpha'],
    enrollmentDate: '2025-05-02',
    parentName: 'Sunil Choudhury',
    parentPhone: '+91 98115 54433',
    parentEmail: 'sunil.c@tcs.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-203-KABIR',
    bloodGroup: 'B+',
  },
];

export const INITIAL_STAFF: Staff[] = [
  // School Staff
  {
    id: 'staff-101',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-042',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@delhiinternationalschool.edu.in',
    phone: '+91 98222 33445',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Science & Physics',
    designation: 'Senior Physics PGT',
    qualification: 'M.Sc. (Physics), B.Ed.',
    joiningDate: '2019-07-01',
    salary: 75000,
    status: 'ACTIVE',
    subjects: ['Physics', 'Science'],
    assignedGroupIds: ['class-10-a', 'class-12-a'],
  },
  {
    id: 'staff-102',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-058',
    name: 'Meenakshi Sundaram',
    email: 'meenakshi.s@delhiinternationalschool.edu.in',
    phone: '+91 98333 22110',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Mathematics',
    designation: 'HOD Mathematics',
    qualification: 'M.Sc. (Mathematics), Ph.D.',
    joiningDate: '2017-04-15',
    salary: 82000,
    status: 'ACTIVE',
    subjects: ['Mathematics', 'Advanced Math'],
    assignedGroupIds: ['class-10-b', 'class-12-a'],
  },
  {
    id: 'staff-103',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-089',
    name: 'Priyanka Sen',
    email: 'priyanka.sen@delhiinternationalschool.edu.in',
    phone: '+91 98444 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'English & Literature',
    designation: 'TGT English',
    qualification: 'M.A. (English Lit), B.Ed.',
    joiningDate: '2021-08-01',
    salary: 62000,
    status: 'ACTIVE',
    subjects: ['English Core', 'Literature'],
    assignedGroupIds: ['class-9-a', 'class-10-a'],
  },

  // Coaching Faculty
  {
    id: 'staff-201',
    tenantId: 'tenant-coaching-1',
    employeeCode: 'FAC-APX-01',
    name: 'Er. Tarun Saxena',
    email: 'tarun.saxena@apexacademy.co.in',
    phone: '+91 98555 44332',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Physics',
    designation: 'Senior Faculty & IIT-JEE Mentor (B.Tech IIT Bombay)',
    qualification: 'B.Tech (IIT Bombay)',
    joiningDate: '2020-03-01',
    salary: 160000,
    status: 'ACTIVE',
    subjects: ['Rotational Dynamics', 'Electrodynamics', 'Modern Physics'],
    assignedGroupIds: ['batch-jee-alpha', 'batch-weekend-math'],
  },
  {
    id: 'staff-202',
    tenantId: 'tenant-coaching-1',
    employeeCode: 'FAC-APX-02',
    name: 'Dr. Neha Gupta',
    email: 'dr.neha.gupta@apexacademy.co.in',
    phone: '+91 98666 77889',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Chemistry',
    designation: 'Head of Chemistry (Ph.D. IIT Delhi)',
    qualification: 'M.Sc., Ph.D. (Chemistry)',
    joiningDate: '2021-01-10',
    salary: 150000,
    status: 'ACTIVE',
    subjects: ['Organic Chemistry', 'Coordination Compounds'],
    assignedGroupIds: ['batch-jee-alpha', 'batch-neet-super30'],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today's School Attendance (Class 10-A)
  {
    id: 'att-101-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:15:30',
    method: 'QR_SCAN',
  },
  {
    id: 'att-103-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-103',
    studentName: 'Dev Malhotra',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:22:10',
    method: 'QR_SCAN',
  },
  {
    id: 'att-104-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-104',
    studentName: 'Pooja Rao',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'LATE',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:45:00',
    method: 'MANUAL',
    notes: 'Late bus arrival',
  },

  // Today's Coaching Attendance (Batch JEE Alpha)
  {
    id: 'att-201-1',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Er. Tarun Saxena',
    markedAt: '07:28:45',
    method: 'QR_SCAN',
  },
  {
    id: 'att-203-1',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-203',
    studentName: 'Kabir Choudhury',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Er. Tarun Saxena',
    markedAt: '07:31:00',
    method: 'QR_SCAN',
  },
];

export const INITIAL_FEE_STRUCTURES: FeeStructure[] = [
  {
    id: 'fee-struct-school-10',
    tenantId: 'tenant-school-1',
    name: 'Class 10 Standard Annual Structure',
    groupId: 'class-10',
    heads: [
      { id: 'h1', name: 'Annual Tuition Fee', amount: 84000, frequency: 'ANNUAL' },
      { id: 'h2', name: 'Science & Computer Lab', amount: 12000, frequency: 'ANNUAL' },
      { id: 'h3', name: 'Sports & Co-curricular', amount: 6000, frequency: 'ANNUAL' },
      { id: 'h4', name: 'Examination & Library', amount: 4500, frequency: 'ANNUAL' },
    ],
    totalAmount: 106500,
  },
  {
    id: 'fee-struct-coaching-jee',
    tenantId: 'tenant-coaching-1',
    name: 'IIT-JEE 2-Year Full Package',
    groupId: 'course-jee-2yr',
    heads: [
      { id: 'ch1', name: 'Course Admission & Kit', amount: 25000, frequency: 'ONE_TIME' },
      { id: 'ch2', name: 'Academic Tuition & Faculty Mentorship', amount: 110000, frequency: 'ANNUAL' },
      { id: 'ch3', name: 'All-India Test Series & DPP Access', amount: 30000, frequency: 'ANNUAL' },
    ],
    totalAmount: 165000,
  },
];

export const INITIAL_FEE_LEDGERS: StudentFeeLedger[] = [
  // School Student: Aarav Kapoor
  {
    id: 'ledger-101',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    groupName: 'Class 10 - A',
    feeStructureId: 'fee-struct-school-10',
    totalFee: 106500,
    concession: 6500, // Sibling Concession
    netPayable: 100000,
    paidAmount: 50000,
    dueAmount: 50000,
    dueDate: '2026-09-30',
    status: 'PARTIAL',
    installments: [
      { installmentNo: 1, title: 'Quarter 1 (Apr - Jun)', amount: 25000, dueDate: '2026-04-10', paidDate: '2026-04-05', status: 'PAID' },
      { installmentNo: 2, title: 'Quarter 2 (Jul - Sep)', amount: 25000, dueDate: '2026-07-10', paidDate: '2026-07-08', status: 'PAID' },
      { installmentNo: 3, title: 'Quarter 3 (Oct - Dec)', amount: 25000, dueDate: '2026-10-10', status: 'PENDING' },
      { installmentNo: 4, title: 'Quarter 4 (Jan - Mar)', amount: 25000, dueDate: '2027-01-10', status: 'PENDING' },
    ],
  },
  // Coaching Student: Rohan Shukla
  {
    id: 'ledger-201',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    admissionNo: 'APX-2026-889',
    groupName: 'JEE Alpha 2027',
    feeStructureId: 'fee-struct-coaching-jee',
    totalFee: 165000,
    concession: 15000, // Apex Talent Search Scholarship (Rank 12)
    netPayable: 150000,
    paidAmount: 90000,
    dueAmount: 60000,
    dueDate: '2026-09-15',
    status: 'PARTIAL',
    installments: [
      { installmentNo: 1, title: 'Installment 1 (Enrollment)', amount: 50000, dueDate: '2025-04-18', paidDate: '2025-04-18', status: 'PAID' },
      { installmentNo: 2, title: 'Installment 2 (Mid-Year)', amount: 40000, dueDate: '2025-09-15', paidDate: '2025-09-14', status: 'PAID' },
      { installmentNo: 3, title: 'Installment 3 (Year 2 Kickoff)', amount: 60000, dueDate: '2026-04-15', status: 'PENDING' },
    ],
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'pay-001',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    receiptNo: 'RCP-DIPS-2026-1082',
    amount: 25000,
    paymentMode: 'RAZORPAY_UPI',
    transactionRef: 'pay_NzkX9Y5Q2mLa10',
    paidAt: '2026-07-08T14:32:00Z',
    receivedBy: 'Razorpay Gateway',
    status: 'SUCCESS',
    feeHeadBreakdown: [
      { headName: 'Quarter 2 Tuition Fee', amount: 21000 },
      { headName: 'Lab & Co-curricular', amount: 4000 },
    ],
  },
  {
    id: 'pay-002',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    receiptNo: 'RCP-APEX-2025-0491',
    amount: 40000,
    paymentMode: 'RAZORPAY_CARD',
    transactionRef: 'pay_OpoY4k91Dks82',
    paidAt: '2025-09-14T11:20:00Z',
    receivedBy: 'Razorpay Gateway',
    status: 'SUCCESS',
    feeHeadBreakdown: [
      { headName: 'Installment 2 Academic Fee', amount: 40000 },
    ],
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-school-term1',
    tenantId: 'tenant-school-1',
    name: 'Half-Yearly Term Examination 2026',
    examType: 'SCHOOL_TERM',
    groupIds: ['class-10-a', 'class-10-b'],
    startDate: '2026-09-15',
    endDate: '2026-09-26',
    totalMarks: 400,
    isPublished: true,
    subjects: [
      { subjectName: 'Mathematics', maxMarks: 100, passMarks: 33, date: '2026-09-15' },
      { subjectName: 'Physics & Chemistry (Science)', maxMarks: 100, passMarks: 33, date: '2026-09-18' },
      { subjectName: 'English Core', maxMarks: 100, passMarks: 33, date: '2026-09-22' },
      { subjectName: 'Social Science', maxMarks: 100, passMarks: 33, date: '2026-09-26' },
    ],
  },
  {
    id: 'exam-coaching-mock4',
    tenantId: 'tenant-coaching-1',
    name: 'All-India JEE Advanced Mock Test Series #04',
    examType: 'COACHING_TEST_SERIES',
    groupIds: ['batch-jee-alpha'],
    startDate: '2026-08-20',
    endDate: '2026-08-20',
    totalMarks: 300,
    isPublished: true,
    subjects: [
      { subjectName: 'Physics (Mechanics & Waves)', maxMarks: 100, passMarks: 35, date: '2026-08-20' },
      { subjectName: 'Chemistry (Physical & Inorganic)', maxMarks: 100, passMarks: 35, date: '2026-08-20' },
      { subjectName: 'Mathematics (Calculus & Vectors)', maxMarks: 100, passMarks: 35, date: '2026-08-20' },
    ],
  },
];

export const INITIAL_EXAM_RESULTS: StudentExamResult[] = [
  // School Result: Aarav Kapoor
  {
    id: 'res-101',
    tenantId: 'tenant-school-1',
    examId: 'exam-school-term1',
    examName: 'Half-Yearly Term Examination 2026',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    groupName: 'Class 10 - A',
    marksObtained: [
      { subjectName: 'Mathematics', marks: 96, maxMarks: 100, grade: 'A1' },
      { subjectName: 'Physics & Chemistry (Science)', marks: 91, maxMarks: 100, grade: 'A1' },
      { subjectName: 'English Core', marks: 88, maxMarks: 100, grade: 'A2' },
      { subjectName: 'Social Science', marks: 84, maxMarks: 100, grade: 'B1' },
    ],
    totalMarks: 359,
    totalMaxMarks: 400,
    percentage: 89.75,
    grade: 'A1',
    rank: 3,
    totalInGroup: 38,
    aiSummary: 'Aarav exhibits outstanding analytical aptitude in Mathematics (96%) and Science (91%). With dedicated practice in descriptive Social Science answers, he is on track for top-tier board distinction.',
  },
  // Coaching Result: Rohan Shukla
  {
    id: 'res-201',
    tenantId: 'tenant-coaching-1',
    examId: 'exam-coaching-mock4',
    examName: 'All-India JEE Advanced Mock Test Series #04',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    admissionNo: 'APX-2026-889',
    groupName: 'JEE Alpha 2027',
    marksObtained: [
      { subjectName: 'Physics (Mechanics & Waves)', marks: 88, maxMarks: 100 },
      { subjectName: 'Chemistry (Physical & Inorganic)', marks: 79, maxMarks: 100 },
      { subjectName: 'Mathematics (Calculus & Vectors)', marks: 92, maxMarks: 100 },
    ],
    totalMarks: 259,
    totalMaxMarks: 300,
    percentage: 86.33,
    rank: 4,
    totalInGroup: 38,
    aiSummary: 'Rohan demonstrated top-decile mastery in Advanced Calculus and Kinematics. Increasing accuracy in multi-correct Inorganic Chemistry questions will elevate his predicted All-India Rank into the top 500.',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // School Slots
  {
    id: 'slot-1',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '08:30',
    endTime: '09:15',
    subject: 'Physics',
    teacherId: 'staff-101',
    teacherName: 'Rajesh Sharma',
    roomNo: 'Lab 201',
    color: '#0284c7',
  },
  {
    id: 'slot-2',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '09:15',
    endTime: '10:00',
    subject: 'Mathematics',
    teacherId: 'staff-102',
    teacherName: 'Meenakshi Sundaram',
    roomNo: 'Room 102',
    color: '#7c3aed',
  },
  {
    id: 'slot-3',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '10:15',
    endTime: '11:00',
    subject: 'English Core',
    teacherId: 'staff-103',
    teacherName: 'Priyanka Sen',
    roomNo: 'Room 102',
    color: '#059669',
  },

  // Coaching Slots
  {
    id: 'slot-c1',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    dayOfWeek: 'MONDAY',
    startTime: '07:30',
    endTime: '09:30',
    subject: 'Advanced Rotational Mechanics',
    teacherId: 'staff-201',
    teacherName: 'Er. Tarun Saxena',
    roomNo: 'Faraday Hall 301',
    color: '#7c3aed',
  },
  {
    id: 'slot-c2',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    dayOfWeek: 'MONDAY',
    startTime: '09:45',
    endTime: '11:30',
    subject: 'Reaction Mechanisms (Organic)',
    teacherId: 'staff-202',
    teacherName: 'Dr. Neha Gupta',
    roomNo: 'Faraday Hall 301',
    color: '#0284c7',
  },
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    subject: 'Physics',
    title: 'Numerical Problems on Light Reflection & Refraction',
    description: 'Solve NCERT Exemplar questions 1 to 15 from Chapter 10 in the physics notebook with ray diagrams.',
    assignedDate: '2026-08-28',
    dueDate: '2026-09-02',
    teacherName: 'Rajesh Sharma',
    submissionsCount: 31,
    totalStudents: 38,
  },
  {
    id: 'hw-2',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    subject: 'Physics',
    title: 'Daily Practice Sheet (DPP #18) - Center of Mass & Collisions',
    description: 'Attempt all 20 advanced single & multiple correct problems from Irodov and Apex Workbook Level 2.',
    assignedDate: '2026-08-30',
    dueDate: '2026-09-01',
    teacherName: 'Er. Tarun Saxena',
    submissionsCount: 28,
    totalStudents: 38,
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    tenantId: 'tenant-school-1',
    title: 'Schedule for Term 1 Pre-Board Examinations & Parent-Teacher Meet',
    content: 'Dear Parents & Students, the Mid-Term Examination schedule has been released. The PTM is scheduled for Saturday, 10:00 AM to 1:00 PM.',
    audience: 'ALL',
    priority: 'HIGH',
    publishedAt: '2026-08-25',
    author: 'Principal Office',
    hasAttachment: true,
  },
  {
    id: 'not-2',
    tenantId: 'tenant-coaching-1',
    title: 'National Talent Scholarship Test (NTST) Mock #4 Results Published',
    content: 'Scores and percentile rankings for All-India Mock #4 are now live in the student analytics portal. Video solutions have been uploaded to the resource repository.',
    audience: 'ALL',
    priority: 'URGENT',
    publishedAt: '2026-08-29',
    author: 'Academic Dean',
    hasAttachment: false,
  },
];

export const INITIAL_LEADS: LeadCRM[] = [
  {
    id: 'lead-1',
    tenantId: 'tenant-coaching-1',
    studentName: 'Kartik Vashishta',
    parentName: 'Vikas Vashishta',
    phone: '+91 98112 34567',
    email: 'vikas.v@gmail.com',
    interestedCourseOrClass: 'IIT-JEE 2-Year Comprehensive Foundation',
    source: 'WEBSITE',
    status: 'DEMO_SCHEDULED',
    assignedStaffName: 'Prof. Alok Singhal',
    followUpDate: '2026-09-02',
    notes: 'Student scored 94% in Class 10 boards. Interested in Physics demo class this Wednesday.',
    estimatedValue: 165000,
    createdAt: '2026-08-28',
  },
  {
    id: 'lead-2',
    tenantId: 'tenant-coaching-1',
    studentName: 'Sanya Mirza',
    parentName: 'Irfan Mirza',
    phone: '+91 98223 45678',
    interestedCourseOrClass: 'NEET Super-30 Intensive Crash & Test Series',
    source: 'WALK_IN',
    status: 'CONTACTED',
    assignedStaffName: 'Dr. Neha Gupta',
    followUpDate: '2026-09-01',
    notes: 'Walk-in inquiry at Hauz Khas center. Requested scholarship test details.',
    estimatedValue: 95000,
    createdAt: '2026-08-29',
  },
  {
    id: 'lead-3',
    tenantId: 'tenant-school-1',
    studentName: 'Vivaan Oberoi',
    parentName: 'Rohan Oberoi',
    phone: '+91 98334 56789',
    email: 'roberoi@oberoigroup.com',
    interestedCourseOrClass: 'Class 9 Admission (Session 2026-27)',
    source: 'REFERRAL',
    status: 'FOLLOW_UP',
    assignedStaffName: 'Dr. Sunita Verma',
    followUpDate: '2026-09-03',
    notes: 'Transfer case from Mumbai. Father requested school tour & document verification.',
    estimatedValue: 110000,
    createdAt: '2026-08-26',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-1',
    tenantId: 'tenant-school-1',
    userId: 'user-school-parent',
    title: 'Term 1 Exam Result Published',
    message: 'Aarav scored 89.75% (Rank 3) in the Half-Yearly Examinations.',
    type: 'EXAM_RESULT',
    createdAt: '2 hours ago',
    isRead: false,
    linkUrl: '/exams',
  },
  {
    id: 'n-2',
    tenantId: 'tenant-school-1',
    userId: 'user-school-parent',
    title: 'Attendance Confirmed via QR',
    message: 'Aarav entered the school premises at 08:15 AM today.',
    type: 'ATTENDANCE_ABSENT',
    createdAt: '3 hours ago',
    isRead: true,
    linkUrl: '/attendance',
  },
  {
    id: 'n-3',
    tenantId: 'tenant-coaching-1',
    userId: 'user-coaching-parent',
    title: 'Upcoming Fee Installment Due',
    message: 'Installment #3 of ₹60,000 is due on 15th Sep 2026.',
    type: 'FEE_DUE',
    createdAt: '1 day ago',
    isRead: false,
    linkUrl: '/fees',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-admin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'TENANT_ADMIN',
    action: 'fee.updated',
    category: 'FEES',
    entityType: 'FeeStructure',
    entityId: 'fee-cls-10',
    details: 'Updated Annual Tuition fee for Class 10 from ₹90,000 to ₹95,000',
    timestamp: '2026-08-31 11:25:10',
    status: 'SUCCESS',
    ipAddress: '192.168.1.104',
    oldValues: 'Tuition: ₹90,000',
    newValues: 'Tuition: ₹95,000',
  },
  {
    id: 'audit-2',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-teacher',
    actorName: 'Mrs. Sunita Verma',
    actorRole: 'TEACHER',
    action: 'attendance.updated',
    category: 'ATTENDANCE',
    entityType: 'AttendanceRecord',
    entityId: 'att-101',
    details: 'Corrected attendance status for Roll #12 from ABSENT to PRESENT',
    timestamp: '2026-08-31 10:42:00',
    status: 'SUCCESS',
    ipAddress: '192.168.1.145',
    oldValues: 'Status: ABSENT',
    newValues: 'Status: PRESENT',
  },
  {
    id: 'audit-3',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-admin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'TENANT_ADMIN',
    action: 'result.published',
    category: 'RESULTS',
    entityType: 'Exam',
    entityId: 'exam-term-1',
    details: 'Officially published Half-Yearly Report Cards & Class Ranks for Class 10A',
    timestamp: '2026-08-31 09:18:32',
    status: 'SUCCESS',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'audit-4',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-parent',
    actorName: 'Mr. Vikram Sharma',
    actorRole: 'PARENT',
    action: 'payment.success',
    category: 'PAYMENTS',
    entityType: 'PaymentTransaction',
    entityId: 'pay-2026-0081',
    details: 'Verified Razorpay UPI payment of ₹25,000 for Aarav Sharma (Receipt: RCP-DPS-2026-4412)',
    timestamp: '2026-08-30 16:15:00',
    status: 'SUCCESS',
    ipAddress: '49.36.128.44',
  },
  {
    id: 'audit-5',
    tenantId: 'tenant-coaching-1',
    actorId: 'user-coaching-admin',
    actorName: 'Er. Alok Bansal',
    actorRole: 'TENANT_ADMIN',
    action: 'student.created',
    category: 'STUDENT',
    entityType: 'Student',
    entityId: 'stu-jee-001',
    details: 'Enrolled new student Rohan Mehta into IIT-JEE Alpha 2027 Batch',
    timestamp: '2026-08-31 08:30:15',
    status: 'SUCCESS',
    ipAddress: '10.0.4.12',
  },
];

