import { 
  TenantConfig, 
  Branch,
  UserProfile, 
  Student, 
  Staff, 
  AcademicClass, 
  CoachingCourse, 
  CoachingBatch, 
  AttendanceRecord, 
  FeeStructure, 
  StudentFeeLedger, 
  PaymentTransaction, 
  Exam, 
  StudentExamResult, 
  GradeScale,
  TimetableSlot, 
  Homework, 
  Notice, 
  LeadCRM, 
  NotificationItem,
  AuditLog,
  Expense,
  ExpenseCategory,
  Vendor,
  VendorBill,
  BankAccount,
  PettyCashTransaction,
  AccountTransfer,
  DepartmentBudget,
  SalaryStructure,
  PayrollRun,
  Payslip,
  SalaryAdvance,
  InventoryCategory,
  Warehouse,
  InventoryItem,
  StockMovement,
  FixedAsset,
  AssetMaintenanceRecord,
  BookTitle,
  BookCopy,
  LibraryMember,
  BookCirculationRecord,
  BookReservation,
  TransportVehicle,
  TransportDriver,
  TransportRoute,
  RouteStop,
  StudentTransportEnrollment,
  TransportTrip,
  FuelLog,
  Hostel,
  HostelRoom,
  HostelBed,
  HostelAllocation,
  HostelAttendanceRecord,
  GatePass,
  HostelComplaint,
  HostelMess,
  MessMealPlan,
  StudentMessSubscription,
  MessDailyMenu,
  MealConsumptionRecord,
  MessFeedback,
  StudentHealthProfile,
  StudentAllergy,
  ClinicFacility,
  MedicalVisit,
  HealthScreening,
  VaccinationRecord,
} from '../types';

export const INITIAL_TENANTS: TenantConfig[] = [
  {
    id: 'tenant-school-1',
    name: 'Delhi International Public School',
    code: 'DIPS',
    tenantType: 'SCHOOL',
    status: 'active',
    logo: 'https://images.unsplash.com/photo-1594608661623-aa0bd3a69d98?w=150&auto=format&fit=crop&q=80',
    tagline: 'Empowering Minds, Shaping Tomorrow',
    primaryColor: '#0284c7', // Sky blue
    secondaryColor: '#0369a1',
    accentColor: '#f59e0b',
    address: 'Plot 42, Institutional Area, Sector 14, Dwarka, New Delhi - 110075',
    phone: '+91 11 2808 4500',
    email: 'admissions@delhiinternationalschool.edu.in',
    website: 'https://delhiinternationalschool.edu.in',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata',
    academicYear: '2026-2027',
    planName: 'Enterprise School SaaS',
    subscriptionRenewalDate: '2027-03-31',
    labels: {
      group: 'Class',
      subgroup: 'Section',
      groupPlural: 'Classes',
      student: 'Student',
      studentPlural: 'Students',
      staff: 'Teacher',
      staffPlural: 'Teachers',
      admission: 'Admission',
      period: 'Academic Year',
      exam: 'Examination',
      examPlural: 'Examinations',
      reportCard: 'Report Card',
      homework: 'Homework / Assignment',
      feeStructure: 'Annual Fee Structure',
    },
    features: {
      attendance: true,
      qrAttendance: true,
      fees: true,
      onlinePayments: true,
      exams: true,
      reportCards: true,
      testSeries: false,
      rankComparison: false,
      homework: true,
      timetable: true,
      communication: true,
      whatsappAlerts: true,
      inquiryCrm: true,
      certificates: true,
      hrPayroll: true,
      aiAssistant: true,
      aiReportSummary: true,
      transport: true,
      library: true,
      hostel: false,
    },
  },
  {
    id: 'tenant-coaching-1',
    name: 'Apex IIT-JEE & Medical Academy',
    code: 'APEX',
    tenantType: 'COACHING',
    status: 'active',
    logo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=150&auto=format&fit=crop&q=80',
    tagline: 'Pioneering Excellence in National Competitive Exams',
    primaryColor: '#7c3aed', // Purple
    secondaryColor: '#6d28d9',
    accentColor: '#10b981',
    address: 'Apex Tower, 3rd Floor, Commercial Complex, Kalu Sarai, Hauz Khas, New Delhi',
    phone: '+91 98765 43210',
    email: 'info@apexacademy.co.in',
    website: 'https://apexacademy.co.in',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata',
    academicYear: 'Session 2026-2027',
    planName: 'Coaching Institute Pro',
    subscriptionRenewalDate: '2027-04-15',
    labels: {
      group: 'Batch',
      subgroup: 'Track',
      groupPlural: 'Batches',
      student: 'Learner',
      studentPlural: 'Learners',
      staff: 'Faculty',
      staffPlural: 'Faculty',
      admission: 'Enrollment',
      period: 'Course Session',
      exam: 'Test Series / Mock Test',
      examPlural: 'Test Series',
      reportCard: 'Rank & Performance Analytics',
      homework: 'Daily Practice Sheet (DPP)',
      feeStructure: 'Course Fee Installment Plan',
    },
    features: {
      attendance: true,
      qrAttendance: true,
      fees: true,
      onlinePayments: true,
      exams: true,
      reportCards: false,
      testSeries: true,
      rankComparison: true,
      homework: true,
      timetable: true,
      communication: true,
      whatsappAlerts: true,
      inquiryCrm: true,
      certificates: true,
      hrPayroll: false,
      aiAssistant: true,
      aiReportSummary: true,
      transport: false,
      library: false,
      hostel: false,
    },
  },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-school-main',
    tenantId: 'tenant-school-1',
    name: 'Main Campus (Dwarka)',
    code: 'DWK-MAIN',
    isMain: true,
    address: 'Plot 42, Institutional Area, Sector 14, Dwarka, New Delhi - 110075',
    phone: '+91 11 2808 4500',
    email: 'dwarka@delhiinternationalschool.edu.in',
  },
  {
    id: 'branch-school-south',
    tenantId: 'tenant-school-1',
    name: 'South Campus (Saket)',
    code: 'SKT-SOUTH',
    isMain: false,
    address: 'Community Center, Saket, New Delhi - 110017',
    phone: '+91 11 4100 8820',
    email: 'saket@delhiinternationalschool.edu.in',
  },
  {
    id: 'branch-coaching-hauz',
    tenantId: 'tenant-coaching-1',
    name: 'Hauz Khas (Central Center)',
    code: 'HK-01',
    isMain: true,
    address: 'Apex Tower, Kalu Sarai, Hauz Khas, New Delhi',
    phone: '+91 98765 43210',
    email: 'hauzkhas@apexacademy.co.in',
  },
  {
    id: 'branch-coaching-noida',
    tenantId: 'tenant-coaching-1',
    name: 'Noida Hub (Sector 62)',
    code: 'NOIDA-02',
    isMain: false,
    address: 'Knowledge Park II, Sector 62, Noida - 201309',
    phone: '+91 98765 43211',
    email: 'noida@apexacademy.co.in',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  // Super Admin
  {
    id: 'user-superadmin',
    tenantId: 'platform',
    email: 'superadmin@edunexus.io',
    name: 'Vikramaditya Sharma',
    phone: '+91 99999 00001',
    role: 'SUPER_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    designation: 'Platform Director',
    createdAt: '2025-01-01T00:00:00Z',
  },
  // School Tenant Admin
  {
    id: 'user-school-admin',
    tenantId: 'tenant-school-1',
    email: 'principal@delhiinternationalschool.edu.in',
    name: 'Dr. Sunita Verma',
    phone: '+91 98111 22334',
    role: 'TENANT_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    designation: 'Principal & Chief Administrator',
    department: 'Administration',
    createdAt: '2025-02-01T00:00:00Z',
  },
  // School Teacher
  {
    id: 'user-school-teacher',
    tenantId: 'tenant-school-1',
    email: 'rajesh.sharma@delhiinternationalschool.edu.in',
    name: 'Rajesh Sharma',
    phone: '+91 98222 33445',
    role: 'TEACHER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    designation: 'Senior Physics PGT',
    department: 'Science',
    assignedGroupIds: ['class-10-a', 'class-12-a'],
    createdAt: '2025-02-15T00:00:00Z',
  },
  // School Accountant
  {
    id: 'user-school-accountant',
    tenantId: 'tenant-school-1',
    email: 'accounts@delhiinternationalschool.edu.in',
    name: 'Ramesh Kulkarni',
    phone: '+91 98111 55667',
    role: 'ACCOUNTANT',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    designation: 'Chief Accounts Officer & Bursar',
    department: 'Accounts & Finance',
    createdAt: '2025-02-10T00:00:00Z',
  },
  // School Receptionist / Staff
  {
    id: 'user-school-receptionist',
    tenantId: 'tenant-school-1',
    email: 'reception@delhiinternationalschool.edu.in',
    name: 'Pooja Bhatt',
    phone: '+91 98111 99000',
    role: 'STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    designation: 'Front Desk & Admissions Coordinator',
    department: 'Front Office',
    createdAt: '2025-02-12T00:00:00Z',
  },
  // School Parent (Multiple Children)
  {
    id: 'user-school-parent',
    tenantId: 'tenant-school-1',
    email: 'amit.kapoor@gmail.com',
    name: 'Amit Kapoor',
    phone: '+91 98333 44556',
    role: 'PARENT',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    designation: 'Parent',
    linkedStudentIds: ['student-101', 'student-102'], // Aarav Kapoor (Grade 10) & Ananya Kapoor (Grade 6)
    createdAt: '2025-03-01T00:00:00Z',
  },
  // School Student
  {
    id: 'user-school-student',
    tenantId: 'tenant-school-1',
    email: 'aarav.kapoor@student.dips.edu',
    name: 'Aarav Kapoor',
    phone: '+91 98444 55667',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    studentId: 'student-101',
    createdAt: '2025-03-01T00:00:00Z',
  },
  // Coaching Tenant Admin
  {
    id: 'user-coaching-admin',
    tenantId: 'tenant-coaching-1',
    email: 'director@apexacademy.co.in',
    name: 'Prof. Alok Singhal',
    phone: '+91 98555 66778',
    role: 'TENANT_ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    designation: 'Managing Director & Academic Dean',
    createdAt: '2025-01-10T00:00:00Z',
  },
  // Coaching Faculty
  {
    id: 'user-coaching-faculty',
    tenantId: 'tenant-coaching-1',
    email: 'dr.neha.gupta@apexacademy.co.in',
    name: 'Dr. Neha Gupta',
    phone: '+91 98666 77889',
    role: 'TEACHER',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    designation: 'Head of Chemistry (Ex-IIT Delhi Faculty)',
    department: 'Organic & Inorganic Chemistry',
    assignedGroupIds: ['batch-jee-alpha', 'batch-neet-super30'],
    createdAt: '2025-01-15T00:00:00Z',
  },
  // Coaching Parent
  {
    id: 'user-coaching-parent',
    tenantId: 'tenant-coaching-1',
    email: 'sanjay.shukla@hotmail.com',
    name: 'Sanjay Shukla',
    phone: '+91 98777 88990',
    role: 'PARENT',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    designation: 'Parent',
    linkedStudentIds: ['student-201'],
    createdAt: '2025-02-01T00:00:00Z',
  },
  // Coaching Student
  {
    id: 'user-coaching-student',
    tenantId: 'tenant-coaching-1',
    email: 'rohan.shukla@apex.in',
    name: 'Rohan Shukla',
    phone: '+91 98888 99001',
    role: 'STUDENT',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    studentId: 'student-201',
    createdAt: '2025-02-01T00:00:00Z',
  },
];

export const INITIAL_SCHOOL_CLASSES: AcademicClass[] = [
  {
    id: 'class-9',
    tenantId: 'tenant-school-1',
    name: 'Class 9',
    numericGrade: 9,
    sections: [
      { id: 'class-9-a', name: 'Section A', capacity: 40, classTeacherId: 'staff-103' },
      { id: 'class-9-b', name: 'Section B', capacity: 40, classTeacherId: 'staff-104' },
    ],
  },
  {
    id: 'class-10',
    tenantId: 'tenant-school-1',
    name: 'Class 10',
    numericGrade: 10,
    sections: [
      { id: 'class-10-a', name: 'Section A', capacity: 40, classTeacherId: 'staff-101' },
      { id: 'class-10-b', name: 'Section B', capacity: 40, classTeacherId: 'staff-102' },
    ],
  },
  {
    id: 'class-12',
    tenantId: 'tenant-school-1',
    name: 'Class 12 - Science',
    numericGrade: 12,
    stream: 'PCM & PCB',
    sections: [
      { id: 'class-12-a', name: 'Section A (PCM)', capacity: 35, classTeacherId: 'staff-101' },
      { id: 'class-12-b', name: 'Section B (PCB)', capacity: 35, classTeacherId: 'staff-105' },
    ],
  },
];

export const INITIAL_COACHING_COURSES: CoachingCourse[] = [
  {
    id: 'course-jee-2yr',
    tenantId: 'tenant-coaching-1',
    name: 'IIT-JEE 2-Year Comprehensive Foundation',
    code: 'JEE-2Y-PINNACLE',
    durationMonths: 24,
    feeAmount: 165000,
    description: 'Targeted preparation for JEE Main & Advanced covering Class 11th & 12th syllabus with regular mock series.',
    targetExam: 'JEE Advanced 2027',
  },
  {
    id: 'course-neet-1yr',
    tenantId: 'tenant-coaching-1',
    name: 'NEET Super-30 Intensive Crash & Test Series',
    code: 'NEET-INT-1Y',
    durationMonths: 12,
    feeAmount: 95000,
    description: 'High-yield medical entrance coaching with daily DPPs, biological diagrams drill, and NTA pattern tests.',
    targetExam: 'NEET (UG) 2026',
  },
  {
    id: 'course-olympiad',
    tenantId: 'tenant-coaching-1',
    name: 'Junior Science & Math Olympiad (KVPY / NSEJS)',
    code: 'OLYMPIAD-FOUND',
    durationMonths: 6,
    feeAmount: 45000,
    description: 'Advanced problem solving and analytical thinking for Grades 8-10.',
    targetExam: 'NSEJS / RMO / IOQM',
  },
];

export const INITIAL_COACHING_BATCHES: CoachingBatch[] = [
  {
    id: 'batch-jee-alpha',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-jee-2yr',
    name: 'JEE Alpha 2027 (Morning Batch)',
    startDate: '2025-04-15',
    endDate: '2027-04-30',
    schedule: 'Mon, Wed, Fri (07:30 AM - 11:30 AM)',
    facultyIds: ['staff-201', 'staff-202'],
    roomNo: 'Hall 301 - Faraday Hall',
    capacity: 45,
    enrolledCount: 38,
  },
  {
    id: 'batch-neet-super30',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-neet-1yr',
    name: 'NEET Super-30 Rankers (Evening)',
    startDate: '2025-06-01',
    endDate: '2026-05-15',
    schedule: 'Tue, Thu, Sat (04:00 PM - 08:00 PM)',
    facultyIds: ['staff-202', 'staff-203'],
    roomNo: 'Hall 204 - Charaka Hall',
    capacity: 35,
    enrolledCount: 32,
  },
  {
    id: 'batch-weekend-math',
    tenantId: 'tenant-coaching-1',
    courseId: 'course-olympiad',
    name: 'Advanced Calculus & Algebra Booster',
    startDate: '2025-08-01',
    endDate: '2026-02-28',
    schedule: 'Saturday & Sunday (10:00 AM - 01:00 PM)',
    facultyIds: ['staff-201'],
    roomNo: 'Studio Lab 1',
    capacity: 25,
    enrolledCount: 19,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  // School Students
  {
    id: 'student-101',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0481',
    rollNo: '101',
    firstName: 'Aarav',
    lastName: 'Kapoor',
    gender: 'MALE',
    dob: '2010-04-12',
    email: 'aarav.kapoor@student.dips.edu',
    phone: '+91 98444 55667',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    address: 'B-404, Palm Grove Apartments, Sector 12, Dwarka, New Delhi',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2021-04-01',
    parentName: 'Amit Kapoor',
    parentPhone: '+91 98333 44556',
    parentEmail: 'amit.kapoor@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-101-AARAV',
    bloodGroup: 'O+',
    emergencyContact: '+91 98333 44556',
  },
  {
    id: 'student-102',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0612',
    rollNo: '102',
    firstName: 'Ananya',
    lastName: 'Kapoor',
    gender: 'FEMALE',
    dob: '2014-08-22',
    email: 'ananya.kapoor@student.dips.edu',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: 'B-404, Palm Grove Apartments, Sector 12, Dwarka, New Delhi',
    status: 'ACTIVE',
    classId: 'class-9',
    sectionId: 'class-9-a',
    enrollmentDate: '2023-04-01',
    parentName: 'Amit Kapoor',
    parentPhone: '+91 98333 44556',
    parentEmail: 'amit.kapoor@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-102-ANANYA',
    bloodGroup: 'B+',
    emergencyContact: '+91 98333 44556',
  },
  {
    id: 'student-103',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0495',
    rollNo: '103',
    firstName: 'Dev',
    lastName: 'Malhotra',
    gender: 'MALE',
    dob: '2010-11-05',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    address: 'House 18, Block C, Vasant Kunj, New Delhi',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2022-04-01',
    parentName: 'Raman Malhotra',
    parentPhone: '+91 98111 88990',
    parentEmail: 'raman.malhotra@yahoo.com',
    parentRelationship: 'FATHER',
    qrCode: 'DIPS-STU-103-DEV',
    bloodGroup: 'A+',
  },
  {
    id: 'student-104',
    tenantId: 'tenant-school-1',
    admissionNo: 'DIPS/2026/0502',
    rollNo: '104',
    firstName: 'Pooja',
    lastName: 'Rao',
    gender: 'FEMALE',
    dob: '2010-02-14',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    address: 'Flat 12A, Golf Course Road, Gurugram',
    status: 'ACTIVE',
    classId: 'class-10',
    sectionId: 'class-10-a',
    enrollmentDate: '2021-04-01',
    parentName: 'Kavita Rao',
    parentPhone: '+91 98222 11223',
    parentEmail: 'kavita.rao@outlook.com',
    parentRelationship: 'MOTHER',
    qrCode: 'DIPS-STU-104-POOJA',
    bloodGroup: 'AB+',
  },

  // Coaching Students (Can belong to multiple batches!)
  {
    id: 'student-201',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-889',
    rollNo: 'J-01',
    firstName: 'Rohan',
    lastName: 'Shukla',
    gender: 'MALE',
    dob: '2008-06-18',
    email: 'rohan.shukla@apex.in',
    phone: '+91 98888 99001',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    address: '34, Anand Lok, August Kranti Marg, New Delhi',
    status: 'ACTIVE',
    courseIds: ['course-jee-2yr', 'course-olympiad'],
    batchIds: ['batch-jee-alpha', 'batch-weekend-math'], // In 2 simultaneous batches!
    enrollmentDate: '2025-04-18',
    parentName: 'Sanjay Shukla',
    parentPhone: '+91 98777 88990',
    parentEmail: 'sanjay.shukla@hotmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-201-ROHAN',
    bloodGroup: 'O+',
  },
  {
    id: 'student-202',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-902',
    rollNo: 'N-14',
    firstName: 'Ishita',
    lastName: 'Deshmukh',
    gender: 'FEMALE',
    dob: '2008-09-29',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    address: 'Sector 56, Sushant Lok Phase 2, Gurugram',
    status: 'ACTIVE',
    courseIds: ['course-neet-1yr'],
    batchIds: ['batch-neet-super30'],
    enrollmentDate: '2025-06-05',
    parentName: 'Dr. Anand Deshmukh',
    parentPhone: '+91 99110 33445',
    parentEmail: 'anand.deshmukh@gmail.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-202-ISHITA',
    bloodGroup: 'A+',
  },
  {
    id: 'student-203',
    tenantId: 'tenant-coaching-1',
    admissionNo: 'APX-2026-915',
    rollNo: 'J-02',
    firstName: 'Kabir',
    lastName: 'Choudhury',
    gender: 'MALE',
    dob: '2008-03-11',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    address: 'C-7, Green Park Extension, New Delhi',
    status: 'ACTIVE',
    courseIds: ['course-jee-2yr'],
    batchIds: ['batch-jee-alpha'],
    enrollmentDate: '2025-05-02',
    parentName: 'Sunil Choudhury',
    parentPhone: '+91 98115 54433',
    parentEmail: 'sunil.c@tcs.com',
    parentRelationship: 'FATHER',
    qrCode: 'APEX-LRN-203-KABIR',
    bloodGroup: 'B+',
  },
];

export const INITIAL_STAFF: Staff[] = [
  // School Staff
  {
    id: 'staff-101',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-042',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@delhiinternationalschool.edu.in',
    phone: '+91 98222 33445',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Science & Physics',
    designation: 'Senior Physics PGT',
    qualification: 'M.Sc. (Physics), B.Ed.',
    joiningDate: '2019-07-01',
    salary: 75000,
    status: 'ACTIVE',
    subjects: ['Physics', 'Science'],
    assignedGroupIds: ['class-10-a', 'class-12-a'],
  },
  {
    id: 'staff-102',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-058',
    name: 'Meenakshi Sundaram',
    email: 'meenakshi.s@delhiinternationalschool.edu.in',
    phone: '+91 98333 22110',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Mathematics',
    designation: 'HOD Mathematics',
    qualification: 'M.Sc. (Mathematics), Ph.D.',
    joiningDate: '2017-04-15',
    salary: 82000,
    status: 'ACTIVE',
    subjects: ['Mathematics', 'Advanced Math'],
    assignedGroupIds: ['class-10-b', 'class-12-a'],
  },
  {
    id: 'staff-103',
    tenantId: 'tenant-school-1',
    employeeCode: 'EMP-DIPS-089',
    name: 'Priyanka Sen',
    email: 'priyanka.sen@delhiinternationalschool.edu.in',
    phone: '+91 98444 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'English & Literature',
    designation: 'TGT English',
    qualification: 'M.A. (English Lit), B.Ed.',
    joiningDate: '2021-08-01',
    salary: 62000,
    status: 'ACTIVE',
    subjects: ['English Core', 'Literature'],
    assignedGroupIds: ['class-9-a', 'class-10-a'],
  },

  // Coaching Faculty
  {
    id: 'staff-201',
    tenantId: 'tenant-coaching-1',
    employeeCode: 'FAC-APX-01',
    name: 'Er. Tarun Saxena',
    email: 'tarun.saxena@apexacademy.co.in',
    phone: '+91 98555 44332',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Physics',
    designation: 'Senior Faculty & IIT-JEE Mentor (B.Tech IIT Bombay)',
    qualification: 'B.Tech (IIT Bombay)',
    joiningDate: '2020-03-01',
    salary: 160000,
    status: 'ACTIVE',
    subjects: ['Rotational Dynamics', 'Electrodynamics', 'Modern Physics'],
    assignedGroupIds: ['batch-jee-alpha', 'batch-weekend-math'],
  },
  {
    id: 'staff-202',
    tenantId: 'tenant-coaching-1',
    employeeCode: 'FAC-APX-02',
    name: 'Dr. Neha Gupta',
    email: 'dr.neha.gupta@apexacademy.co.in',
    phone: '+91 98666 77889',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'TEACHER',
    department: 'Chemistry',
    designation: 'Head of Chemistry (Ph.D. IIT Delhi)',
    qualification: 'M.Sc., Ph.D. (Chemistry)',
    joiningDate: '2021-01-10',
    salary: 150000,
    status: 'ACTIVE',
    subjects: ['Organic Chemistry', 'Coordination Compounds'],
    assignedGroupIds: ['batch-jee-alpha', 'batch-neet-super30'],
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today's School Attendance (Class 10-A)
  {
    id: 'att-101-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:15:30',
    method: 'QR_SCAN',
  },
  {
    id: 'att-103-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-103',
    studentName: 'Dev Malhotra',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:22:10',
    method: 'QR_SCAN',
  },
  {
    id: 'att-104-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-104',
    studentName: 'Pooja Rao',
    groupId: 'class-10-a',
    groupName: 'Class 10 - Section A',
    date: new Date().toISOString().split('T')[0],
    status: 'LATE',
    markedBy: 'Rajesh Sharma',
    markedAt: '08:45:00',
    method: 'MANUAL',
    notes: 'Late bus arrival',
  },

  // Today's Coaching Attendance (Batch JEE Alpha)
  {
    id: 'att-201-1',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Er. Tarun Saxena',
    markedAt: '07:28:45',
    method: 'QR_SCAN',
  },
  {
    id: 'att-203-1',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-203',
    studentName: 'Kabir Choudhury',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    date: new Date().toISOString().split('T')[0],
    status: 'PRESENT',
    markedBy: 'Er. Tarun Saxena',
    markedAt: '07:31:00',
    method: 'QR_SCAN',
  },
];

export const INITIAL_FEE_STRUCTURES: FeeStructure[] = [
  {
    id: 'fee-struct-school-10',
    tenantId: 'tenant-school-1',
    name: 'Class 10 Standard Annual Structure',
    groupId: 'class-10',
    heads: [
      { id: 'h1', name: 'Annual Tuition Fee', amount: 84000, frequency: 'ANNUAL' },
      { id: 'h2', name: 'Science & Computer Lab', amount: 12000, frequency: 'ANNUAL' },
      { id: 'h3', name: 'Sports & Co-curricular', amount: 6000, frequency: 'ANNUAL' },
      { id: 'h4', name: 'Examination & Library', amount: 4500, frequency: 'ANNUAL' },
    ],
    totalAmount: 106500,
  },
  {
    id: 'fee-struct-coaching-jee',
    tenantId: 'tenant-coaching-1',
    name: 'IIT-JEE 2-Year Full Package',
    groupId: 'course-jee-2yr',
    heads: [
      { id: 'ch1', name: 'Course Admission & Kit', amount: 25000, frequency: 'ONE_TIME' },
      { id: 'ch2', name: 'Academic Tuition & Faculty Mentorship', amount: 110000, frequency: 'ANNUAL' },
      { id: 'ch3', name: 'All-India Test Series & DPP Access', amount: 30000, frequency: 'ANNUAL' },
    ],
    totalAmount: 165000,
  },
];

export const INITIAL_FEE_LEDGERS: StudentFeeLedger[] = [
  // School Student: Aarav Kapoor
  {
    id: 'ledger-101',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    groupName: 'Class 10 - A',
    feeStructureId: 'fee-struct-school-10',
    totalFee: 106500,
    concession: 6500, // Sibling Concession
    netPayable: 100000,
    paidAmount: 50000,
    dueAmount: 50000,
    dueDate: '2026-09-30',
    status: 'PARTIAL',
    installments: [
      { installmentNo: 1, title: 'Quarter 1 (Apr - Jun)', amount: 25000, dueDate: '2026-04-10', paidDate: '2026-04-05', status: 'PAID' },
      { installmentNo: 2, title: 'Quarter 2 (Jul - Sep)', amount: 25000, dueDate: '2026-07-10', paidDate: '2026-07-08', status: 'PAID' },
      { installmentNo: 3, title: 'Quarter 3 (Oct - Dec)', amount: 25000, dueDate: '2026-10-10', status: 'PENDING' },
      { installmentNo: 4, title: 'Quarter 4 (Jan - Mar)', amount: 25000, dueDate: '2027-01-10', status: 'PENDING' },
    ],
  },
  // Coaching Student: Rohan Shukla
  {
    id: 'ledger-201',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    admissionNo: 'APX-2026-889',
    groupName: 'JEE Alpha 2027',
    feeStructureId: 'fee-struct-coaching-jee',
    totalFee: 165000,
    concession: 15000, // Apex Talent Search Scholarship (Rank 12)
    netPayable: 150000,
    paidAmount: 90000,
    dueAmount: 60000,
    dueDate: '2026-09-15',
    status: 'PARTIAL',
    installments: [
      { installmentNo: 1, title: 'Installment 1 (Enrollment)', amount: 50000, dueDate: '2025-04-18', paidDate: '2025-04-18', status: 'PAID' },
      { installmentNo: 2, title: 'Installment 2 (Mid-Year)', amount: 40000, dueDate: '2025-09-15', paidDate: '2025-09-14', status: 'PAID' },
      { installmentNo: 3, title: 'Installment 3 (Year 2 Kickoff)', amount: 60000, dueDate: '2026-04-15', status: 'PENDING' },
    ],
  },
];

export const INITIAL_PAYMENTS: PaymentTransaction[] = [
  {
    id: 'pay-001',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    receiptNo: 'RCP-DIPS-2026-1082',
    amount: 25000,
    paymentMode: 'RAZORPAY_UPI',
    transactionRef: 'pay_NzkX9Y5Q2mLa10',
    paidAt: '2026-07-08T14:32:00Z',
    receivedBy: 'Razorpay Gateway',
    status: 'SUCCESS',
    feeHeadBreakdown: [
      { headName: 'Quarter 2 Tuition Fee', amount: 21000 },
      { headName: 'Lab & Co-curricular', amount: 4000 },
    ],
  },
  {
    id: 'pay-002',
    tenantId: 'tenant-coaching-1',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    receiptNo: 'RCP-APEX-2025-0491',
    amount: 40000,
    paymentMode: 'RAZORPAY_CARD',
    transactionRef: 'pay_OpoY4k91Dks82',
    paidAt: '2025-09-14T11:20:00Z',
    receivedBy: 'Razorpay Gateway',
    status: 'SUCCESS',
    feeHeadBreakdown: [
      { headName: 'Installment 2 Academic Fee', amount: 40000 },
    ],
  },
];

export const INITIAL_GRADE_SCALES: GradeScale[] = [
  {
    id: 'scale-cbse-1',
    tenantId: 'tenant-school-1',
    name: 'CBSE Secondary 9-Point Scale',
    scaleType: 'CBSE_9_POINT',
    isDefault: true,
    bands: [
      { id: 'b1', grade: 'A1', minPercentage: 91, maxPercentage: 100, gradePoint: 10.0, description: 'Top 1/8th of passed candidates', isPassing: true },
      { id: 'b2', grade: 'A2', minPercentage: 81, maxPercentage: 90.99, gradePoint: 9.0, description: 'Next 1/8th of passed candidates', isPassing: true },
      { id: 'b3', grade: 'B1', minPercentage: 71, maxPercentage: 80.99, gradePoint: 8.0, description: 'Next 1/8th of passed candidates', isPassing: true },
      { id: 'b4', grade: 'B2', minPercentage: 61, maxPercentage: 70.99, gradePoint: 7.0, description: 'Next 1/8th of passed candidates', isPassing: true },
      { id: 'b5', grade: 'C1', minPercentage: 51, maxPercentage: 60.99, gradePoint: 6.0, description: 'Next 1/8th of passed candidates', isPassing: true },
      { id: 'b6', grade: 'C2', minPercentage: 41, maxPercentage: 50.99, gradePoint: 5.0, description: 'Next 1/8th of passed candidates', isPassing: true },
      { id: 'b7', grade: 'D', minPercentage: 33, maxPercentage: 40.99, gradePoint: 4.0, description: 'Minimum Qualifying Passing', isPassing: true },
      { id: 'b8', grade: 'E1', minPercentage: 21, maxPercentage: 32.99, gradePoint: 0.0, description: 'Needs Improvement / Re-eval', isPassing: false },
      { id: 'b9', grade: 'E2', minPercentage: 0, maxPercentage: 20.99, gradePoint: 0.0, description: 'Unsatisfactory / Essential Repeat', isPassing: false },
    ],
  },
  {
    id: 'scale-coaching-1',
    tenantId: 'tenant-coaching-1',
    name: 'Competitive Exam Percentile & Standard Grade',
    scaleType: 'PERCENTAGE_LETTER',
    isDefault: true,
    bands: [
      { id: 'cb1', grade: 'A+', minPercentage: 90, maxPercentage: 100, gradePoint: 10.0, description: 'Top 1% All-India Benchmark', isPassing: true },
      { id: 'cb2', grade: 'A', minPercentage: 80, maxPercentage: 89.99, gradePoint: 9.0, description: 'High Distinction Tier', isPassing: true },
      { id: 'cb3', grade: 'B+', minPercentage: 70, maxPercentage: 79.99, gradePoint: 8.0, description: 'Qualifying Advanced Tier', isPassing: true },
      { id: 'cb4', grade: 'B', minPercentage: 60, maxPercentage: 69.99, gradePoint: 7.0, description: 'Above Average Standard', isPassing: true },
      { id: 'cb5', grade: 'C', minPercentage: 50, maxPercentage: 59.99, gradePoint: 6.0, description: 'Foundation Mastery Needed', isPassing: true },
      { id: 'cb6', grade: 'D', minPercentage: 35, maxPercentage: 49.99, gradePoint: 4.0, description: 'Minimum Passing Threshold', isPassing: true },
      { id: 'cb7', grade: 'F', minPercentage: 0, maxPercentage: 34.99, gradePoint: 0.0, description: 'Did Not Qualify', isPassing: false },
    ],
  },
];

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-school-term1',
    tenantId: 'tenant-school-1',
    name: 'Half-Yearly Term Examination 2026',
    examType: 'SCHOOL_TERM',
    groupIds: ['class-10-a', 'class-10-b'],
    startDate: '2026-09-15',
    endDate: '2026-09-26',
    totalMarks: 400,
    status: 'PUBLISHED',
    isPublished: true,
    gradeScaleId: 'scale-cbse-1',
    passingRules: {
      overallMinPercentage: 40,
      subjectMinPercentage: 33,
      allowGraceMarks: true,
      maxGracePerSubject: 5,
      maxTotalGrace: 10,
    },
    subjects: [
      { subjectName: 'Mathematics', maxMarks: 100, passMarks: 33, date: '2026-09-15', theoryMax: 80, internalMax: 20 },
      { subjectName: 'Physics & Chemistry (Science)', maxMarks: 100, passMarks: 33, date: '2026-09-18', theoryMax: 70, practicalMax: 30 },
      { subjectName: 'English Core', maxMarks: 100, passMarks: 33, date: '2026-09-22', theoryMax: 80, internalMax: 20 },
      { subjectName: 'Social Science', maxMarks: 100, passMarks: 33, date: '2026-09-26', theoryMax: 80, internalMax: 20 },
    ],
  },
  {
    id: 'exam-coaching-mock4',
    tenantId: 'tenant-coaching-1',
    name: 'All-India JEE Advanced Mock Test Series #04',
    examType: 'COACHING_TEST_SERIES',
    groupIds: ['batch-jee-alpha'],
    startDate: '2026-08-20',
    endDate: '2026-08-20',
    totalMarks: 300,
    status: 'PUBLISHED',
    isPublished: true,
    gradeScaleId: 'scale-coaching-1',
    passingRules: {
      overallMinPercentage: 35,
      subjectMinPercentage: 30,
      allowGraceMarks: false,
      maxGracePerSubject: 0,
      maxTotalGrace: 0,
    },
    subjects: [
      { subjectName: 'Physics (Mechanics & Waves)', maxMarks: 100, passMarks: 35, date: '2026-08-20', theoryMax: 100 },
      { subjectName: 'Chemistry (Physical & Inorganic)', maxMarks: 100, passMarks: 35, date: '2026-08-20', theoryMax: 100 },
      { subjectName: 'Mathematics (Calculus & Vectors)', maxMarks: 100, passMarks: 35, date: '2026-08-20', theoryMax: 100 },
    ],
  },
];

export const INITIAL_EXAM_RESULTS: StudentExamResult[] = [
  // School Result: Aarav Kapoor (Published v1)
  {
    id: 'res-101',
    tenantId: 'tenant-school-1',
    examId: 'exam-school-term1',
    examName: 'Half-Yearly Term Examination 2026',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    rollNo: '10A-01',
    groupName: 'Class 10 - A',
    academicYear: '2026-2027',
    term: 'Half-Yearly Term 1',
    status: 'PUBLISHED',
    passStatus: 'PASS',
    version: 1,
    gradeScaleName: 'CBSE Secondary 9-Point Scale',
    attendancePercentage: 94.2,
    teacherRemarks: 'Aarav exhibits outstanding analytical rigor in STEM subjects. Consistently punctual and proactive in class discussions.',
    principalRemarks: 'Promoted with Academic Distinction. Keep up the commendable dedication.',
    approvedBy: 'Dr. Sunita Rao (Academic Principal)',
    approvedAt: '2026-09-28T14:30:00Z',
    publishedAt: '2026-09-29T10:00:00Z',
    marksObtained: [
      { subjectName: 'Mathematics', marks: 96, maxMarks: 100, theoryMarks: 77, internalMarks: 19, percentage: 96, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
      { subjectName: 'Physics & Chemistry (Science)', marks: 91, maxMarks: 100, theoryMarks: 63, practicalMarks: 28, percentage: 91, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
      { subjectName: 'English Core', marks: 88, maxMarks: 100, theoryMarks: 70, internalMarks: 18, percentage: 88, grade: 'A2', gradePoint: 9.0, passStatus: 'PASS' },
      { subjectName: 'Social Science', marks: 84, maxMarks: 100, theoryMarks: 66, internalMarks: 18, percentage: 84, grade: 'B1', gradePoint: 8.0, passStatus: 'PASS' },
    ],
    totalMarks: 359,
    totalMaxMarks: 400,
    percentage: 89.75,
    grade: 'A1',
    gradePoint: 9.25,
    gpa: 9.25,
    rank: 3,
    totalInGroup: 38,
    aiSummary: 'Aarav exhibits outstanding analytical aptitude in Mathematics (96%) and Science (91%). With dedicated practice in descriptive Social Science answers, he is on track for top-tier board distinction.',
  },
  // School Result: Ananya Sen (Class 10-A)
  {
    id: 'res-102',
    tenantId: 'tenant-school-1',
    examId: 'exam-school-term1',
    examName: 'Half-Yearly Term Examination 2026',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0482',
    rollNo: '10A-02',
    groupName: 'Class 10 - A',
    academicYear: '2026-2027',
    term: 'Half-Yearly Term 1',
    status: 'PUBLISHED',
    passStatus: 'PASS',
    version: 1,
    gradeScaleName: 'CBSE Secondary 9-Point Scale',
    attendancePercentage: 97.5,
    teacherRemarks: 'Brilliant conceptual clarity in Literature and Social Sciences. Maintains top academic discipline.',
    principalRemarks: 'Exemplary scholar. Ranked 1st in Class 10th cohort.',
    approvedBy: 'Dr. Sunita Rao (Academic Principal)',
    approvedAt: '2026-09-28T14:30:00Z',
    publishedAt: '2026-09-29T10:00:00Z',
    marksObtained: [
      { subjectName: 'Mathematics', marks: 98, maxMarks: 100, theoryMarks: 78, internalMarks: 20, percentage: 98, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
      { subjectName: 'Physics & Chemistry (Science)', marks: 95, maxMarks: 100, theoryMarks: 66, practicalMarks: 29, percentage: 95, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
      { subjectName: 'English Core', marks: 94, maxMarks: 100, theoryMarks: 75, internalMarks: 19, percentage: 94, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
      { subjectName: 'Social Science', marks: 92, maxMarks: 100, theoryMarks: 73, internalMarks: 19, percentage: 92, grade: 'A1', gradePoint: 10.0, passStatus: 'PASS' },
    ],
    totalMarks: 379,
    totalMaxMarks: 400,
    percentage: 94.75,
    grade: 'A1',
    gradePoint: 10.0,
    gpa: 10.0,
    rank: 1,
    totalInGroup: 38,
    aiSummary: 'Ananya demonstrated peerless academic mastery across all four curriculum subjects with an aggregate score of 94.75%.',
  },
  // Coaching Result: Rohan Shukla
  {
    id: 'res-201',
    tenantId: 'tenant-coaching-1',
    examId: 'exam-coaching-mock4',
    examName: 'All-India JEE Advanced Mock Test Series #04',
    studentId: 'student-201',
    studentName: 'Rohan Shukla',
    admissionNo: 'APX-2026-889',
    rollNo: 'JEE-889',
    groupName: 'JEE Alpha 2027',
    academicYear: '2026-2027',
    term: 'Mock Series Round 4',
    status: 'PUBLISHED',
    passStatus: 'PASS',
    version: 1,
    gradeScaleName: 'Competitive Exam Percentile & Standard Grade',
    attendancePercentage: 98.0,
    teacherRemarks: 'Exceptional speed in Mathematics Calculus section. Attention required to minimize negative marking in Organic reaction mechanisms.',
    principalRemarks: 'Predicted All-India Rank: 350-500. Maintain speed and negative control.',
    approvedBy: 'Er. V. K. Bansal (Academic Director)',
    approvedAt: '2026-08-21T18:00:00Z',
    publishedAt: '2026-08-22T08:00:00Z',
    marksObtained: [
      { subjectName: 'Physics (Mechanics & Waves)', marks: 88, maxMarks: 100, theoryMarks: 88, percentage: 88, grade: 'A', gradePoint: 9.0, passStatus: 'PASS' },
      { subjectName: 'Chemistry (Physical & Inorganic)', marks: 79, maxMarks: 100, theoryMarks: 79, percentage: 79, grade: 'B+', gradePoint: 8.0, passStatus: 'PASS' },
      { subjectName: 'Mathematics (Calculus & Vectors)', marks: 92, maxMarks: 100, theoryMarks: 92, percentage: 92, grade: 'A+', gradePoint: 10.0, passStatus: 'PASS' },
    ],
    totalMarks: 259,
    totalMaxMarks: 300,
    percentage: 86.33,
    grade: 'A',
    gradePoint: 9.0,
    gpa: 9.0,
    rank: 4,
    totalInGroup: 38,
    aiSummary: 'Rohan demonstrated top-decile mastery in Advanced Calculus and Kinematics. Increasing accuracy in multi-correct Inorganic Chemistry questions will elevate his predicted All-India Rank into the top 500.',
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  // School Slots
  {
    id: 'slot-1',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '08:30',
    endTime: '09:15',
    subject: 'Physics',
    teacherId: 'staff-101',
    teacherName: 'Rajesh Sharma',
    roomNo: 'Lab 201',
    color: '#0284c7',
  },
  {
    id: 'slot-2',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '09:15',
    endTime: '10:00',
    subject: 'Mathematics',
    teacherId: 'staff-102',
    teacherName: 'Meenakshi Sundaram',
    roomNo: 'Room 102',
    color: '#7c3aed',
  },
  {
    id: 'slot-3',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    dayOfWeek: 'MONDAY',
    startTime: '10:15',
    endTime: '11:00',
    subject: 'English Core',
    teacherId: 'staff-103',
    teacherName: 'Priyanka Sen',
    roomNo: 'Room 102',
    color: '#059669',
  },

  // Coaching Slots
  {
    id: 'slot-c1',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    dayOfWeek: 'MONDAY',
    startTime: '07:30',
    endTime: '09:30',
    subject: 'Advanced Rotational Mechanics',
    teacherId: 'staff-201',
    teacherName: 'Er. Tarun Saxena',
    roomNo: 'Faraday Hall 301',
    color: '#7c3aed',
  },
  {
    id: 'slot-c2',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    dayOfWeek: 'MONDAY',
    startTime: '09:45',
    endTime: '11:30',
    subject: 'Reaction Mechanisms (Organic)',
    teacherId: 'staff-202',
    teacherName: 'Dr. Neha Gupta',
    roomNo: 'Faraday Hall 301',
    color: '#0284c7',
  },
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    tenantId: 'tenant-school-1',
    groupId: 'class-10-a',
    groupName: 'Class 10 - A',
    subject: 'Physics',
    title: 'Numerical Problems on Light Reflection & Refraction',
    description: 'Solve NCERT Exemplar questions 1 to 15 from Chapter 10 in the physics notebook with ray diagrams.',
    assignedDate: '2026-08-28',
    dueDate: '2026-09-02',
    teacherName: 'Rajesh Sharma',
    submissionsCount: 31,
    totalStudents: 38,
  },
  {
    id: 'hw-2',
    tenantId: 'tenant-coaching-1',
    groupId: 'batch-jee-alpha',
    groupName: 'JEE Alpha 2027',
    subject: 'Physics',
    title: 'Daily Practice Sheet (DPP #18) - Center of Mass & Collisions',
    description: 'Attempt all 20 advanced single & multiple correct problems from Irodov and Apex Workbook Level 2.',
    assignedDate: '2026-08-30',
    dueDate: '2026-09-01',
    teacherName: 'Er. Tarun Saxena',
    submissionsCount: 28,
    totalStudents: 38,
  },
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not-1',
    tenantId: 'tenant-school-1',
    title: 'Schedule for Term 1 Pre-Board Examinations & Parent-Teacher Meet',
    content: 'Dear Parents & Students, the Mid-Term Examination schedule has been released. The PTM is scheduled for Saturday, 10:00 AM to 1:00 PM.',
    audience: 'ALL',
    priority: 'HIGH',
    publishedAt: '2026-08-25',
    author: 'Principal Office',
    hasAttachment: true,
  },
  {
    id: 'not-2',
    tenantId: 'tenant-coaching-1',
    title: 'National Talent Scholarship Test (NTST) Mock #4 Results Published',
    content: 'Scores and percentile rankings for All-India Mock #4 are now live in the student analytics portal. Video solutions have been uploaded to the resource repository.',
    audience: 'ALL',
    priority: 'URGENT',
    publishedAt: '2026-08-29',
    author: 'Academic Dean',
    hasAttachment: false,
  },
];

export const INITIAL_LEADS: LeadCRM[] = [
  {
    id: 'lead-1',
    tenantId: 'tenant-coaching-1',
    studentName: 'Kartik Vashishta',
    parentName: 'Vikas Vashishta',
    phone: '+91 98112 34567',
    email: 'vikas.v@gmail.com',
    interestedCourseOrClass: 'IIT-JEE 2-Year Comprehensive Foundation',
    source: 'WEBSITE',
    status: 'DEMO_SCHEDULED',
    assignedStaffName: 'Prof. Alok Singhal',
    followUpDate: '2026-09-02',
    notes: 'Student scored 94% in Class 10 boards. Interested in Physics demo class this Wednesday.',
    estimatedValue: 165000,
    createdAt: '2026-08-28',
  },
  {
    id: 'lead-2',
    tenantId: 'tenant-coaching-1',
    studentName: 'Sanya Mirza',
    parentName: 'Irfan Mirza',
    phone: '+91 98223 45678',
    interestedCourseOrClass: 'NEET Super-30 Intensive Crash & Test Series',
    source: 'WALK_IN',
    status: 'CONTACTED',
    assignedStaffName: 'Dr. Neha Gupta',
    followUpDate: '2026-09-01',
    notes: 'Walk-in inquiry at Hauz Khas center. Requested scholarship test details.',
    estimatedValue: 95000,
    createdAt: '2026-08-29',
  },
  {
    id: 'lead-3',
    tenantId: 'tenant-school-1',
    studentName: 'Vivaan Oberoi',
    parentName: 'Rohan Oberoi',
    phone: '+91 98334 56789',
    email: 'roberoi@oberoigroup.com',
    interestedCourseOrClass: 'Class 9 Admission (Session 2026-27)',
    source: 'REFERRAL',
    status: 'FOLLOW_UP',
    assignedStaffName: 'Dr. Sunita Verma',
    followUpDate: '2026-09-03',
    notes: 'Transfer case from Mumbai. Father requested school tour & document verification.',
    estimatedValue: 110000,
    createdAt: '2026-08-26',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'n-1',
    tenantId: 'tenant-school-1',
    userId: 'user-school-parent',
    title: 'Term 1 Exam Result Published',
    message: 'Aarav scored 89.75% (Rank 3) in the Half-Yearly Examinations.',
    type: 'EXAM_RESULT',
    createdAt: '2 hours ago',
    isRead: false,
    linkUrl: '/exams',
  },
  {
    id: 'n-2',
    tenantId: 'tenant-school-1',
    userId: 'user-school-parent',
    title: 'Attendance Confirmed via QR',
    message: 'Aarav entered the school premises at 08:15 AM today.',
    type: 'ATTENDANCE_ABSENT',
    createdAt: '3 hours ago',
    isRead: true,
    linkUrl: '/attendance',
  },
  {
    id: 'n-3',
    tenantId: 'tenant-coaching-1',
    userId: 'user-coaching-parent',
    title: 'Upcoming Fee Installment Due',
    message: 'Installment #3 of ₹60,000 is due on 15th Sep 2026.',
    type: 'FEE_DUE',
    createdAt: '1 day ago',
    isRead: false,
    linkUrl: '/fees',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-admin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'TENANT_ADMIN',
    action: 'fee.updated',
    category: 'FEES',
    entityType: 'FeeStructure',
    entityId: 'fee-cls-10',
    details: 'Updated Annual Tuition fee for Class 10 from ₹90,000 to ₹95,000',
    timestamp: '2026-08-31 11:25:10',
    status: 'SUCCESS',
    ipAddress: '192.168.1.104',
    oldValues: 'Tuition: ₹90,000',
    newValues: 'Tuition: ₹95,000',
  },
  {
    id: 'audit-2',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-teacher',
    actorName: 'Mrs. Sunita Verma',
    actorRole: 'TEACHER',
    action: 'attendance.updated',
    category: 'ATTENDANCE',
    entityType: 'AttendanceRecord',
    entityId: 'att-101',
    details: 'Corrected attendance status for Roll #12 from ABSENT to PRESENT',
    timestamp: '2026-08-31 10:42:00',
    status: 'SUCCESS',
    ipAddress: '192.168.1.145',
    oldValues: 'Status: ABSENT',
    newValues: 'Status: PRESENT',
  },
  {
    id: 'audit-3',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-admin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'TENANT_ADMIN',
    action: 'result.published',
    category: 'RESULTS',
    entityType: 'Exam',
    entityId: 'exam-term-1',
    details: 'Officially published Half-Yearly Report Cards & Class Ranks for Class 10A',
    timestamp: '2026-08-31 09:18:32',
    status: 'SUCCESS',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'audit-4',
    tenantId: 'tenant-school-1',
    actorId: 'user-school-parent',
    actorName: 'Mr. Vikram Sharma',
    actorRole: 'PARENT',
    action: 'payment.success',
    category: 'PAYMENTS',
    entityType: 'PaymentTransaction',
    entityId: 'pay-2026-0081',
    details: 'Verified Razorpay UPI payment of ₹25,000 for Aarav Sharma (Receipt: RCP-DPS-2026-4412)',
    timestamp: '2026-08-30 16:15:00',
    status: 'SUCCESS',
    ipAddress: '49.36.128.44',
  },
  {
    id: 'audit-5',
    tenantId: 'tenant-coaching-1',
    actorId: 'user-coaching-admin',
    actorName: 'Er. Alok Bansal',
    actorRole: 'TENANT_ADMIN',
    action: 'student.created',
    category: 'STUDENT',
    entityType: 'Student',
    entityId: 'stu-jee-001',
    details: 'Enrolled new student Rohan Mehta into IIT-JEE Alpha 2027 Batch',
    timestamp: '2026-08-31 08:30:15',
    status: 'SUCCESS',
    ipAddress: '10.0.4.12',
  },
];

export const INITIAL_TEACHER_ASSIGNMENTS = [
  {
    id: 'ta-1',
    tenantId: 'tenant-school-1',
    teacherId: 'staff-101',
    classId: 'class-10',
    sectionId: 'class-10-a',
    subjectId: 'Physics',
    academicYearId: '2026–2027',
    isClassTeacher: true,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'ta-2',
    tenantId: 'tenant-school-1',
    teacherId: 'staff-101',
    classId: 'class-12',
    sectionId: 'class-12-a',
    subjectId: 'Physics',
    academicYearId: '2026–2027',
    isClassTeacher: false,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'ta-3',
    tenantId: 'tenant-school-1',
    teacherId: 'staff-102',
    classId: 'class-10',
    sectionId: 'class-10-b',
    subjectId: 'Mathematics',
    academicYearId: '2026–2027',
    isClassTeacher: true,
    createdAt: '2026-04-01T08:00:00Z',
  },
  {
    id: 'ta-4',
    tenantId: 'tenant-coaching-1',
    teacherId: 'staff-201',
    batchId: 'batch-jee-alpha',
    subjectId: 'Advanced Physics',
    academicYearId: '2026–2027',
    isClassTeacher: true,
    createdAt: '2026-04-01T08:00:00Z',
  },
];

// -------------------------------------------------------------
// DOCUMENT 54: EXPENSES, FINANCE & ACCOUNTING INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_EXPENSE_CATEGORIES: ExpenseCategory[] = [
  { id: 'cat-rent', tenantId: 'tenant-school-1', name: 'Campus Lease & Facility Rent', code: 'EXP-RENT', budgetAmount: 1200000, color: 'purple' },
  { id: 'cat-util', tenantId: 'tenant-school-1', name: 'Electricity, Water & Utilities', code: 'EXP-UTIL', budgetAmount: 350000, color: 'amber' },
  { id: 'cat-tech', tenantId: 'tenant-school-1', name: 'IT Infrastructure, Software & SaaS', code: 'EXP-TECH', budgetAmount: 250000, color: 'blue' },
  { id: 'cat-lab', tenantId: 'tenant-school-1', name: 'Laboratory Chemicals & Equipment', code: 'EXP-LAB', budgetAmount: 200000, color: 'emerald' },
  { id: 'cat-stationery', tenantId: 'tenant-school-1', name: 'Printing, Worksheets & Stationery', code: 'EXP-STAT', budgetAmount: 180000, color: 'blue' },
  { id: 'cat-maint', tenantId: 'tenant-school-1', name: 'Repairs, Janitorial & Maintenance', code: 'EXP-MAINT', budgetAmount: 220000, color: 'slate' },
  { id: 'cat-mktg', tenantId: 'tenant-coaching-1', name: 'Admissions Campaign & Digital Marketing', code: 'EXP-MKTG', budgetAmount: 500000, color: 'purple' },
  { id: 'cat-books', tenantId: 'tenant-coaching-1', name: 'Study Modules & Question Bank Publishing', code: 'EXP-PUB', budgetAmount: 400000, color: 'emerald' },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'ven-1',
    tenantId: 'tenant-school-1',
    name: 'National Stationery & Educational Press',
    contactPerson: 'Harish Mehta',
    phone: '+91 98112 34567',
    email: 'billing@natpress.in',
    gstin: '07AAAAA0000A1Z5',
    address: '42 Asaf Ali Road, Daryaganj, New Delhi',
    bankName: 'HDFC Bank',
    accountNo: '50200018928391',
    ifsc: 'HDFC0000189',
    category: 'Stationery & Printing',
    paymentTerms: 'Net 30 Days',
  },
  {
    id: 'ven-2',
    tenantId: 'tenant-school-1',
    name: 'Sigma Scientific Apparatus Corp',
    contactPerson: 'Dr. Ananya Roy',
    phone: '+91 99201 88293',
    email: 'orders@sigmascientific.com',
    gstin: '07BBBBB1111B2Z6',
    address: '12 Okhla Industrial Area Phase-III, New Delhi',
    bankName: 'State Bank of India',
    accountNo: '30918290192',
    ifsc: 'SBIN0001290',
    category: 'Lab Equipment',
    paymentTerms: 'Immediate / 15 Days',
  },
  {
    id: 'ven-3',
    tenantId: 'tenant-coaching-1',
    name: 'Apex Precision Printing & Binding Works',
    contactPerson: 'Rajesh Agrawal',
    phone: '+91 97182 99012',
    email: 'dispatch@apexprinting.in',
    gstin: '08CCCCC2222C3Z7',
    address: 'Kota Industrial Area, Rajasthan',
    bankName: 'ICICI Bank',
    accountNo: '002105001298',
    ifsc: 'ICIC0000021',
    category: 'Study Modules',
    paymentTerms: 'Net 15 Days',
  },
];

export const INITIAL_VENDOR_BILLS: VendorBill[] = [
  {
    id: 'bill-101',
    tenantId: 'tenant-school-1',
    vendorId: 'ven-1',
    vendorName: 'National Stationery & Educational Press',
    billNo: 'INV-NP-2026-401',
    billDate: '2026-08-10',
    dueDate: '2026-09-10',
    amount: 32000,
    paidAmount: 32000,
    dueAmount: 0,
    status: 'PAID',
    category: 'Printing & Stationery',
    description: 'Half-yearly examination answer sheets and student progress booklets',
  },
  {
    id: 'bill-102',
    tenantId: 'tenant-school-1',
    vendorId: 'ven-2',
    vendorName: 'Sigma Scientific Apparatus Corp',
    billNo: 'INV-SIG-8821',
    billDate: '2026-08-25',
    dueDate: '2026-09-20',
    amount: 24500,
    paidAmount: 0,
    dueAmount: 24500,
    status: 'UNPAID',
    category: 'Laboratory Chemicals',
    description: 'Physics optical benches, lenses, and chemistry titration burettes',
  },
  {
    id: 'bill-201',
    tenantId: 'tenant-coaching-1',
    vendorId: 'ven-3',
    vendorName: 'Apex Precision Printing & Binding Works',
    billNo: 'APEX-PR-2026-89',
    billDate: '2026-08-15',
    dueDate: '2026-09-01',
    amount: 85000,
    paidAmount: 50000,
    dueAmount: 35000,
    status: 'PARTIAL',
    category: 'Study Modules',
    description: 'JEE Advanced Vol 1 Calculus & Mechanics modules (500 sets)',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-101',
    tenantId: 'tenant-school-1',
    categoryId: 'cat-tech',
    categoryName: 'IT Infrastructure, Software & SaaS',
    vendorName: 'Bharti Airtel Enterprise',
    amount: 8500,
    taxAmount: 1530,
    totalAmount: 10030,
    date: '2026-09-01',
    description: 'Monthly high-speed 1 Gbps leased line internet connection',
    paymentMethod: 'BANK_TRANSFER',
    status: 'PAID',
    voucherNo: 'VCH-2026-09-001',
    referenceNo: 'TXN-UTR-9918290',
    approvedBy: 'Dr. Sunita Rao (Principal)',
    approvedAt: '2026-09-01T10:00:00Z',
    paidAt: '2026-09-01T14:30:00Z',
    createdBy: 'Ramesh Gupta (Accountant)',
    createdAt: '2026-09-01T09:15:00Z',
  },
  {
    id: 'exp-102',
    tenantId: 'tenant-school-1',
    categoryId: 'cat-lab',
    categoryName: 'Laboratory Chemicals & Equipment',
    vendorId: 'ven-2',
    vendorName: 'Sigma Scientific Apparatus Corp',
    billId: 'bill-102',
    amount: 24500,
    taxAmount: 4410,
    totalAmount: 28910,
    date: '2026-08-28',
    description: 'Senior secondary science laboratory apparatus replenishment',
    paymentMethod: 'CHEQUE',
    status: 'APPROVED',
    voucherNo: 'VCH-2026-08-084',
    referenceNo: 'CHQ-889102',
    approvedBy: 'Dr. Sunita Rao (Principal)',
    approvedAt: '2026-08-29T11:00:00Z',
    createdBy: 'Ramesh Gupta (Accountant)',
    createdAt: '2026-08-28T16:00:00Z',
  },
  {
    id: 'exp-103',
    tenantId: 'tenant-school-1',
    categoryId: 'cat-maint',
    categoryName: 'Repairs, Janitorial & Maintenance',
    amount: 15400,
    totalAmount: 15400,
    date: '2026-09-02',
    description: 'Auditorium projector lamp repair and public address system servicing',
    paymentMethod: 'PETTY_CASH',
    status: 'PAID',
    voucherNo: 'VCH-2026-09-005',
    approvedBy: 'Dr. Sunita Rao (Principal)',
    approvedAt: '2026-09-02T12:00:00Z',
    paidAt: '2026-09-02T15:00:00Z',
    createdBy: 'Ramesh Gupta (Accountant)',
    createdAt: '2026-09-02T11:30:00Z',
  },
  {
    id: 'exp-104',
    tenantId: 'tenant-school-1',
    categoryId: 'cat-util',
    categoryName: 'Electricity, Water & Utilities',
    amount: 64200,
    totalAmount: 64200,
    date: '2026-09-03',
    description: 'Monthly campus high-tension electrical power bill',
    paymentMethod: 'BANK_TRANSFER',
    status: 'PENDING_APPROVAL',
    voucherNo: 'VCH-2026-09-012',
    createdBy: 'Ramesh Gupta (Accountant)',
    createdAt: '2026-09-03T09:00:00Z',
  },
];

export const INITIAL_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'acc-1',
    tenantId: 'tenant-school-1',
    accountName: 'Operating & Salary Disbursement Account',
    bankName: 'HDFC Bank Ltd',
    accountNo: '50100492819201',
    ifsc: 'HDFC0000189',
    branch: 'Connaught Place, New Delhi',
    accountType: 'CURRENT',
    balance: 1684000,
    isPrimary: true,
  },
  {
    id: 'acc-2',
    tenantId: 'tenant-school-1',
    accountName: 'Online Student Fee Collection Escrow',
    bankName: 'ICICI Bank Ltd',
    accountNo: '002105991829',
    ifsc: 'ICIC0000021',
    branch: 'Nehru Place, New Delhi',
    accountType: 'COLLECTION',
    balance: 924500,
    isPrimary: false,
  },
  {
    id: 'acc-3',
    tenantId: 'tenant-coaching-1',
    accountName: 'Apex Operations & Student Revenue Account',
    bankName: 'State Bank of India',
    accountNo: '38192019281',
    ifsc: 'SBIN0004012',
    branch: 'Vigyan Nagar, Kota',
    accountType: 'CURRENT',
    balance: 2450000,
    isPrimary: true,
  },
];

export const INITIAL_PETTY_CASH: PettyCashTransaction[] = [
  {
    id: 'pc-1',
    tenantId: 'tenant-school-1',
    type: 'DISBURSEMENT',
    amount: 450,
    category: 'Postage & Courier',
    description: 'Urgent speed post dispatch of examination board compliance forms',
    voucherNo: 'PC-2026-001',
    custodian: 'Ramesh Gupta',
    date: '2026-09-01',
    balanceAfter: 19550,
  },
  {
    id: 'pc-2',
    tenantId: 'tenant-school-1',
    type: 'DISBURSEMENT',
    amount: 1250,
    category: 'Hospitality & Refreshments',
    description: 'Tea and refreshments for visiting CBSE inspection panel',
    voucherNo: 'PC-2026-002',
    custodian: 'Ramesh Gupta',
    date: '2026-09-02',
    balanceAfter: 18300,
  },
  {
    id: 'pc-3',
    tenantId: 'tenant-school-1',
    type: 'DISBURSEMENT',
    amount: 800,
    category: 'Stationery',
    description: 'Emergency whiteboard marker pens & duster replacements for Class 10th block',
    voucherNo: 'PC-2026-003',
    custodian: 'Ramesh Gupta',
    date: '2026-09-03',
    balanceAfter: 17500,
  },
];

export const INITIAL_ACCOUNT_TRANSFERS: AccountTransfer[] = [
  {
    id: 'tr-1',
    tenantId: 'tenant-school-1',
    fromAccountId: 'acc-2',
    fromAccountName: 'Online Student Fee Collection Escrow',
    toAccountId: 'acc-1',
    toAccountName: 'Operating & Salary Disbursement Account',
    amount: 150000,
    transferDate: '2026-08-31',
    reference: 'SWEEP-AUG-2026',
    transferredBy: 'Ramesh Gupta',
    notes: 'Monthly automatic sweep of realized fee revenue to main operational account',
  },
];

export const INITIAL_DEPARTMENT_BUDGETS: DepartmentBudget[] = [
  { id: 'bud-1', tenantId: 'tenant-school-1', department: 'Academic & Laboratory Resources', academicYear: '2026–2027', allocatedAmount: 350000, utilizedAmount: 245000, alertThresholdPct: 85 },
  { id: 'bud-2', tenantId: 'tenant-school-1', department: 'Information Technology & Campus Wi-Fi', academicYear: '2026–2027', allocatedAmount: 280000, utilizedAmount: 185000, alertThresholdPct: 80 },
  { id: 'bud-3', tenantId: 'tenant-school-1', department: 'Campus Maintenance & Physical Infrastructure', academicYear: '2026–2027', allocatedAmount: 450000, utilizedAmount: 390000, alertThresholdPct: 85 },
  { id: 'bud-4', tenantId: 'tenant-coaching-1', department: 'Student Recruitment & Digital Branding', academicYear: '2026–2027', allocatedAmount: 600000, utilizedAmount: 410000, alertThresholdPct: 90 },
];

// -------------------------------------------------------------
// DOCUMENT 55: STAFF, PAYROLL & HR INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_SALARY_STRUCTURES: SalaryStructure[] = [
  {
    id: 'sal-struct-pgt',
    tenantId: 'tenant-school-1',
    name: 'Senior PGT & Academic Faculty Band',
    description: 'Applicable to Senior Secondary teachers (PGT/HOD)',
    basicSalary: 45000,
    hra: 18000,
    da: 9000,
    specialAllowance: 5000,
    conveyanceAllowance: 3000,
    pfDeduction: 5400,
    esiDeduction: 0,
    tdsDeduction: 3500,
    professionalTax: 200,
    netCalculated: 65900,
  },
  {
    id: 'sal-struct-admin',
    tenantId: 'tenant-school-1',
    name: 'Executive Admin & Accounts Grade',
    description: 'Accounts officer, HR managers, and senior librarians',
    basicSalary: 32000,
    hra: 12800,
    da: 6400,
    specialAllowance: 3000,
    conveyanceAllowance: 2000,
    pfDeduction: 3840,
    esiDeduction: 420,
    tdsDeduction: 1500,
    professionalTax: 200,
    netCalculated: 50240,
  },
  {
    id: 'sal-struct-coaching-senior',
    tenantId: 'tenant-coaching-1',
    name: 'Apex Senior IIT-JEE Faculty Band',
    description: 'Lead Subject Heads and IIT Mentors',
    basicSalary: 95000,
    hra: 38000,
    da: 19000,
    specialAllowance: 15000,
    conveyanceAllowance: 8000,
    pfDeduction: 11400,
    esiDeduction: 0,
    tdsDeduction: 18500,
    professionalTax: 200,
    netCalculated: 144900,
  },
];

export const INITIAL_PAYROLL_RUNS: PayrollRun[] = [
  {
    id: 'pr-2026-08',
    tenantId: 'tenant-school-1',
    month: 'August 2026',
    year: 2026,
    totalEmployees: 4,
    totalGross: 275000,
    totalDeductions: 38200,
    totalNetPayout: 236800,
    status: 'DISBURSED',
    calculatedAt: '2026-08-30T10:00:00Z',
    approvedBy: 'Dr. Sunita Rao (Principal)',
    approvedAt: '2026-08-31T14:00:00Z',
    disbursedAt: '2026-09-01T09:30:00Z',
    disbursedFromAccountId: 'acc-1',
    payslipCount: 4,
  },
  {
    id: 'pr-2026-09',
    tenantId: 'tenant-school-1',
    month: 'September 2026',
    year: 2026,
    totalEmployees: 4,
    totalGross: 275000,
    totalDeductions: 38200,
    totalNetPayout: 236800,
    status: 'CALCULATED',
    calculatedAt: '2026-09-02T16:00:00Z',
    payslipCount: 4,
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-101',
    tenantId: 'tenant-school-1',
    payrollRunId: 'pr-2026-08',
    payslipNo: 'PS-DIPS-2026-08-042',
    staffId: 'staff-101',
    employeeCode: 'EMP-DIPS-042',
    staffName: 'Rajesh Sharma',
    department: 'Science & Physics',
    designation: 'Senior Physics PGT',
    panNumber: 'ABCPS1234F',
    bankAccountNo: '501002938192',
    bankName: 'HDFC Bank Ltd',
    workingDays: 31,
    presentDays: 30,
    lopDays: 0,
    basicPay: 45000,
    hra: 18000,
    da: 9000,
    specialAllowance: 5000,
    conveyanceAllowance: 3000,
    grossEarnings: 80000,
    pfDeduction: 5400,
    esiDeduction: 0,
    tdsDeduction: 4500,
    professionalTax: 200,
    lopDeduction: 0,
    advanceDeduction: 0,
    totalDeductions: 10100,
    netSalary: 69900,
    status: 'PAID',
  },
  {
    id: 'ps-102',
    tenantId: 'tenant-school-1',
    payrollRunId: 'pr-2026-08',
    payslipNo: 'PS-DIPS-2026-08-058',
    staffId: 'staff-102',
    employeeCode: 'EMP-DIPS-058',
    staffName: 'Meenakshi Sundaram',
    department: 'Mathematics',
    designation: 'HOD Mathematics',
    panNumber: 'BNDPS9921K',
    bankAccountNo: '30918290192',
    bankName: 'State Bank of India',
    workingDays: 31,
    presentDays: 31,
    lopDays: 0,
    basicPay: 48000,
    hra: 19200,
    da: 9600,
    specialAllowance: 5000,
    conveyanceAllowance: 3000,
    grossEarnings: 84800,
    pfDeduction: 5760,
    esiDeduction: 0,
    tdsDeduction: 5200,
    professionalTax: 200,
    lopDeduction: 0,
    advanceDeduction: 0,
    totalDeductions: 11160,
    netSalary: 73640,
    status: 'PAID',
  },
];

export const INITIAL_SALARY_ADVANCES: SalaryAdvance[] = [
  {
    id: 'adv-101',
    tenantId: 'tenant-school-1',
    staffId: 'staff-103',
    staffName: 'Priyanka Sen',
    amount: 25000,
    requestedDate: '2026-08-15',
    reason: 'Medical emergency support for family member',
    repaymentMonths: 5,
    monthlyDeduction: 5000,
    status: 'APPROVED',
    approvedBy: 'Dr. Sunita Rao (Principal)',
  },
];

// -------------------------------------------------------------
// DOCUMENT 56: INVENTORY & ASSET MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_INVENTORY_CATEGORIES: InventoryCategory[] = [
  { id: 'icat-stn', tenantId: 'tenant-school-1', name: 'Examination & Office Stationery', code: 'CAT-STN' },
  { id: 'icat-lab', tenantId: 'tenant-school-1', name: 'Science Laboratory Consumables', code: 'CAT-LAB' },
  { id: 'icat-book', tenantId: 'tenant-school-1', name: 'Worksheets, Handouts & Printing Paper', code: 'CAT-BOOK' },
  { id: 'icat-mod', tenantId: 'tenant-coaching-1', name: 'Study Modules & Daily Practice Sheets', code: 'CAT-DPP' },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  { id: 'wh-main', tenantId: 'tenant-school-1', name: 'Main Campus Central Store', code: 'WH-CENTRAL', location: 'Administrative Block, Ground Floor', custodian: 'Ramesh Gupta' },
  { id: 'wh-lab', tenantId: 'tenant-school-1', name: 'Science Laboratory Vault', code: 'WH-LAB', location: 'Science Wing, 2nd Floor', custodian: 'Dr. Ananya Roy' },
  { id: 'wh-coaching', tenantId: 'tenant-coaching-1', name: 'Apex Kota Central Dispatch Depot', code: 'WH-APX', location: 'Vigyan Nagar Campus B', custodian: 'Rajesh Agrawal' },
];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'item-1',
    tenantId: 'tenant-school-1',
    sku: 'STN-A4-REAM',
    name: 'JK Copier A4 Paper (75 GSM, 500 Sheets)',
    categoryId: 'icat-stn',
    categoryName: 'Examination & Office Stationery',
    warehouseId: 'wh-main',
    warehouseName: 'Main Campus Central Store',
    unit: 'REAM',
    currentStock: 18,
    minimumStock: 10,
    reorderLevel: 25,
    unitPrice: 320,
    totalValue: 5760,
    status: 'LOW_STOCK',
  },
  {
    id: 'item-2',
    tenantId: 'tenant-school-1',
    sku: 'EXAM-ANS-SHEET',
    name: 'CBSE Standard 32-Page Lined Answer Booklets',
    categoryId: 'icat-stn',
    categoryName: 'Examination & Office Stationery',
    warehouseId: 'wh-main',
    warehouseName: 'Main Campus Central Store',
    unit: 'PACK',
    currentStock: 450,
    minimumStock: 100,
    reorderLevel: 150,
    unitPrice: 45,
    totalValue: 20250,
    status: 'IN_STOCK',
  },
  {
    id: 'item-3',
    tenantId: 'tenant-school-1',
    sku: 'LAB-ACID-HCL',
    name: 'Hydrochloric Acid (Analytical Grade, 2.5L)',
    categoryId: 'icat-lab',
    categoryName: 'Science Laboratory Consumables',
    warehouseId: 'wh-lab',
    warehouseName: 'Science Laboratory Vault',
    unit: 'LITRE',
    currentStock: 4,
    minimumStock: 3,
    reorderLevel: 5,
    unitPrice: 650,
    totalValue: 2600,
    status: 'LOW_STOCK',
  },
  {
    id: 'item-4',
    tenantId: 'tenant-coaching-1',
    sku: 'DPP-PHY-ADV-01',
    name: 'JEE Advanced Mechanics Module Sets',
    categoryId: 'icat-mod',
    categoryName: 'Study Modules & Daily Practice Sheets',
    warehouseId: 'wh-coaching',
    warehouseName: 'Apex Kota Central Dispatch Depot',
    unit: 'SET',
    currentStock: 220,
    minimumStock: 50,
    reorderLevel: 80,
    unitPrice: 850,
    totalValue: 187000,
    status: 'IN_STOCK',
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm-1',
    tenantId: 'tenant-school-1',
    itemId: 'item-1',
    itemName: 'JK Copier A4 Paper (75 GSM, 500 Sheets)',
    sku: 'STN-A4-REAM',
    type: 'STOCK_OUT',
    quantity: 10,
    unit: 'REAM',
    sourceWarehouseId: 'wh-main',
    recipient: 'Senior Exam Cell & Question Paper Print Desk',
    referenceDoc: 'ISSUE-VCH-2026-092',
    movementDate: '2026-09-01',
    recordedBy: 'Ramesh Gupta',
    remarks: 'Dispatched for Half-Yearly Question Paper printing',
  },
  {
    id: 'sm-2',
    tenantId: 'tenant-school-1',
    itemId: 'item-2',
    itemName: 'CBSE Standard 32-Page Lined Answer Booklets',
    sku: 'EXAM-ANS-SHEET',
    type: 'STOCK_IN',
    quantity: 500,
    unit: 'PACK',
    destWarehouseId: 'wh-main',
    vendorName: 'National Stationery & Educational Press',
    referenceDoc: 'INV-NP-2026-401',
    costPerUnit: 45,
    totalCost: 22500,
    movementDate: '2026-08-28',
    recordedBy: 'Ramesh Gupta',
    remarks: 'Annual stock delivery against Purchase Order PO-108',
  },
];

export const INITIAL_FIXED_ASSETS: FixedAsset[] = [
  {
    id: 'ast-1',
    tenantId: 'tenant-school-1',
    assetCode: 'AST-IT-LAB-042',
    name: 'Dell OptiPlex 7090 Desktop (Core i7, 16GB RAM)',
    category: 'Computers & IT',
    location: 'Computer Laboratory 2 (Station 12)',
    custodian: 'Amit Saxena (IT Admin)',
    purchaseDate: '2023-06-15',
    purchaseCost: 62000,
    vendorName: 'Bharti Technology Solutions',
    warrantyExpiry: '2026-06-14',
    serialNumber: 'CN-0K7938-19280',
    status: 'ACTIVE',
    lastMaintenanceDate: '2026-07-10',
    nextMaintenanceDate: '2026-10-10',
  },
  {
    id: 'ast-2',
    tenantId: 'tenant-school-1',
    assetCode: 'AST-AUD-PROJ-01',
    name: 'Epson Pro Cinema 4K Laser Projector',
    category: 'Audio-Visual & Projectors',
    location: 'Central Multi-Purpose Auditorium',
    custodian: 'Harish Mehta (Campus Supervisor)',
    purchaseDate: '2024-01-10',
    purchaseCost: 185000,
    vendorName: 'Vision AV Systems Ltd',
    warrantyExpiry: '2027-01-09',
    serialNumber: 'EPS-882190-KL',
    status: 'ACTIVE',
    lastMaintenanceDate: '2026-09-02',
    nextMaintenanceDate: '2026-12-02',
  },
  {
    id: 'ast-3',
    tenantId: 'tenant-school-1',
    assetCode: 'AST-SCI-SPEC-04',
    name: 'Digital Optical UV-Vis Spectrophotometer',
    category: 'Laboratory Apparatus',
    location: 'Chemistry Research Lab (Room 204)',
    custodian: 'Dr. Ananya Roy',
    purchaseDate: '2022-09-20',
    purchaseCost: 145000,
    vendorName: 'Sigma Scientific Apparatus Corp',
    warrantyExpiry: '2025-09-19',
    serialNumber: 'SIG-SPEC-9921',
    status: 'IN_MAINTENANCE',
    lastMaintenanceDate: '2026-08-20',
    nextMaintenanceDate: '2026-09-15',
  },
];

export const INITIAL_ASSET_MAINTENANCE: AssetMaintenanceRecord[] = [
  {
    id: 'maint-1',
    tenantId: 'tenant-school-1',
    assetId: 'ast-2',
    assetCode: 'AST-AUD-PROJ-01',
    assetName: 'Epson Pro Cinema 4K Laser Projector',
    maintenanceDate: '2026-09-02',
    type: 'CORRECTIVE',
    serviceProvider: 'Vision AV Systems Ltd',
    cost: 15400,
    details: 'Lamp replacement, dust filter vacuuming, and optical alignment calibration',
    performedBy: 'Vikas Sharma (Service Engineer)',
    status: 'COMPLETED',
  },
  {
    id: 'maint-2',
    tenantId: 'tenant-school-1',
    assetId: 'ast-3',
    assetCode: 'AST-SCI-SPEC-04',
    assetName: 'Digital Optical UV-Vis Spectrophotometer',
    maintenanceDate: '2026-09-15',
    type: 'AMC_SERVICE',
    serviceProvider: 'Sigma Scientific Apparatus Corp',
    cost: 4500,
    details: 'Half-yearly wavelength calibration and sensor diode diagnostic check',
    performedBy: 'Dr. Ananya Roy',
    status: 'SCHEDULED',
  },
];

// -------------------------------------------------------------
// DOCUMENT 57: LIBRARY MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_BOOK_TITLES: BookTitle[] = [
  {
    id: 'bt-1',
    tenantId: 'tenant-school-1',
    title: 'Concepts of Physics (Vol 1 & 2)',
    author: 'Dr. H.C. Verma',
    isbn: '978-8177091878',
    publisher: 'Bharati Bhawan',
    edition: '2024 Revised Edition',
    category: 'SCIENCE',
    language: 'English',
    shelfLocation: 'Stack A-03',
    totalCopies: 6,
    availableCopies: 4,
    coverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e37b73?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'bt-2',
    tenantId: 'tenant-school-1',
    title: 'Secondary School Mathematics for Class 10',
    author: 'R.S. Aggarwal & V. Aggarwal',
    isbn: '978-9389551402',
    publisher: 'Bharti Bhawan',
    edition: '18th Edition',
    category: 'MATHEMATICS',
    language: 'English',
    shelfLocation: 'Stack M-01',
    totalCopies: 8,
    availableCopies: 7,
    coverUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'bt-3',
    tenantId: 'tenant-school-1',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '978-0060935467',
    publisher: 'HarperCollins',
    edition: 'Classic Reissue',
    category: 'LITERATURE',
    language: 'English',
    shelfLocation: 'Stack L-04',
    totalCopies: 4,
    availableCopies: 3,
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'bt-4',
    tenantId: 'tenant-coaching-1',
    title: 'Advanced Problems in Coordinate Geometry for IIT-JEE',
    author: 'Vikas Gupta & Pankaj Joshi',
    isbn: '978-9388309196',
    publisher: 'Balaji Publications',
    edition: '7th Edition',
    category: 'COMPETITIVE_EXAM',
    language: 'English',
    shelfLocation: 'Kota Reserve Wing 1',
    totalCopies: 12,
    availableCopies: 10,
    coverUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_BOOK_COPIES: BookCopy[] = [
  {
    id: 'copy-101',
    tenantId: 'tenant-school-1',
    bookTitleId: 'bt-1',
    accessionNumber: 'ACC-DIPS-2026-001',
    barcode: 'BC-DIPS-001',
    condition: 'EXCELLENT',
    status: 'ISSUED',
    shelfLocation: 'Stack A-03',
    acquisitionDate: '2024-04-10',
    cost: 450,
  },
  {
    id: 'copy-102',
    tenantId: 'tenant-school-1',
    bookTitleId: 'bt-1',
    accessionNumber: 'ACC-DIPS-2026-002',
    barcode: 'BC-DIPS-002',
    condition: 'GOOD',
    status: 'AVAILABLE',
    shelfLocation: 'Stack A-03',
    acquisitionDate: '2024-04-10',
    cost: 450,
  },
  {
    id: 'copy-103',
    tenantId: 'tenant-school-1',
    bookTitleId: 'bt-2',
    accessionNumber: 'ACC-DIPS-2026-015',
    barcode: 'BC-DIPS-015',
    condition: 'EXCELLENT',
    status: 'AVAILABLE',
    shelfLocation: 'Stack M-01',
    acquisitionDate: '2025-01-15',
    cost: 520,
  },
  {
    id: 'copy-104',
    tenantId: 'tenant-school-1',
    bookTitleId: 'bt-3',
    accessionNumber: 'ACC-DIPS-2026-042',
    barcode: 'BC-DIPS-042',
    condition: 'GOOD',
    status: 'ISSUED',
    shelfLocation: 'Stack L-04',
    acquisitionDate: '2023-11-20',
    cost: 399,
  },
];

export const INITIAL_LIBRARY_MEMBERS: LibraryMember[] = [
  {
    id: 'mem-101',
    tenantId: 'tenant-school-1',
    memberType: 'STUDENT',
    personId: 'student-101',
    personName: 'Aarav Kapoor',
    cardNumber: 'LIB-CARD-2026-101',
    maxAllowedBooks: 3,
    activeIssuedCount: 1,
    status: 'ACTIVE',
  },
  {
    id: 'mem-102',
    tenantId: 'tenant-school-1',
    memberType: 'STUDENT',
    personId: 'student-102',
    personName: 'Ananya Sen',
    cardNumber: 'LIB-CARD-2026-102',
    maxAllowedBooks: 3,
    activeIssuedCount: 1,
    status: 'ACTIVE',
  },
  {
    id: 'mem-staff-1',
    tenantId: 'tenant-school-1',
    memberType: 'STAFF',
    personId: 'staff-101',
    personName: 'Rajesh Sharma',
    cardNumber: 'LIB-FAC-042',
    maxAllowedBooks: 6,
    activeIssuedCount: 0,
    status: 'ACTIVE',
  },
];

export const INITIAL_LIBRARY_CIRCULATION: BookCirculationRecord[] = [
  {
    id: 'circ-1',
    tenantId: 'tenant-school-1',
    copyId: 'copy-101',
    accessionNumber: 'ACC-DIPS-2026-001',
    bookTitle: 'Concepts of Physics (Vol 1 & 2)',
    memberId: 'mem-101',
    memberName: 'Aarav Kapoor',
    memberType: 'STUDENT',
    issuedDate: '2026-08-25',
    dueDate: '2026-09-08',
    status: 'ISSUED',
    fineAmount: 0,
    finePaid: false,
    issuedBy: 'Meenakshi Sundaram (Librarian)',
  },
  {
    id: 'circ-2',
    tenantId: 'tenant-school-1',
    copyId: 'copy-104',
    accessionNumber: 'ACC-DIPS-2026-042',
    bookTitle: 'To Kill a Mockingbird',
    memberId: 'mem-102',
    memberName: 'Ananya Sen',
    memberType: 'STUDENT',
    issuedDate: '2026-08-10',
    dueDate: '2026-08-24',
    status: 'OVERDUE',
    fineAmount: 45, // 9 days overdue * ₹5/day
    finePaid: false,
    issuedBy: 'Meenakshi Sundaram (Librarian)',
  },
];

// -------------------------------------------------------------
// DOCUMENT 58: TRANSPORT MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_TRANSPORT_VEHICLES: TransportVehicle[] = [
  {
    id: 'veh-1',
    tenantId: 'tenant-school-1',
    vehicleCode: 'BUS-01',
    registrationNumber: 'DL-1VB-4920',
    vehicleType: 'SCHOOL_BUS',
    capacity: 40,
    allocatedStudents: 32,
    ownership: 'OWNED',
    status: 'ACTIVE',
    assignedDriverName: 'Balwant Singh',
    insuranceExpiry: '2027-03-15',
    fitnessExpiry: '2026-11-20',
    pucExpiry: '2026-12-10',
    gpsDeviceId: 'GPS-TRK-9901',
  },
  {
    id: 'veh-2',
    tenantId: 'tenant-school-1',
    vehicleCode: 'BUS-02',
    registrationNumber: 'DL-1VB-8812',
    vehicleType: 'SCHOOL_BUS',
    capacity: 45,
    allocatedStudents: 41,
    ownership: 'OWNED',
    status: 'ACTIVE',
    assignedDriverName: 'Joginder Rawat',
    insuranceExpiry: '2027-05-10',
    fitnessExpiry: '2027-01-14',
    pucExpiry: '2026-10-25',
    gpsDeviceId: 'GPS-TRK-9902',
  },
  {
    id: 'veh-3',
    tenantId: 'tenant-coaching-1',
    vehicleCode: 'VAN-APX-01',
    registrationNumber: 'RJ-20-PA-1092',
    vehicleType: 'VAN',
    capacity: 14,
    allocatedStudents: 12,
    ownership: 'CONTRACTED',
    status: 'ACTIVE',
    assignedDriverName: 'Mohan Lal Verma',
    insuranceExpiry: '2026-09-30',
    fitnessExpiry: '2026-10-15',
    pucExpiry: '2026-09-20',
    gpsDeviceId: 'GPS-TRK-4401',
  },
];

export const INITIAL_TRANSPORT_DRIVERS: TransportDriver[] = [
  {
    id: 'drv-1',
    tenantId: 'tenant-school-1',
    name: 'Balwant Singh',
    phone: '+91 98119 22334',
    licenseNumber: 'DL-042011009218',
    licenseExpiry: '2029-08-14',
    assignedVehicleId: 'veh-1',
    assignedVehicleCode: 'BUS-01',
    policeVerified: true,
    status: 'ACTIVE',
  },
  {
    id: 'drv-2',
    tenantId: 'tenant-school-1',
    name: 'Joginder Rawat',
    phone: '+91 98220 33445',
    licenseNumber: 'DL-072015004412',
    licenseExpiry: '2028-11-20',
    assignedVehicleId: 'veh-2',
    assignedVehicleCode: 'BUS-02',
    policeVerified: true,
    status: 'ACTIVE',
  },
];

export const INITIAL_TRANSPORT_ROUTES: TransportRoute[] = [
  {
    id: 'rt-1',
    tenantId: 'tenant-school-1',
    routeCode: 'RT-01',
    name: 'Rohini Sector 11 – Pitampura – Campus',
    vehicleId: 'veh-1',
    vehicleCode: 'BUS-01',
    driverName: 'Balwant Singh',
    startPoint: 'Rohini Sector 11 Metro Station',
    endPoint: 'Delhi International Public School Campus',
    totalDistanceKm: 18.5,
    stops: [
      { id: 'st-1', stopName: 'Rohini Sector 11 Gate', pickupTime: '06:45 AM', dropTime: '02:45 PM', fareAmount: 2200, stopOrder: 1 },
      { id: 'st-2', stopName: 'Madhuban Chowk Red Light', pickupTime: '07:00 AM', dropTime: '02:30 PM', fareAmount: 2000, stopOrder: 2 },
      { id: 'st-3', stopName: 'Pitampura Power House', pickupTime: '07:15 AM', dropTime: '02:15 PM', fareAmount: 1800, stopOrder: 3 },
      { id: 'st-4', stopName: 'Main Campus Arrival Gate', pickupTime: '07:40 AM', dropTime: '01:50 PM', fareAmount: 0, stopOrder: 4 },
    ],
  },
  {
    id: 'rt-2',
    tenantId: 'tenant-school-1',
    routeCode: 'RT-02',
    name: 'Vasant Kunj – Saket – IIT Gate – Campus',
    vehicleId: 'veh-2',
    vehicleCode: 'BUS-02',
    driverName: 'Joginder Rawat',
    startPoint: 'Vasant Kunj Sector C Pocket 9',
    endPoint: 'Delhi International Public School Campus',
    totalDistanceKm: 22.0,
    stops: [
      { id: 'st-5', stopName: 'Vasant Kunj Fortis Roundabout', pickupTime: '06:40 AM', dropTime: '02:50 PM', fareAmount: 2500, stopOrder: 1 },
      { id: 'st-6', stopName: 'Saket Metro Station Gate 2', pickupTime: '07:00 AM', dropTime: '02:30 PM', fareAmount: 2200, stopOrder: 2 },
      { id: 'st-7', stopName: 'IIT Flyover Bus Stop', pickupTime: '07:18 AM', dropTime: '02:10 PM', fareAmount: 1900, stopOrder: 3 },
      { id: 'st-8', stopName: 'Main Campus Arrival Gate', pickupTime: '07:45 AM', dropTime: '01:50 PM', fareAmount: 0, stopOrder: 4 },
    ],
  },
];

export const INITIAL_TRANSPORT_ENROLLMENTS: StudentTransportEnrollment[] = [
  {
    id: 'te-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    classOrBatch: 'Class 10-A',
    routeId: 'rt-1',
    routeName: 'Rohini Sector 11 – Pitampura – Campus',
    stopId: 'st-1',
    stopName: 'Rohini Sector 11 Gate',
    vehicleId: 'veh-1',
    vehicleCode: 'BUS-01',
    monthlyFee: 2200,
    status: 'ACTIVE',
  },
  {
    id: 'te-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0488',
    classOrBatch: 'Class 10-A',
    routeId: 'rt-2',
    routeName: 'Vasant Kunj – Saket – IIT Gate – Campus',
    stopId: 'st-5',
    stopName: 'Vasant Kunj Fortis Roundabout',
    vehicleId: 'veh-2',
    vehicleCode: 'BUS-02',
    monthlyFee: 2500,
    status: 'ACTIVE',
  },
];

export const INITIAL_TRANSPORT_TRIPS: TransportTrip[] = [
  {
    id: 'trip-101',
    tenantId: 'tenant-school-1',
    tripDate: '2026-09-03',
    routeId: 'rt-1',
    routeName: 'Rohini Sector 11 – Pitampura – Campus',
    vehicleCode: 'BUS-01',
    driverName: 'Balwant Singh',
    tripType: 'MORNING_PICKUP',
    status: 'COMPLETED',
    boardedCount: 31,
    totalExpected: 32,
  },
  {
    id: 'trip-102',
    tenantId: 'tenant-school-1',
    tripDate: '2026-09-03',
    routeId: 'rt-2',
    routeName: 'Vasant Kunj – Saket – IIT Gate – Campus',
    vehicleCode: 'BUS-02',
    driverName: 'Joginder Rawat',
    tripType: 'MORNING_PICKUP',
    status: 'COMPLETED',
    boardedCount: 40,
    totalExpected: 41,
  },
];

export const INITIAL_FUEL_LOGS: FuelLog[] = [
  {
    id: 'fuel-1',
    tenantId: 'tenant-school-1',
    vehicleId: 'veh-1',
    vehicleCode: 'BUS-01',
    date: '2026-09-01',
    odometerReading: 48210,
    quantityLitres: 65,
    ratePerLitre: 89.5,
    totalCost: 5817.5,
    fuelStation: 'Indian Oil Corporation - Rohini',
    invoiceRef: 'IOC-ROH-9921',
  },
  {
    id: 'fuel-2',
    tenantId: 'tenant-school-1',
    vehicleId: 'veh-2',
    vehicleCode: 'BUS-02',
    date: '2026-09-02',
    odometerReading: 52140,
    quantityLitres: 70,
    ratePerLitre: 89.5,
    totalCost: 6265,
    fuelStation: 'Bharat Petroleum - Saket',
    invoiceRef: 'BPCL-SKT-1028',
  },
];

// -------------------------------------------------------------
// DOCUMENT 59: HOSTEL MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_HOSTELS: Hostel[] = [
  {
    id: 'hostel-1',
    tenantId: 'tenant-school-1',
    name: 'Tagore Senior Boys Residence',
    code: 'BH-1',
    genderPolicy: 'MALE',
    wardenName: 'Col. Virendra Rathore (Retd.)',
    wardenPhone: '+91 98112 33441',
    totalRooms: 24,
    totalBeds: 72,
    status: 'ACTIVE',
  },
  {
    id: 'hostel-2',
    tenantId: 'tenant-school-1',
    name: 'Sarojini Naidu Girls Residence',
    code: 'GH-1',
    genderPolicy: 'FEMALE',
    wardenName: 'Dr. Sunita Deshmukh',
    wardenPhone: '+91 98112 33442',
    totalRooms: 20,
    totalBeds: 60,
    status: 'ACTIVE',
  },
  {
    id: 'hostel-3',
    tenantId: 'tenant-coaching-1',
    name: 'Apex Super-30 JEE Aspirants Tower',
    code: 'APX-BH-A',
    genderPolicy: 'MALE',
    wardenName: 'Manish Tyagi',
    wardenPhone: '+91 94140 22119',
    totalRooms: 30,
    totalBeds: 60,
    status: 'ACTIVE',
  },
];

export const INITIAL_HOSTEL_ROOMS: HostelRoom[] = [
  {
    id: 'room-101',
    tenantId: 'tenant-school-1',
    hostelId: 'hostel-1',
    hostelCode: 'BH-1',
    block: 'Block A',
    floor: 1,
    roomNumber: '101',
    roomType: 'TRIPLE',
    capacity: 3,
    occupiedBeds: 1,
    hasAttachedBath: true,
    isAirConditioned: true,
    monthlyRent: 8500,
  },
  {
    id: 'room-102',
    tenantId: 'tenant-school-1',
    hostelId: 'hostel-1',
    hostelCode: 'BH-1',
    block: 'Block A',
    floor: 1,
    roomNumber: '102',
    roomType: 'DOUBLE',
    capacity: 2,
    occupiedBeds: 0,
    hasAttachedBath: true,
    isAirConditioned: false,
    monthlyRent: 7000,
  },
  {
    id: 'room-201',
    tenantId: 'tenant-school-1',
    hostelId: 'hostel-2',
    hostelCode: 'GH-1',
    block: 'Wing B',
    floor: 2,
    roomNumber: '201',
    roomType: 'DOUBLE',
    capacity: 2,
    occupiedBeds: 1,
    hasAttachedBath: true,
    isAirConditioned: true,
    monthlyRent: 9000,
  },
];

export const INITIAL_HOSTEL_BEDS: HostelBed[] = [
  {
    id: 'bed-101-1',
    tenantId: 'tenant-school-1',
    roomId: 'room-101',
    roomNumber: '101',
    hostelId: 'hostel-1',
    bedCode: 'BH1-A-101-B1',
    bedNumber: 1,
    status: 'OCCUPIED',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
  },
  {
    id: 'bed-101-2',
    tenantId: 'tenant-school-1',
    roomId: 'room-101',
    roomNumber: '101',
    hostelId: 'hostel-1',
    bedCode: 'BH1-A-101-B2',
    bedNumber: 2,
    status: 'VACANT',
  },
  {
    id: 'bed-101-3',
    tenantId: 'tenant-school-1',
    roomId: 'room-101',
    roomNumber: '101',
    hostelId: 'hostel-1',
    bedCode: 'BH1-A-101-B3',
    bedNumber: 3,
    status: 'VACANT',
  },
  {
    id: 'bed-201-1',
    tenantId: 'tenant-school-1',
    roomId: 'room-201',
    roomNumber: '201',
    hostelId: 'hostel-2',
    bedCode: 'GH1-B-201-B1',
    bedNumber: 1,
    status: 'OCCUPIED',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
  },
  {
    id: 'bed-201-2',
    tenantId: 'tenant-school-1',
    roomId: 'room-201',
    roomNumber: '201',
    hostelId: 'hostel-2',
    bedCode: 'GH1-B-201-B2',
    bedNumber: 2,
    status: 'VACANT',
  },
];

export const INITIAL_HOSTEL_ALLOCATIONS: HostelAllocation[] = [
  {
    id: 'alloc-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    gender: 'MALE',
    hostelId: 'hostel-1',
    hostelName: 'Tagore Senior Boys Residence (BH-1)',
    roomId: 'room-101',
    roomNumber: '101',
    bedId: 'bed-101-1',
    bedCode: 'BH1-A-101-B1',
    allocationDate: '2026-04-01',
    securityDeposit: 15000,
    monthlyFee: 8500,
    status: 'ACTIVE',
  },
  {
    id: 'alloc-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0488',
    gender: 'FEMALE',
    hostelId: 'hostel-2',
    hostelName: 'Sarojini Naidu Girls Residence (GH-1)',
    roomId: 'room-201',
    roomNumber: '201',
    bedId: 'bed-201-1',
    bedCode: 'GH1-B-201-B1',
    allocationDate: '2026-04-01',
    securityDeposit: 15000,
    monthlyFee: 9000,
    status: 'ACTIVE',
  },
];

export const INITIAL_HOSTEL_ATTENDANCE: HostelAttendanceRecord[] = [
  {
    id: 'hatt-1',
    tenantId: 'tenant-school-1',
    date: '2026-09-02',
    hostelId: 'hostel-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    roomNumber: '101',
    status: 'PRESENT',
  },
  {
    id: 'hatt-2',
    tenantId: 'tenant-school-1',
    date: '2026-09-02',
    hostelId: 'hostel-2',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    roomNumber: '201',
    status: 'PRESENT',
  },
];

export const INITIAL_GATE_PASSES: GatePass[] = [
  {
    id: 'gp-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    roomNumber: '101',
    passType: 'DAY_OUT',
    departureTime: '2026-09-06 09:00 AM',
    expectedReturn: '2026-09-06 06:00 PM',
    reason: 'Weekend family gathering in Connaught Place',
    approvedBy: 'Col. Virendra Rathore (Warden)',
    status: 'APPROVED',
  },
];

export const INITIAL_HOSTEL_COMPLAINTS: HostelComplaint[] = [
  {
    id: 'comp-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    roomNumber: '101',
    category: 'ELECTRICAL',
    description: 'Study lamp socket near Bed 1 is fluctuating',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    loggedAt: '2026-09-02T14:30:00Z',
  },
];

// -------------------------------------------------------------
// DOCUMENT 60: HOSTEL MESS MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_HOSTEL_MESSES: HostelMess[] = [
  {
    id: 'mess-1',
    tenantId: 'tenant-school-1',
    name: 'Annapurna Central Dining Hall',
    code: 'MESS-CENTRAL',
    hostelId: 'hostel-1',
    hostelName: 'Tagore & Sarojini Residences',
    seatingCapacity: 180,
    breakfastWindow: '07:00 AM - 08:30 AM',
    lunchWindow: '12:30 PM - 02:00 PM',
    snacksWindow: '05:00 PM - 06:00 PM',
    dinnerWindow: '07:45 PM - 09:15 PM',
    status: 'ACTIVE',
  },
  {
    id: 'mess-2',
    tenantId: 'tenant-coaching-1',
    name: 'Apex JEE Super Dining Facility',
    code: 'MESS-APX-01',
    hostelId: 'hostel-3',
    hostelName: 'Apex Tower',
    seatingCapacity: 90,
    breakfastWindow: '06:30 AM - 08:00 AM',
    lunchWindow: '01:00 PM - 02:30 PM',
    snacksWindow: '05:30 PM - 06:30 PM',
    dinnerWindow: '08:00 PM - 09:30 PM',
    status: 'ACTIVE',
  },
];

export const INITIAL_MESS_MEAL_PLANS: MessMealPlan[] = [
  {
    id: 'plan-1',
    tenantId: 'tenant-school-1',
    name: 'Full Boarding 4-Meals Regular (Veg/Non-Veg)',
    dietaryType: 'VEG',
    mealsIncluded: ['BREAKFAST', 'LUNCH', 'SNACKS', 'DINNER'],
    monthlyRate: 4800,
    description: 'Comprehensive 4-meal daily menu with milk, fresh fruits, and Sunday special feasts.',
  },
  {
    id: 'plan-2',
    tenantId: 'tenant-school-1',
    name: 'Pure Jain Satvik 4-Meals',
    dietaryType: 'JAIN',
    mealsIncluded: ['BREAKFAST', 'LUNCH', 'SNACKS', 'DINNER'],
    monthlyRate: 5000,
    description: 'Strict root-vegetable-free Satvik cuisine prepared in dedicated kitchen enclosures.',
  },
];

export const INITIAL_MESS_SUBSCRIPTIONS: StudentMessSubscription[] = [
  {
    id: 'sub-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    messId: 'mess-1',
    planId: 'plan-1',
    planName: 'Full Boarding 4-Meals Regular',
    dietaryPreference: 'NON_VEG',
    monthlyRate: 4800,
    status: 'ACTIVE',
  },
  {
    id: 'sub-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0488',
    messId: 'mess-1',
    planId: 'plan-1',
    planName: 'Full Boarding 4-Meals Regular',
    dietaryPreference: 'VEG',
    monthlyRate: 4800,
    status: 'ACTIVE',
  },
];

export const INITIAL_MESS_MENUS: MessDailyMenu[] = [
  {
    id: 'menu-thu',
    tenantId: 'tenant-school-1',
    dayOfWeek: 'THURSDAY',
    breakfast: 'Idli Sambar, Coconut Chutney, Boiled Eggs / Banana, Filter Coffee & Milk',
    lunch: 'Dal Makhani, Jeera Rice, Tawa Roti, Seasonal Bhindi Do Pyaza, Fresh Curd & Green Salad',
    snacks: 'Vegetable Cutlet, Mint Sauce, Hot Ginger Cardamom Tea',
    dinner: 'Paneer Butter Masala (Veg) / Murgh Kadhai (Non-Veg), Mixed Dal Tadka, Steamed Rice, Phulkas, Hot Gulab Jamun',
    specialNote: 'Special North Indian dinner feast',
  },
  {
    id: 'menu-fri',
    tenantId: 'tenant-school-1',
    dayOfWeek: 'FRIDAY',
    breakfast: 'Stuffed Aloo Paratha with White Butter, Curd, Pickle, Tea / Bournvita',
    lunch: 'Chole Masala, Amritsari Kulcha / Rice, Boondi Raita, Onion-Lemon Salad',
    snacks: 'Poha with Roasted Peanuts, Sev & Masala Tea',
    dinner: 'Egg Curry / Malai Kofta, Yellow Moong Dal, Jeera Pulao, Tandoori Roti, Kheer',
    specialNote: 'Chef special Amritsari Lunch',
  },
];

export const INITIAL_MEAL_CONSUMPTIONS: MealConsumptionRecord[] = [
  {
    id: 'mc-1',
    tenantId: 'tenant-school-1',
    date: '2026-09-03',
    mealType: 'BREAKFAST',
    messId: 'mess-1',
    totalExpected: 132,
    totalServed: 128,
    status: 'COMPLETED',
  },
  {
    id: 'mc-2',
    tenantId: 'tenant-school-1',
    date: '2026-09-03',
    mealType: 'LUNCH',
    messId: 'mess-1',
    totalExpected: 132,
    totalServed: 130,
    status: 'COMPLETED',
  },
  {
    id: 'mc-3',
    tenantId: 'tenant-school-1',
    date: '2026-09-03',
    mealType: 'DINNER',
    messId: 'mess-1',
    totalExpected: 132,
    totalServed: 0,
    status: 'SCHEDULED',
  },
];

export const INITIAL_MESS_FEEDBACK: MessFeedback[] = [
  {
    id: 'fb-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    date: '2026-09-03',
    mealType: 'LUNCH',
    rating: 5,
    comment: 'Dal Makhani was exceptional today! Warm rotis served right off the tawa.',
    category: 'TASTE',
    status: 'REVIEWED',
  },
];

// -------------------------------------------------------------
// DOCUMENT 61: HEALTH & MEDICAL MANAGEMENT INITIAL DATA
// -------------------------------------------------------------
export const INITIAL_CLINIC_FACILITIES: ClinicFacility[] = [
  {
    id: 'clinic-1',
    tenantId: 'tenant-school-1',
    name: 'Sanjeevani Central Health Clinic',
    location: 'Ground Floor, Administrative Block (Near Gate 2)',
    nurseInCharge: 'Sister Anjali Verma, RN',
    contactPhone: '+91 98110 55443 (Ext. 104)',
    bedCount: 6,
    status: 'ACTIVE',
  },
  {
    id: 'clinic-2',
    tenantId: 'tenant-coaching-1',
    name: 'Apex First-Aid & Wellness Room',
    location: 'Tower A, 1st Floor',
    nurseInCharge: 'Rameshwar Singh, Paramedic',
    contactPhone: '+91 94140 33221',
    bedCount: 3,
    status: 'ACTIVE',
  },
];

export const INITIAL_STUDENT_HEALTH_PROFILES: StudentHealthProfile[] = [
  {
    id: 'hp-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    bloodGroup: 'B+',
    heightCm: 168,
    weightKg: 58,
    bmi: 20.5,
    chronicConditions: 'Mild exercise-induced asthma (keeps inhaler)',
    dietaryRestrictions: 'Lactose sensitivity',
    emergencyContactName: 'Rajesh Kapoor (Father)',
    emergencyContactPhone: '+91 98111 22334',
    emergencyContactRelation: 'Father',
    preferredHospital: 'Max Super Speciality Hospital, Saket',
    updatedAt: '2026-08-20',
  },
  {
    id: 'hp-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0488',
    bloodGroup: 'O+',
    heightCm: 162,
    weightKg: 52,
    bmi: 19.8,
    chronicConditions: 'None',
    dietaryRestrictions: 'Vegetarian',
    emergencyContactName: 'Dr. Debashis Sen (Father)',
    emergencyContactPhone: '+91 98200 44556',
    emergencyContactRelation: 'Father',
    preferredHospital: 'Fortis Escorts Hospital, Okhla',
    updatedAt: '2026-08-22',
  },
];

export const INITIAL_STUDENT_ALLERGIES: StudentAllergy[] = [
  {
    id: 'al-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    substance: 'Peanuts & Tree Nuts',
    category: 'FOOD',
    severity: 'SEVERE',
    reaction: 'Skin rash, facial hives, mild shortness of breath',
    status: 'ACTIVE',
  },
  {
    id: 'al-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    substance: 'Penicillin / Amoxicillin',
    category: 'MEDICATION',
    severity: 'CRITICAL',
    reaction: 'Anaphylaxis warning - strict contraindication',
    status: 'ACTIVE',
  },
];

export const INITIAL_MEDICAL_VISITS: MedicalVisit[] = [
  {
    id: 'mv-1',
    tenantId: 'tenant-school-1',
    clinicId: 'clinic-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    admissionNo: 'DIPS/2026/0481',
    visitDate: '2026-09-02',
    visitTime: '11:15 AM',
    chiefComplaint: 'Twisted right ankle during basketball practice in PE period',
    symptoms: 'Mild swelling over lateral malleolus, localized pain on bearing weight',
    vitalTempF: 98.4,
    vitalPulse: 76,
    vitalBp: '118/74',
    diagnosis: 'Grade 1 Inversion Ankle Sprain (Right)',
    treatmentGiven: 'RICE protocol applied: Ice compression pack for 20 mins, crepe bandage immobilized, leg elevated',
    medicationGiven: 'Paracetamol 500mg SOS post-meal',
    status: 'COMPLETED',
    recordedBy: 'Sister Anjali Verma, RN',
    parentNotified: true,
  },
  {
    id: 'mv-2',
    tenantId: 'tenant-school-1',
    clinicId: 'clinic-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    admissionNo: 'DIPS/2026/0488',
    visitDate: '2026-09-03',
    visitTime: '09:40 AM',
    chiefComplaint: 'Dizziness and headache following morning assembly',
    symptoms: 'Mild dehydration, skipped breakfast',
    vitalTempF: 98.6,
    vitalPulse: 82,
    vitalBp: '108/68',
    diagnosis: 'Mild dehydration / Hypoglycemic fatigue',
    treatmentGiven: 'Rested in clinic bed for 30 minutes with ORS hydration drink and glucose biscuits',
    status: 'COMPLETED',
    recordedBy: 'Sister Anjali Verma, RN',
    parentNotified: false,
  },
];

export const INITIAL_HEALTH_SCREENINGS: HealthScreening[] = [
  {
    id: 'hs-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    date: '2026-07-15',
    screeningType: 'ANNUAL_CHECKUP',
    visionRight: '6/6',
    visionLeft: '6/6',
    dentalHealth: 'HEALTHY',
    generalFitness: 'EXCELLENT',
    doctorNotes: 'Excellent cardiopulmonary fitness. Cleared for all varsity sports.',
    examinerName: 'Dr. R. K. Goel, MBBS, MD',
  },
  {
    id: 'hs-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    date: '2026-07-15',
    screeningType: 'VISION',
    visionRight: '6/9',
    visionLeft: '6/9',
    dentalHealth: 'HEALTHY',
    generalFitness: 'GOOD',
    doctorNotes: 'Slight myopia detected. Recommended pediatric ophthalmologist evaluation for corrective glasses.',
    examinerName: 'Dr. Meenakshi Sunder, MS (Ophth)',
  },
];

export const INITIAL_VACCINATION_RECORDS: VaccinationRecord[] = [
  {
    id: 'vac-1',
    tenantId: 'tenant-school-1',
    studentId: 'student-101',
    studentName: 'Aarav Kapoor',
    vaccineName: 'Tetanus Toxoid / Tdap Booster',
    doseNumber: 1,
    dateAdministered: '2026-04-10',
    administeredBy: 'Delhi Govt Primary Health Center',
    certificateRef: 'PHC-DEL-2026-778',
    status: 'COMPLETED',
  },
  {
    id: 'vac-2',
    tenantId: 'tenant-school-1',
    studentId: 'student-102',
    studentName: 'Ananya Sen',
    vaccineName: 'MMR (Measles, Mumps, Rubella)',
    doseNumber: 2,
    dateAdministered: '2025-11-18',
    administeredBy: 'Apollo Childrens Clinic',
    certificateRef: 'APL-IMM-4491',
    status: 'COMPLETED',
  },
];






