import React,{useEffect,useState} from 'react';
import {useTenant} from '../../context/TenantContext';
import {useAuth} from '../../context/AuthContext';
import {financeService as api} from '../../services/financeService';
import {loadResources} from '../../services/resourceLoader';
import {canOpenModule} from '../../services/auth/permissionPolicy';
const tabs=['Chart of Accounts','Cash/Bank Accounts','Journals','Expenses','Other Income','General Ledger','Cash/Bank Book','Income/Expense Report','Fee Reconciliation'];
const money=(value:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value||0));
const Table=({heads,rows}:any)=><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr>{heads.map((h:string)=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i} className="border-t">{r.map((v:any,j:number)=><td key={j} className="p-3">{v}</td>)}</tr>)}</tbody></table></div>;
export function FinanceModule(){
 const {currentTenant}=useTenant(),{currentUser}=useAuth(),tenantId=currentTenant.id;
 const [tab,setTab]=useState(tabs[0]),[data,setData]=useState<any>({accounts:[],cash:[],journals:[],expenses:[],income:[],ledger:[]}),[errors,setErrors]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const blank={title:'',account_id:'',payment_account_id:'',amount:'',date:new Date().toISOString().slice(0,10)};
 const [form,setForm]=useState(blank);
 const load=async()=>{setLoading(true);try{
 // Account initialization precedes dependent finance lists, as required by the existing API.
 const accounts=await api.list(tenantId,'accounts');setData((d:any)=>({...d,accounts:accounts.data}));
 const result=await loadResources({cash:()=>api.list(tenantId,'cash-bank-accounts'),journals:()=>api.list(tenantId,'journals'),expenses:()=>api.list(tenantId,'expenses'),income:()=>api.list(tenantId,'other-income'),ledger:()=>api.list(tenantId,'reports/ledger')});setData((d:any)=>({...d,...result.data}));setErrors(result.errors);
 }catch(e:any){setErrors({accounts:e.message||'Unable to load finance accounts.'});}finally{setLoading(false);}};
 useEffect(()=>{if(canOpenModule(currentUser,'finance'))void load();},[tenantId]);
 if(!canOpenModule(currentUser,'finance'))return <p role="alert">Finance access is not permitted.</p>;
 const post=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{await api.post(tenantId,tab==='Expenses'?'expenses':'other-income',{...form,amount:Number(form.amount)});setForm(blank);setMessage(tab==='Expenses'?'Expense posted.':'Other income posted.');await load();}catch(e:any){setErrors(previous=>({...previous,mutation:e.message}));}finally{setBusy(false);}};
 const ledgers=(types:string[])=>data.ledger.filter((x:any)=>types.includes(x.account_type));
 const ledgerRows=(rows:any[])=>rows.map(x=>[x.code,x.name,x.account_type,money(x.total_debit),money(x.total_credit),money(x.balance)]);
 const cashLedgerIds=new Set(data.cash.map((x:any)=>x.ledger_account_id));
 return <div className="space-y-5"><h1 className="text-2xl font-bold">School Finance & Accounting</h1><p className="text-sm text-slate-500">School journals and balances from PostgreSQL.</p><button onClick={()=>void load()} className="rounded border px-3 py-2">Refresh finance</button>
 {loading&&<p role="status">Loading finance…</p>}{Object.entries(errors).map(([key,error])=><p key={key} role="alert" className="rounded border border-rose-200 bg-rose-50 p-3">{key}: {error}</p>)}{message&&<p role="status">{message}</p>}
 <div className="flex flex-wrap gap-2">{tabs.map(x=><button key={x} onClick={()=>{setTab(x);setForm(blank);setMessage('');}} className={`rounded border px-3 py-2 ${tab===x?'bg-indigo-600 text-white':'bg-white'}`}>{x}</button>)}</div>
 {tab==='Chart of Accounts'&&<Table heads={['Code','Account Name','Type']} rows={data.accounts.map((x:any)=>[x.code,x.name,x.account_type])}/>}
 {tab==='Cash/Bank Accounts'&&<Table heads={['Name','Type','Ledger Account']} rows={data.cash.map((x:any)=>[x.display_name,x.type,data.accounts.find((a:any)=>a.id===x.ledger_account_id)?.name||x.ledger_account_id])}/>}
 {tab==='Journals'&&data.journals.map((j:any)=><section key={j.id} className="rounded-xl border bg-white p-4"><h2>{j.entry_number} · {j.source_type} · {j.status}</h2><p>{String(j.transaction_date).slice(0,10)} · {j.description}</p><Table heads={['Account','Debit','Credit']} rows={j.lines.map((l:any)=>[data.accounts.find((a:any)=>a.id===l.account_id)?.name||l.account_id,money(l.debit),money(l.credit)])}/></section>)}
 {(tab==='Expenses'||tab==='Other Income')&&<><form onSubmit={post} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3"><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="block w-full rounded border p-2"/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="block w-full rounded border p-2"/></label><label>Date<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="block w-full rounded border p-2"/></label><label>{tab==='Expenses'?'Expense account':'Income account'}<select required value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})} className="block w-full rounded border p-2"><option value="">Select account</option>{data.accounts.filter((a:any)=>a.account_type===(tab==='Expenses'?'EXPENSE':'INCOME')).map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Cash/Bank account<select required value={form.payment_account_id} onChange={e=>setForm({...form,payment_account_id:e.target.value})} className="block w-full rounded border p-2"><option value="">Select account</option>{data.cash.map((a:any)=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select></label><button disabled={busy||!!errors.accounts||!!errors.cash} className="self-end rounded bg-indigo-600 p-2 text-white">{tab==='Expenses'?'Post expense':'Post income'}</button></form><Table heads={['Date','Reference','Title','Amount','Status']} rows={(tab==='Expenses'?data.expenses:data.income).map((x:any)=>[String(x.date).slice(0,10),x.voucher_no||x.receipt_no,x.title,money(x.amount),x.status])}/></>}
 {tab==='General Ledger'&&<Table heads={['Code','Account Name','Type','Debit','Credit','Balance']} rows={ledgerRows(data.ledger)}/>}
 {tab==='Cash/Bank Book'&&<Table heads={['Code','Account Name','Type','Debit','Credit','Balance']} rows={ledgerRows(data.ledger.filter((x:any)=>cashLedgerIds.has(x.id)))}/>}
 {tab==='Income/Expense Report'&&<><p>Income: {money(ledgers(['INCOME']).reduce((s:number,x:any)=>s+Number(x.balance),0))} · Expenses: {money(ledgers(['EXPENSE']).reduce((s:number,x:any)=>s+Number(x.balance),0))}</p><Table heads={['Code','Account Name','Type','Debit','Credit','Balance']} rows={ledgerRows(ledgers(['INCOME','EXPENSE']))}/></>}
 {tab==='Fee Reconciliation'&&<><p>Reconcile verified school fee payments into their existing journals. SaaS billing is separate.</p><button disabled={busy} onClick={async()=>{setBusy(true);try{const r:any=await api.post(tenantId,'reconcile/fee-payments',{});setMessage(`Reconciliation complete: ${r.data.totalProcessed} verified payment(s) checked.`);await load();}catch(e:any){setErrors(v=>({...v,reconciliation:e.message}));}finally{setBusy(false);}}} className="rounded border px-3 py-2">Reconcile fee payments</button></>}
 </div>;
}
