import { loadResources } from '../../services/resourceLoader';
import React,{useEffect,useState}from'react';import{useTenant}from'../../context/TenantContext';import{useAuth}from'../../context/AuthContext';import{academicOperationsService as api}from'../../services/academicOperationsService';import{masterDataService as master}from'../../services/masterDataService';
type Tab='staff'|'assignments'|'timetable'|'attendance';
const Field=({label,...p}:any)=><label className="text-xs font-medium text-slate-600">{label}<input {...p} className="mt-1 w-full rounded border p-2 text-sm"/></label>;
const Select=({label,items,value,onChange,required=false}:any)=><label className="text-xs font-medium text-slate-600">{label}<select required={required} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2 text-sm"><option value="">Select</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
export const AcademicOperationsModule:React.FC<{initialTab?:Tab}>=({initialTab='staff'})=>{const{currentTenant}=useTenant();const{can}=useAuth();const t=currentTenant.id;const[tab,setTab]=useState<Tab>(initialTab);const[data,setData]=useState<any>({staff:[],assignments:[],years:[],classes:[],sections:[],subjects:[],timetable:[],roster:[]});const[msg,setMsg]=useState('');const[err,setErr]=useState('');const[staff,setStaff]=useState<any>({employeeId:'',name:'',email:'',designation:'Teacher',department:'Academics',employmentType:'FULL_TIME',status:'ACTIVE',teacherProfile:{qualification:'',specialization:'',experienceYears:0}});const[assignment,setAssignment]=useState<any>({teacherId:'',subjectId:'',classId:'',sectionId:'',academicYearId:'',isPrimary:false});const[slot,setSlot]=useState<any>({academicYearId:'',classId:'',sectionId:'',subjectId:'',teacherId:'',dayOfWeek:1,startTime:'09:00',endTime:'09:45',room:''});const[scope,setScope]=useState<any>({academicYearId:'',classId:'',sectionId:'',date:new Date().toISOString().slice(0,10)});const[marks,setMarks]=useState<Record<string,string>>({});
const load=async()=>{setErr('');const resources:Record<string,()=>Promise<any>>={};
 if(can('teaching_assignments.view')) resources.assignments=()=>api.listAssignments(t);
 if(can('staff.view')) resources.staff=()=>api.listStaff(t);
 if(can('master_data.view')){resources.years=()=>master.listYears(t);resources.classes=()=>master.listClasses(t);resources.sections=()=>master.listSections(t);resources.subjects=()=>master.listSubjects(t);}
 else if(can('teaching_assignments.view'))resources.context=()=>api.teachingContext(t);
 const result=await loadResources(resources);const ctx:any=result.data.context;
 if(ctx){const unique=(key:string,name:string)=>Array.from(new Map(ctx.filter((x:any)=>x[key]).map((x:any)=>[x[key],{id:x[key],name:x[name],class_id:x.class_id}])).values());Object.assign(result.data,{years:unique('academic_year_id','academic_year_name'),classes:unique('class_id','class_name'),sections:unique('section_id','section_name'),subjects:unique('subject_id','subject_name')});}
 setData((previous:any)=>({...previous,...result.data}));setErr(Object.entries(result.errors).map(([key,message])=>key+': '+message).join(' · '));
};useEffect(()=>{load()},[t]);
const run=async(fn:()=>Promise<any>,m:string)=>{setErr('');setMsg('');try{const r=await fn();setMsg(m);await load();return r}catch(e:any){setErr(e.message)}};
const sections=data.sections.filter((x:any)=>x.class_id===(tab==='timetable'?slot.classId:scope.classId));
const loadSlots=async()=>{const r=await run(()=>api.listTimetable(t,{academicYearId:slot.academicYearId,classId:slot.classId,sectionId:slot.sectionId}),'Timetable loaded.');if(r)setData((d:any)=>({...d,timetable:r.data}))};
const loadRoster=async()=>{if(!scope.academicYearId||!scope.classId||!scope.sectionId||!scope.date){setErr('Select an academic year, class, section and date before loading attendance.');return;}const r=await run(()=>api.roster(t,scope),'Attendance roster loaded.');if(r){setData((d:any)=>({...d,roster:r.data}));setMarks(Object.fromEntries(r.data.map((x:any)=>[x.enrollment_id,x.status||'PRESENT'])));}};
return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Academic Operations</h2><p className="text-sm text-slate-500">Staff, teaching assignments, timetable, and enrollment attendance.</p></div>{err&&<div className="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{err}</div>}{msg&&<div className="rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}<div className="flex gap-2">{(['staff','assignments','timetable','attendance']as Tab[]).filter(x=>x==='staff'?can('staff.view'):x==='assignments'?can('teaching_assignments.view'):x==='timetable'?can('timetable.view'):can('attendance.view')).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded px-3 py-2 text-sm font-semibold ${tab===x?'bg-emerald-600 text-white':'border bg-white'}`}>{x}</button>)}</div>
{tab==='staff'&&<>{can('staff.manage')&&<form onSubmit={e=>{e.preventDefault();run(()=>api.createStaff(t,staff),'Staff member created.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><Field label="Employee ID" required value={staff.employeeId} onChange={(e:any)=>setStaff({...staff,employeeId:e.target.value})}/><Field label="Name" required value={staff.name} onChange={(e:any)=>setStaff({...staff,name:e.target.value})}/><Field label="Email" type="email" value={staff.email} onChange={(e:any)=>setStaff({...staff,email:e.target.value})}/><Field label="Designation" required value={staff.designation} onChange={(e:any)=>setStaff({...staff,designation:e.target.value})}/><Field label="Qualification" value={staff.teacherProfile.qualification} onChange={(e:any)=>setStaff({...staff,teacherProfile:{...staff.teacherProfile,qualification:e.target.value}})}/><Field label="Specialization" value={staff.teacherProfile.specialization} onChange={(e:any)=>setStaff({...staff,teacherProfile:{...staff.teacherProfile,specialization:e.target.value}})}/><button className="self-end rounded bg-emerald-600 p-2 text-white">Create staff / teacher</button></form>}<Table heads={['Employee','Name','Designation','Account','Action']} rows={data.staff.map((x:any)=>[x.employeeId,x.name,x.designation,x.accountEmail||'Not activated',can('teacher_accounts.manage')&&x.teacherProfile&&!x.userId?<button onClick={async()=>{const r=await run(()=>api.inviteTeacher(t,x.id),`Invitation created for ${x.name}.`);if(r)setMsg(`One-time onboarding token for ${x.name}: ${r.data.onboardingToken}`)}} className="text-emerald-700 underline">Invite</button>:'—'])}/></>}
{tab==='assignments'&&<>{can('teaching_assignments.manage')&&<form onSubmit={e=>{e.preventDefault();run(()=>api.createAssignment(t,{...assignment,sectionId:assignment.sectionId||null}),'Assignment created.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-6"><Select label="Teacher" required items={data.staff.filter((x:any)=>x.teacherProfile)} value={assignment.teacherId} onChange={(v:string)=>setAssignment({...assignment,teacherId:v})}/><Select label="Subject" required items={data.subjects} value={assignment.subjectId} onChange={(v:string)=>setAssignment({...assignment,subjectId:v})}/><Select label="Year" required items={data.years} value={assignment.academicYearId} onChange={(v:string)=>setAssignment({...assignment,academicYearId:v})}/><Select label="Class" required items={data.classes} value={assignment.classId} onChange={(v:string)=>setAssignment({...assignment,classId:v})}/><Select label="Section" items={data.sections.filter((x:any)=>x.class_id===assignment.classId)} value={assignment.sectionId} onChange={(v:string)=>setAssignment({...assignment,sectionId:v})}/><button className="self-end rounded bg-emerald-600 p-2 text-white">Assign</button></form>}<Table heads={['Teacher','Subject','Class','Section','Year']} rows={data.assignments.map((x:any)=>[x.teacher_name,x.subject_name,x.class_name,x.section_name||'All',x.academic_year_name])}/></>}
{tab==='timetable'&&<><form onSubmit={e=>{e.preventDefault();run(()=>api.createTimetable(t,slot),'Timetable entry created.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-5"><Select label="Year" required items={data.years} value={slot.academicYearId} onChange={(v:string)=>setSlot({...slot,academicYearId:v})}/><Select label="Class" required items={data.classes} value={slot.classId} onChange={(v:string)=>setSlot({...slot,classId:v,sectionId:''})}/><Select label="Section" required items={sections} value={slot.sectionId} onChange={(v:string)=>setSlot({...slot,sectionId:v})}/><Select label="Subject" required items={data.subjects} value={slot.subjectId} onChange={(v:string)=>setSlot({...slot,subjectId:v})}/><Select label="Teacher" required items={data.staff.filter((x:any)=>x.teacherProfile)} value={slot.teacherId} onChange={(v:string)=>setSlot({...slot,teacherId:v})}/><Field label="Day (1–7)" type="number" min="1" max="7" value={slot.dayOfWeek} onChange={(e:any)=>setSlot({...slot,dayOfWeek:Number(e.target.value)})}/><Field label="Start" type="time" value={slot.startTime} onChange={(e:any)=>setSlot({...slot,startTime:e.target.value})}/><Field label="End" type="time" value={slot.endTime} onChange={(e:any)=>setSlot({...slot,endTime:e.target.value})}/>{can('timetable.manage')&&<button className="self-end rounded bg-emerald-600 p-2 text-white">Add period</button>}<button type="button" onClick={loadSlots} className="self-end rounded border p-2">Refresh</button></form><Table heads={['Day','Time','Class','Section','Subject','Teacher']} rows={data.timetable.map((x:any)=>[x.day_of_week,`${x.start_time}–${x.end_time}`,x.class_name,x.section_name,x.subject_name,x.teacher_name])}/></>}
{tab==='attendance'&&<><div className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-5"><Select label="Year" required items={data.years} value={scope.academicYearId} onChange={(v:string)=>setScope({...scope,academicYearId:v})}/><Select label="Class" required items={data.classes} value={scope.classId} onChange={(v:string)=>setScope({...scope,classId:v,sectionId:''})}/><Select label="Section" required items={sections} value={scope.sectionId} onChange={(v:string)=>setScope({...scope,sectionId:v})}/><Field label="Date" type="date" value={scope.date} onChange={(e:any)=>setScope({...scope,date:e.target.value})}/><button onClick={loadRoster} className="self-end rounded bg-slate-800 p-2 text-white">Load roster</button></div><div className="rounded-xl border bg-white"><Table heads={['Roll','Student','Status']} rows={data.roster.map((x:any)=>[x.roll_no||'—',`${x.first_name} ${x.last_name}`,<select disabled={!can('attendance.manage')} value={marks[x.enrollment_id]||'PRESENT'} onChange={e=>setMarks({...marks,[x.enrollment_id]:e.target.value})} className="rounded border p-1">{['PRESENT','ABSENT','LATE','EXCUSED','HALF_DAY'].map(v=><option key={v}>{v}</option>)}</select>])}/>{can('attendance.manage')&&data.roster.length>0&&<button onClick={()=>run(()=>api.saveAttendance(t,{...scope,records:data.roster.map((x:any)=>({enrollmentId:x.enrollment_id,status:marks[x.enrollment_id]||'PRESENT'}))}),'Attendance saved.')} className="m-4 rounded bg-emerald-600 px-4 py-2 text-white">Save attendance</button>}</div></>}
</div>};
const Table=({heads,rows}:any)=><div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{heads.map((h:string)=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i} className="border-t">{r.map((v:any,j:number)=><td key={j} className="p-3">{typeof v==='string'||typeof v==='number'?v:v}</td>)}</tr>)}</tbody></table></div>;
