import { loadResources } from '../../services/resourceLoader';
import React,{useEffect,useState}from'react';import{useTenant}from'../../context/TenantContext';import{useAuth}from'../../context/AuthContext';import{feeManagementService as api}from'../../services/feeManagementService';import{masterDataService as master}from'../../services/masterDataService';import{studentLifecycleService}from'../../services/studentLifecycleService';import { ParentFeePortal } from './ParentFeePortal';
type Tab='dues'|'structures'|'assign'|'settings'|'proofs'|'verify'|'receipts'|'reports'|'parentAccess';const Input=({label,...p}:any)=><label className="text-xs font-medium text-slate-600">{label}<input {...p} className="mt-1 w-full rounded border p-2 text-sm"/></label>;const Select=({label,items,value,onChange}:any)=><label className="text-xs font-medium text-slate-600">{label}<select required value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded border p-2 text-sm"><option value="">Select</option>{items.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;const dataUrl=(f:File)=>new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.onerror=no;r.readAsDataURL(f)});
export const FeeManagementModule:React.FC=()=>{const{currentTenant}=useTenant();const{can,currentUser}=useAuth();
if (currentUser?.role === 'PARENT') {
  return <ParentFeePortal />;
}
const t=currentTenant.id;const[tab,setTab]=useState<Tab>('dues');const[d,setD]=useState<any>({settings:null,structures:[],assignments:[],proofs:[],receipts:[],years:[],classes:[],students:[],report:null,parentAccess:[]});const[err,setErr]=useState('');const[msg,setMsg]=useState('');const[structure,setStructure]=useState<any>({name:'',academicYearId:'',classId:'',dueDate:'',status:'ACTIVE',items:'Tuition,0'});const[assign,setAssign]=useState<any>({enrollmentId:'',feeStructureId:'',concessionAmount:0,installments:'Installment 1,,0'});const[settings,setSettings]=useState<any>({payeeName:'',upiId:'',bankName:'',accountLastFour:'',instructions:'',qrDataUrl:null});const[proof,setProof]=useState<any>({feeAssignmentId:'',installmentId:'',amount:0,transactionReference:'',paymentDate:new Date().toISOString().slice(0,10),fileName:'',proofDataUrl:''});
const load=async()=>{
 setErr('');
 const resources:Record<string,()=>Promise<any>>={assignments:()=>api.assignments(t),settings:()=>api.settings(t)};
 if(can('fee_management.view')) {resources.proofs=()=>api.proofs(t);resources.structures=()=>api.structures(t);}
 if(can('fee_receipts.view')) resources.receipts=()=>api.receipts(t);
 if(can('master_data.view')) {resources.years=()=>master.listYears(t);resources.classes=()=>master.listClasses(t);}
 if(can('student_lifecycle.view')&&can('fee_management.manage')) resources.students=()=>studentLifecycleService.list(t,{pageSize:100});
 const result=await loadResources(resources);setD((v:any)=>({...v,...result.data}));
 const errors=Object.entries(result.errors).map(([key,message])=>key+': '+message);
 const settings:any=result.data.settings;
 if(settings){setSettings({payeeName:settings.payee_name,upiId:settings.upi_id,bankName:settings.bank_name||'',accountLastFour:settings.account_last_four||'',instructions:settings.instructions||'',qrDataUrl:null});if(settings.has_qr){try{const qrUrl=URL.createObjectURL(await api.qr(t));setD((v:any)=>({...v,qrUrl}));}catch(e:any){errors.push('School QR: '+e.message);}}}
 setErr(errors.join(' · '));
};useEffect(()=>{load()},[t]);const run=async(fn:()=>Promise<any>,m:string)=>{setErr('');try{const r=await fn();setMsg(m);await load();if(tab==='parentAccess'){const pa=await api.parentAccess(t);setD((v:any)=>({...v,parentAccess:pa.data}))}return r}catch(e:any){setErr(e.message)}};const allowed=(x:Tab)=>x==='structures'?can('fee_management.manage'):x==='assign'?can('fee_management.manage')&&can('master_data.view')&&can('student_lifecycle.view'):x==='settings'?can('payment_settings.manage'):x==='proofs'?can('payment_proofs.submit'):x==='verify'?can('payment_proofs.verify'):x==='reports'?can('fee_reports.view'):x==='parentAccess'?can('parent_accounts.view'):x==='receipts'?can('fee_receipts.view'):can('fee_management.view');
const assignment=d.assignments.find((x:any)=>x.id===proof.feeAssignmentId);return <div className="space-y-5"><div><h2 className="text-2xl font-bold">Fee Management</h2><p className="text-sm text-slate-500">Manual QR/UPI proof verification and enrollment-linked fee accounting.</p></div>{err&&<div className="rounded border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{err}</div>}{msg&&<div className="break-all rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{msg}</div>}<div className="flex flex-wrap gap-2">{(['dues','structures','assign','settings','proofs','verify','receipts','reports','parentAccess']as Tab[]).filter(allowed).map(x=><button key={x} onClick={async()=>{setTab(x);if(x==='reports'){const r=await api.report(t);setD((v:any)=>({...v,report:r.data}))}if(x==='parentAccess'){const pa=await api.parentAccess(t);setD((v:any)=>({...v,parentAccess:pa.data}))}}} className={`rounded px-3 py-2 text-sm font-semibold ${tab===x?'bg-violet-600 text-white':'border bg-white'}`}>{x}</button>)}</div>
{tab==='dues'&&<Table heads={['Student','Admission','Fee','Year','Total','Paid','Outstanding','Installments']} rows={d.assignments.map((x:any)=>[`${x.first_name} ${x.last_name}`,x.admission_no,x.structure_name,x.academic_year_name,money(x.total_amount),money(x.verified_paid),money(x.outstanding),(x.installments||[]).map((i:any)=>`${i.name}: ${money(i.amount)} due ${date(i.dueDate)}`).join(' · ')])}/>} 
{tab==='structures'&&<>{!can('master_data.view')&&<p role="status">Fee structures are visible. Creation requires school master-data access.</p>}{can('master_data.view')&&<form onSubmit={e=>{e.preventDefault();const items=structure.items.split('\n').map((l:string)=>{const[n,a]=l.split(',');return{name:n.trim(),amount:Number(a)}});run(()=>api.createStructure(t,{...structure,items,dueDate:structure.dueDate||null}),'Fee structure created.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><Input label="Name" required value={structure.name} onChange={(e:any)=>setStructure({...structure,name:e.target.value})}/><Select label="Academic year" items={d.years} value={structure.academicYearId} onChange={(v:string)=>setStructure({...structure,academicYearId:v})}/><Select label="Class" items={d.classes.filter((x:any)=>x.academic_year_id===structure.academicYearId)} value={structure.classId} onChange={(v:string)=>setStructure({...structure,classId:v})}/><Input label="Default due date" type="date" value={structure.dueDate} onChange={(e:any)=>setStructure({...structure,dueDate:e.target.value})}/><label className="text-xs md:col-span-4">Fee items: one name,amount per line<textarea rows={5} value={structure.items} onChange={e=>setStructure({...structure,items:e.target.value})} className="mt-1 w-full rounded border p-2 font-mono"/></label><button className="rounded bg-violet-600 p-2 text-white md:col-span-4">Create structure</button></form>}<Table heads={['Name','Year','Class','Total','Items']} rows={d.structures.map((x:any)=>[x.name,x.academic_year_name,x.class_name,money(x.total_amount),x.items.map((i:any)=>`${i.name}: ${money(i.amount)}`).join(', ')])}/></>}
{tab==='assign'&&<><form onSubmit={e=>{e.preventDefault();const installments=assign.installments.split('\n').map((l:string)=>{const[n,due,a]=l.split(',');return{name:n.trim(),dueDate:due,amount:Number(a)}});run(()=>api.createAssignment(t,{...assign,installments}),'Fee assigned to enrollment.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-3"><label className="text-xs">Student enrollment<select required value={assign.enrollmentId} onChange={e=>setAssign({...assign,enrollmentId:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Select</option>{d.students.filter((x:any)=>x.enrollment_id).map((x:any)=><option key={x.enrollment_id} value={x.enrollment_id}>{x.first_name} {x.last_name} — {x.class_name}</option>)}</select></label><Select label="Fee structure" items={d.structures} value={assign.feeStructureId} onChange={(v:string)=>setAssign({...assign,feeStructureId:v})}/><Input label="Concession" type="number" min="0" value={assign.concessionAmount} onChange={(e:any)=>setAssign({...assign,concessionAmount:Number(e.target.value)})}/><label className="text-xs md:col-span-3">Installments: name,due date,amount<textarea rows={5} value={assign.installments} onChange={e=>setAssign({...assign,installments:e.target.value})} className="mt-1 w-full rounded border p-2 font-mono"/></label><button className="rounded bg-violet-600 p-2 text-white md:col-span-3">Assign fee</button></form></>}
{tab==='settings'&&<form onSubmit={e=>{e.preventDefault();run(()=>api.saveSettings(t,{...settings,accountLastFour:settings.accountLastFour||null}),'School payment settings saved.')}} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-2"><Input label="Payee name" required value={settings.payeeName} onChange={(e:any)=>setSettings({...settings,payeeName:e.target.value})}/><Input label="UPI ID" required value={settings.upiId} onChange={(e:any)=>setSettings({...settings,upiId:e.target.value})}/><Input label="Bank name" value={settings.bankName} onChange={(e:any)=>setSettings({...settings,bankName:e.target.value})}/><Input label="Account last four" maxLength={4} value={settings.accountLastFour} onChange={(e:any)=>setSettings({...settings,accountLastFour:e.target.value})}/><Input label="Instructions" value={settings.instructions} onChange={(e:any)=>setSettings({...settings,instructions:e.target.value})}/><label className="text-xs">QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(f)setSettings({...settings,qrDataUrl:await dataUrl(f)})}} className="mt-1 block"/></label><button className="rounded bg-violet-600 p-2 text-white md:col-span-2">Save payment settings</button></form>}
{tab==='proofs'&&<div className="grid gap-5 lg:grid-cols-2"><div className="rounded-xl border bg-white p-5"><h3 className="font-bold">Pay school manually</h3>{d.settings?<><p className="mt-2 text-sm">Payee: {d.settings.payee_name}</p><p className="text-lg font-bold">UPI: {d.settings.upi_id}</p>{d.settings.has_qr&&<img alt="School payment QR" src={d.qrUrl} className="mt-3 max-h-64 rounded border"/>}<p className="mt-2 text-xs text-slate-500">{d.settings.instructions}</p></>:<p className="text-sm text-amber-700">School payment settings are not configured.</p>}</div><form onSubmit={e=>{e.preventDefault();run(()=>api.submitProof(t,{...proof,installmentId:proof.installmentId||null}),'Payment proof submitted for administrator review.')}} className="grid gap-3 rounded-xl border bg-white p-4"><label className="text-xs">Fee due<select required value={proof.feeAssignmentId} onChange={e=>setProof({...proof,feeAssignmentId:e.target.value,installmentId:''})} className="mt-1 w-full rounded border p-2"><option value="">Select</option>{d.assignments.filter((x:any)=>Number(x.outstanding)>0).map((x:any)=><option key={x.id} value={x.id}>{x.first_name} {x.last_name} — {x.structure_name} — {money(x.outstanding)}</option>)}</select></label>{assignment&&<label className="text-xs">Installment<select value={proof.installmentId} onChange={e=>setProof({...proof,installmentId:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">General payment</option>{assignment.installments.map((x:any)=><option key={x.id} value={x.id}>{x.name} — {money(x.amount)}</option>)}</select></label>}<Input label="Amount paid" type="number" min="0.01" step="0.01" value={proof.amount} onChange={(e:any)=>setProof({...proof,amount:Number(e.target.value)})}/><Input label="UPI transaction reference" required value={proof.transactionReference} onChange={(e:any)=>setProof({...proof,transactionReference:e.target.value})}/><Input label="Payment date" type="date" value={proof.paymentDate} onChange={(e:any)=>setProof({...proof,paymentDate:e.target.value})}/><label className="text-xs">Screenshot or PDF<input required type="file" accept="image/png,image/jpeg,image/webp,application/pdf" onChange={async e=>{const f=e.target.files?.[0];if(f)setProof({...proof,fileName:f.name,proofDataUrl:await dataUrl(f)})}} className="mt-1 block"/></label><button className="rounded bg-violet-600 p-2 text-white">Upload payment proof</button></form></div>}
{tab==='verify'&&<Table heads={['Student','Reference','Amount','Date','Proof','Decision']} rows={d.proofs.filter((x:any)=>x.status==='PENDING').map((x:any)=>[`${x.first_name} ${x.last_name}`,x.transaction_reference,money(x.amount),date(x.payment_date),<button onClick={async()=>{const blob=await api.proofFile(t,x.id);window.open(URL.createObjectURL(blob),'_blank')}} className="text-violet-700 underline">View</button>,<span className="flex gap-2"><button onClick={()=>run(()=>api.verifyProof(t,x.id,{decision:'APPROVED',notes:'Verified against submitted transaction proof.'}),'Payment approved and receipt generated.')} className="text-emerald-700 underline">Approve</button><button onClick={()=>{const notes=prompt('Rejection reason');if(notes)run(()=>api.verifyProof(t,x.id,{decision:'REJECTED',notes}),'Payment proof rejected.')}} className="text-rose-700 underline">Reject</button></span>])}/>} 
{tab==='receipts'&&<Table heads={['Receipt','Student','Fee','Amount','Reference','Paid']} rows={d.receipts.map((x:any)=>[x.receipt_no,`${x.first_name} ${x.last_name}`,x.structure_name,money(x.amount),x.reference_number,date(x.paid_at)])}/>} 
{tab==='reports'&&d.report&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-4">{[['Assigned',d.report.summary.assigned],['Collected',d.report.summary.collected],['Outstanding',d.report.summary.outstanding],['Overdue accounts',d.report.summary.overdue]].map(([k,v])=><div key={String(k)} className="rounded-xl border bg-white p-4"><p className="text-xs text-slate-500">{k}</p><p className="text-xl font-bold">{k==='Overdue accounts'?v:money(v)}</p></div>)}</div><Table heads={['Month','Collected']} rows={d.report.monthly.map((x:any)=>[x.month,money(x.collected)])}/></div>}
{tab==='parentAccess'&&<Table heads={['Parent Name','Email','Phone','Students Linked','Account Status','Action']} rows={(d.parentAccess||[]).map((x:any)=>[`${x.first_name} ${x.last_name}`,x.email,x.phone,x.children.map((c:any)=>`${c.name} (${c.admissionNo})`).join(', ')||'None',x.user_id?'Linked':x.pending_invitation_id?'Invitation Sent':'Unlinked',!x.user_id&&<button onClick={()=>{const em=prompt('Enter email to invite parent:',x.email||'');if(em)run(()=>api.inviteParent(t,x.id,em),'Invitation sent to parent.')}} className="text-violet-700 underline">Invite Parent</button>])}/>}
</div>};const money=(v:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0));const date=(v:any)=>{if(!v)return '—';const str=String(v);if(str.includes('T')){const d=new Date(str);if(!isNaN(d.getTime())){const y=d.getFullYear();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}}return str.slice(0,10);};const Table=({heads,rows}:any)=><div className="my-4 overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{heads.map((h:string)=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i} className="border-t">{r.map((v:any,j:number)=><td key={j} className="p-3">{v}</td>)}</tr>)}</tbody></table></div>;
