import test,{after}from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{pool,query}from'../src/db.ts';import{enqueueNotification}from'../src/services/notificationService.ts';import{processNotificationJobs}from'../src/services/notificationWorker.ts';
const ready=await pool.query(`SELECT to_regclass('public.notification_jobs') ready`).then(r=>Boolean(r.rows[0].ready)).catch(()=>false);
test('Phase 10 PostgreSQL outbox integration',{skip:!ready},async()=>{const tenantId=randomUUID(),userId=randomUUID(),otherTenant=randomUUID(),otherUser=randomUUID(),sent=[];const provider={send:async message=>{sent.push(message.to);return{messageId:randomUUID(),provider:'TEST'};}};try{await query(`INSERT INTO tenants(id,name,slug,tenant_type,status) VALUES($1,'Phase 10 School',$2,'school','active'),($3,'Other School',$4,'school','active')`,[tenantId,`p10-${tenantId}`,otherTenant,`p10-${otherTenant}`]);for(const[id,email]of[[userId,`parent-${userId}@example.test`],[otherUser,`other-${otherUser}@example.test`]]){await query(`INSERT INTO users(id,email,password_hash,status) VALUES($1,$2,'hash','ACTIVE')`,[id,email]);await query(`INSERT INTO profiles(id,display_name,status) VALUES($1,'Test User','active')`,[id]);}const role=(await query(`SELECT id FROM roles WHERE key='PARENT' AND tenant_id IS NULL LIMIT 1`)).rows[0];await query(`INSERT INTO memberships(tenant_id,user_id,role_id,status) VALUES($1,$2,$3,'active'),($4,$5,$3,'active')`,[tenantId,userId,role.id,otherTenant,otherUser]);
const event={tenantId,eventType:'FEE_PROOF_APPROVED',templateCode:'FEE_PROOF_APPROVED',sourceType:'TEST',sourceId:randomUUID(),payload:{student_name:'Student',amount:'100',receipt_number:'R-1'}};await enqueueNotification(event,[{userId}]);await enqueueNotification(event,[{userId}]);assert.equal(Number((await query(`SELECT COUNT(*) count FROM notifications WHERE tenant_id=$1 AND source_id=$2`,[tenantId,event.sourceId])).rows[0].count),1);assert.equal(Number((await query(`SELECT COUNT(*) count FROM notification_jobs j JOIN notifications n ON n.id=j.notification_id WHERE n.tenant_id=$1 AND n.source_id=$2`,[tenantId,event.sourceId])).rows[0].count),2);
await assert.rejects(()=>enqueueNotification({...event,sourceId:randomUUID()},[{userId:otherUser}]),/not an active tenant member/);
await Promise.all([processNotificationJobs({provider,workerId:'test-a'}),processNotificationJobs({provider,workerId:'test-b'})]);assert.equal(sent.filter(x=>x.includes(userId)).length,1);const states=await query(`SELECT channel,status FROM notification_jobs j JOIN notifications n ON n.id=j.notification_id WHERE n.tenant_id=$1 AND n.source_id=$2`,[tenantId,event.sourceId]);assert.ok(states.rows.every(x=>x.status==='SENT'));
await query(`INSERT INTO notification_preferences(tenant_id,user_id,event_type,channel,is_enabled) VALUES($1,$2,'FEE_DUE_REMINDER','EMAIL',false)`,[tenantId,userId]);const optional={tenantId,eventType:'FEE_DUE_REMINDER',templateCode:'FEE_DUE_REMINDER',sourceType:'TEST',sourceId:randomUUID(),payload:{student_name:'Student',amount:'50',due_date:'2026-10-03',status_label:'Due'}};await enqueueNotification(optional,[{userId}]);const optionalJobs=await query(`SELECT channel,status FROM notification_jobs j JOIN notifications n ON n.id=j.notification_id WHERE n.source_id=$1`,[optional.sourceId]);assert.equal(optionalJobs.rows.find(x=>x.channel==='EMAIL').status,'SKIPPED');
await query(`INSERT INTO notification_preferences(tenant_id,user_id,event_type,channel,is_enabled) VALUES($1,$2,'ATTENDANCE_ABSENT','EMAIL',false) ON CONFLICT(tenant_id,user_id,event_type,channel) DO UPDATE SET is_enabled=false`,[tenantId,userId]);const mandatory={tenantId,eventType:'ATTENDANCE_ABSENT',templateCode:'ATTENDANCE_ABSENT',sourceType:'TEST',sourceId:randomUUID(),payload:{student_name:'Student',date:'2026-10-03'}};await enqueueNotification(mandatory,[{userId}]);const mandatoryEmail=await query(`SELECT j.status FROM notification_jobs j JOIN notifications n ON n.id=j.notification_id WHERE n.source_id=$1 AND j.channel='EMAIL'`,[mandatory.sourceId]);assert.equal(mandatoryEmail.rows[0].status,'QUEUED');
await processNotificationJobs({provider,workerId:'test-drain'});const retryEvent={...event,sourceId:randomUUID(),payload:{student_name:'Retry Student',amount:'25',receipt_number:'R-RETRY'}};await enqueueNotification(retryEvent,[{userId}]);const failingProvider={send:async()=>{const error=new Error('temporary provider outage');error.transient=true;throw error;}};for(let attempt=1;attempt<=4;attempt++){await processNotificationJobs({provider:failingProvider,workerId:`test-retry-${attempt}`});const emailJob=(await query(`SELECT j.id,j.status,j.attempts FROM notification_jobs j JOIN notifications n ON n.id=j.notification_id WHERE n.source_id=$1 AND j.channel='EMAIL'`,[retryEvent.sourceId])).rows[0];assert.equal(Number(emailJob.attempts),attempt);assert.equal(emailJob.status,attempt===4?'FAILED':'QUEUED');if(attempt<4)await query(`UPDATE notification_jobs SET next_attempt_at=NOW() WHERE id=$1`,[emailJob.id]);}
}finally{await query('DELETE FROM tenants WHERE id=ANY($1::uuid[])',[ [tenantId,otherTenant] ]).catch(()=>{});await query('DELETE FROM users WHERE id=ANY($1::uuid[])',[ [userId,otherUser] ]).catch(()=>{});}});
after(()=>pool.end());
