import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath}from'node:url';
import{escapeTemplateValue,renderTemplate}from'../src/services/notificationService.ts';
import{retryDelayMinutes}from'../src/services/notificationWorker.ts';
import{LogEmailProvider}from'../src/services/emailProvider.ts';
import{pool}from'../src/db.ts';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const migration=read('sql/migrations/native_0014_communications.sql');
const notifications=read('src/routes/notifications.ts');
const communication=read('src/routes/communication.ts');
const attendance=read('src/routes/attendanceOperations.ts');
const fees=read('src/services/feePaymentService.ts');
const exams=read('src/routes/examinationOperations.ts');
const teacher=read('src/routes/academicOperations.ts');
const parent=read('src/routes/feeManagement.ts');
const owner=read('src/routes/tenants.ts');
const worker=read('src/services/notificationWorker.ts');

test('1 in-app notification model targets an ERP user',()=>assert.match(migration,/notification_recipients[\s\S]*user_id UUID/));
test('2 own inbox derives user from authentication context',()=>{assert.match(notifications,/nr\.user_id=\$2/);assert.match(notifications,/req\.user\.id/);});
test('3 tenant isolation is present on every own-inbox mutation',()=>assert.ok((notifications.match(/req\.tenantId/g)||[]).length>=6));
test('4 mark-read is scoped to tenant and current user',()=>assert.match(notifications,/n\.id=\$1 AND nr\.tenant_id=\$2 AND nr\.user_id=\$3/));
test('5 owner invitation queues through the central outbox',()=>assert.match(owner,/eventType: 'OWNER_INVITATION'/));
test('6 logical business events have a database uniqueness key',()=>assert.match(migration,/uq_notifications_business_event/));
test('7 teacher invitation reuses user_invitations',()=>{assert.match(teacher,/INSERT INTO user_invitations/);assert.match(teacher,/TEACHER_INVITATION/);});
test('8 parent invitation reuses Phase 7.1 parent_id',()=>{assert.match(parent,/parent_id\) VALUES/);assert.match(parent,/PARENT_INVITATION/);});
test('9 absence resolves recipients through parent account links',()=>{assert.match(attendance,/resolveParentRecipients/);assert.doesNotMatch(attendance,/parent_id \}\)/);});
test('10 attendance API has no recipient input field',()=>assert.doesNotMatch(attendance,/recipientEmail|recipientId/));
test('11 repeated attendance saves use attendance record idempotency',()=>assert.match(attendance,/sourceType:'ATTENDANCE_RECORD',sourceId:r\.rows\[0\]\.id/));
test('12 fee approval and outbox share one transaction client',()=>assert.match(fees,/FEE_PROOF_APPROVED[\s\S]*recipients,c\)/));
test('13 rejected proof has a separate event',()=>assert.match(fees,/eventType:'FEE_PROOF_REJECTED'/));
test('14 pending proof does not enqueue approval',()=>assert.match(fees,/proof\.status!=='PENDING'/));
test('15 exam event is created only in publish endpoint',()=>assert.equal((exams.match(/eventType:'EXAM_RESULT_PUBLISHED'/g)||[]).length,1));
test('16 template rendering escapes unsafe values',()=>{assert.equal(escapeTemplateValue('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.equal(renderTemplate('Hi {{name}}',{name:'<b>A</b>'}),'Hi &lt;b&gt;A&lt;/b&gt;');assert.throws(()=>renderTemplate('{{missing}}',{}),/Missing template variables/);});
test('17 retry delays increase deterministically',()=>assert.deepEqual([1,2,3,4].map(retryDelayMinutes),[1,5,30,120]));
test('18 worker stops after maximum attempts',()=>assert.match(worker,/attempt>=Number\(job\.max_attempts\)/));
test('19 workers claim with skip-locked and commit before send',()=>{assert.match(worker,/FOR UPDATE SKIP LOCKED/);assert.match(worker,/const job=await loadJob/);});
test('20 optional preferences create skipped jobs',()=>{assert.match(migration,/OPTIONAL/);assert.match(read('src/services/notificationService.ts'),/skipped\?'SKIPPED':'QUEUED'/);});
test('21 transactional and security opt-outs are rejected',()=>assert.match(notifications,/MANDATORY_NOTIFICATION/));
test('22 parent lacks communication admin role grant',()=>assert.doesNotMatch(migration,/r\.key='PARENT'.*communications\.view/s));
test('23 teacher lacks template management grant',()=>assert.doesNotMatch(migration,/TEACHER[^\n]+communications\.templates\.manage/));
test('24 delivery worker never logs email bodies',()=>{assert.doesNotMatch(worker,/console\.(log|error)\([^\n]*(html|text|payload)/);assert.match(worker,/notification_job_sent/);});
test('safe LOG provider does not expose body or recipient local-part',async()=>{let line='';const original=console.log;console.log=x=>{line=String(x);};try{await new LogEmailProvider().send({to:'secret.parent@example.com',subject:'token abc',html:'private body',text:'private body'});}finally{console.log=original;}assert.doesNotMatch(line,/secret\.parent|private body|token abc/);assert.match(line,/example\.com/);});
test('admin APIs require communication permissions',()=>{assert.match(communication,/communications\.templates\.manage/);assert.match(communication,/communications\.delivery\.view/);assert.match(communication,/communications\.send/);});
test.after(()=>pool.end());
