import test,{after}from'node:test';import assert from'node:assert/strict';import{fixture,pool}from'./operations-fixture.mjs';let f;
test('Phase 11E hostel and mess PostgreSQL workflows',async t=>{f=await fixture('hostel');const{request:r,admin,teacher,foreignAdmin}=f;const student=await f.student(),enrollment=await f.enrollment(f.tenant,student),second=await f.enrollment(),sameStudentNextYear=await f.enrollment(f.tenant,student),foreignEnrollment=await f.enrollment(f.otherTenant);let building,bed,secondBed,allocation;
 await t.test('buildings rooms and physical beds are tenant-safe and permission protected',async()=>{assert.equal((await r(teacher,'/buildings','POST',{name:'Unsafe'})).status,403);building=(await r(admin,'/buildings','POST',{name:'North hostel'})).data.id;assert.equal((await r(foreignAdmin,'/rooms','POST',{buildingId:building,roomNumber:'101',capacity:2})).status,422);assert.equal((await r(admin,'/rooms','POST',{buildingId:building,roomNumber:'101',capacity:2})).status,201);const beds=(await r(admin,'')).data.beds;assert.equal(beds.length,2);bed=beds[0].id;secondBed=beds[1].id;});
 await t.test('cross-tenant enrollment allocation rejected',async()=>{assert.equal((await r(admin,'/allocations','POST',{bedId:bed,enrollmentId:foreignEnrollment})).status,422);assert.equal((await r(foreignAdmin,'/allocations','POST',{bedId:bed,enrollmentId:foreignEnrollment})).status,422);});
 await t.test('concurrent bed allocation succeeds exactly once',async()=>{const x=await Promise.all([r(admin,'/allocations','POST',{bedId:bed,enrollmentId:enrollment}),r(admin,'/allocations','POST',{bedId:bed,enrollmentId:second})]);assert.deepEqual(x.map(a=>a.status).sort(),[201,409]);allocation=x.find(a=>a.status===201).data;assert.equal((await r(admin,'')).data.rooms[0].occupied,1);assert.equal((await r(admin,`/buildings/${building}`,'PATCH',{status:'ARCHIVED'})).status,409);});
 await t.test('same student cannot occupy a second bed even through another enrollment',async()=>{const another=allocation.enrollment_id===enrollment?sameStudentNextYear:second;assert.equal((await r(admin,'/allocations','POST',{bedId:secondBed,enrollmentId:another})).status,409);});
 await t.test('checkout releases bed atomically and preserves history',async()=>{assert.equal((await r(admin,`/allocations/${allocation.id}/checkout`,'POST')).status,200);assert.equal((await r(admin,`/allocations/${allocation.id}/checkout`,'POST')).status,409);assert.equal((await r(admin,'')).data.rooms[0].available,2);assert.equal((await r(admin,'/allocations','POST',{bedId:bed,enrollmentId:enrollment})).status,201);await assert.rejects(()=>pool.query('UPDATE hostel_allocations SET tenant_id=$2 WHERE id=$1',[allocation.id,f.otherTenant]),e=>e.code==='23503');});
 await t.test('hostel allocation and checkout have durable audit',async()=>{assert.equal((await pool.query(`SELECT COUNT(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action='HOSTEL_BED_ALLOCATED'`,[f.tenant])).rows[0].n,2);assert.equal((await pool.query(`SELECT COUNT(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action='HOSTEL_CHECKOUT'`,[f.tenant])).rows[0].n,1);});
 // Reuse the same authenticated HTTP fixture; module changes only the endpoint path.
 const mess=(user,path='',method='GET',body)=>r(user,`/../mess${path}`,method,body);let plan,member;
 await t.test('mess plans and menus are permission protected and save weekly menu',async()=>{assert.equal((await mess(teacher,'/plans','POST',{name:'Unsafe'})).status,403);const p=await mess(admin,'/plans','POST',{name:'Standard meals',description:'Three meals'});assert.equal(p.status,201);plan=p.data.id;assert.equal((await mess(admin,'/menus','POST',{planId:plan,dayOfWeek:'MONDAY',mealType:'LUNCH',menuItems:'Rice and vegetables'})).status,201);assert.equal((await mess(admin,'/menus','POST',{planId:plan,dayOfWeek:'MONDAY',mealType:'LUNCH',menuItems:'Rice and lentils'})).status,201);assert.equal((await mess(admin,'')).data.menus.length,1);assert.equal((await mess(admin,'')).data.menus[0].menu_items,'Rice and lentils');});
 await t.test('mess membership supports existing students and staff only within tenant',async()=>{const st=await f.staff(),foreign=await f.student(f.otherTenant);assert.equal((await mess(admin,'/assignments','POST',{planId:plan,memberType:'STUDENT',memberId:foreign})).status,422);const x=await mess(admin,'/assignments','POST',{planId:plan,memberType:'STUDENT',memberId:student});assert.equal(x.status,201);member=x.data.id;assert.equal((await mess(admin,'/assignments','POST',{planId:plan,memberType:'STUDENT',memberId:student})).status,409);assert.equal((await mess(admin,'/assignments','POST',{planId:plan,memberType:'STAFF',memberId:st})).status,201);assert.equal((await mess(foreignAdmin,'')).data.assignments.length,0);assert.equal((await mess(admin,`/plans/${plan}`,'PATCH',{status:'ARCHIVED'})).status,409);assert.equal((await mess(admin,`/assignments/${member}/end`,'POST')).status,200);});
});after(async()=>{if(f)await f.close();else await pool.end();});
