import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
let f,pool,server,base,accounts,cash;
const call=async(user,route,method='GET',body,headers={})=>{const r=await fetch(base+'/api/v1'+route,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${user.token}`,...headers},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,...await r.json()};};
before(async()=>{assert.match(new URL(process.env.DATABASE_URL).pathname,/_test$/);({pool}=await import('../src/db.ts'));
 if(process.env.BATCH3_API_URL){base=process.env.BATCH3_API_URL;f=JSON.parse(fs.readFileSync(path.join(process.env.BATCH3_ARTIFACT_DIR,'batch3-api-fixtures.json')));for(const account of Object.values(f.accounts)){const login=await call(account,'/auth/signin','POST',{email:account.email,password:f.password});assert.equal(login.status,200);account.token=login.data.token;}
}else{const{default:app}=await import('../src/server.ts');server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`;const dir=fs.mkdtempSync(path.join(os.tmpdir(),'edunexus-b3-'));process.env.BATCH3_ARTIFACT_DIR=dir;process.env.BATCH3_STATE=process.env.BATCH1_STATE;process.env.BATCH3_FIXTURE_API_URL=base+'/api/v1';await import('../../qa/batch3-fixtures.mjs');f=JSON.parse(fs.readFileSync(path.join(dir,'batch3-api-fixtures.json')));}
 accounts=(await call(f.accounts.owner,'/finance/accounts')).data;cash=(await call(f.accounts.owner,'/finance/cash-bank-accounts')).data;
});after(async()=>{if(server)await new Promise(r=>server.close(r));await pool?.end();});
const owner=()=>f.accounts.owner,acct=()=>f.accounts.accountant;const amount=25;
test('BUG-004 authorized owner finance accounts load',async()=>{const r=await call(owner(),'/finance/accounts');assert.equal(r.status,200);assert.ok(r.data.some(a=>a.account_type==='EXPENSE'));});
test('BUG-004 cross-tenant finance account header denied',async()=>assert.equal((await call(owner(),'/finance/accounts','GET',null,{'x-tenant-id':f.accounts.foreign.tenantId})).status,403));
test('BUG-004 expense posts balanced journal through API',async()=>{const r=await call(owner(),'/finance/expenses','POST',{title:'Batch3 regression expense',account_id:accounts.find(a=>a.account_type==='EXPENSE').id,payment_account_id:cash[0].id,amount,date:'2026-10-05'});assert.equal(r.status,201);assert.equal(r.data.date,'2026-10-05');const lines=(await pool.query('SELECT l.*,a.account_type FROM journal_lines l JOIN finance_accounts a ON a.id=l.account_id JOIN journal_entries j ON j.id=l.journal_entry_id WHERE j.source_id=$1',[r.data.id])).rows;assert.equal(lines.length,2);assert.equal(Number(lines.find(l=>l.account_type==='EXPENSE').debit),amount);assert.equal(Number(lines.find(l=>l.account_type==='ASSET').credit),amount);});
test('BUG-004 other income posts balanced journal through API',async()=>{const r=await call(owner(),'/finance/other-income','POST',{title:'Batch3 regression income',account_id:accounts.find(a=>a.code==='INC-OTH').id,payment_account_id:cash[0].id,amount:40,date:'2026-10-05'});assert.equal(r.status,201);const lines=(await pool.query('SELECT l.*,a.account_type FROM journal_lines l JOIN finance_accounts a ON a.id=l.account_id JOIN journal_entries j ON j.id=l.journal_entry_id WHERE j.source_id=$1',[r.data.id])).rows;assert.equal(Number(lines.find(l=>l.account_type==='ASSET').debit),40);assert.equal(Number(lines.find(l=>l.account_type==='INCOME').credit),40);});
test('BUG-004 verified fee journal is visible and reconciliation idempotent',async()=>{for(let i=0;i<2;i++)assert.equal((await call(owner(),'/finance/reconcile/fee-payments','POST',{})).status,200);const rows=(await pool.query("SELECT j.source_id,COUNT(*)::int n FROM journal_entries j WHERE tenant_id=$1 AND source_type='STUDENT_FEE_PAYMENT' GROUP BY source_id",[owner().tenantId])).rows;assert.equal(rows.length,1);assert.equal(rows[0].n,1);});
test('BUG-004 posted journals balance in PostgreSQL',async()=>{const r=await pool.query("SELECT j.id FROM journal_entries j JOIN journal_lines l ON l.journal_entry_id=j.id WHERE j.tenant_id=$1 AND j.status='POSTED' GROUP BY j.id HAVING SUM(l.debit)<>SUM(l.credit)",[owner().tenantId]);assert.equal(r.rowCount,0);});
test('BUG-004 ledger matches journal line aggregation',async()=>{const r=await call(owner(),'/finance/reports/ledger');assert.equal(r.status,200);for(const a of r.data){const sum=(await pool.query('SELECT COALESCE(SUM(debit),0) debit,COALESCE(SUM(credit),0) credit FROM journal_lines WHERE tenant_id=$1 AND account_id=$2',[owner().tenantId,a.id])).rows[0];assert.equal(a.total_debit,Number(sum.debit));assert.equal(a.total_credit,Number(sum.credit));}});
test('BUG-004 SaaS events absent from school journals',async()=>{const r=await pool.query("SELECT id FROM journal_entries WHERE tenant_id=$1 AND source_type NOT IN ('STUDENT_FEE_PAYMENT','EXPENSE','OTHER_INCOME')",[owner().tenantId]);assert.equal(r.rowCount,0);});
for(const route of ['/fees/assignments','/fees/proofs','/fees/receipts','/fees/reports/summary','/finance/accounts','/finance/reports/ledger','/communication/overview'])test('BUG-008 Accountant authorized resource '+route,async()=>assert.equal((await call(acct(),route)).status,200));
test('BUG-008 Accountant has no student/master/HR admin dependency',async()=>{for(const route of ['/students','/master-data/academic-years','/hr/dashboard'])assert.equal((await call(acct(),route)).status,403);});
for(const key of ['teacher','parent','student','custom'])test('BUG-007 '+key+' denied internal finance',async()=>assert.equal((await call(f.accounts[key],'/finance/accounts')).status,403));
test('BUG-007 custom ADMIN receives only its actual grants',async()=>{const r=await call(f.accounts.custom,'/auth/me');assert.equal(r.status,200);assert.deepEqual(r.data.user.permissions,['master_data.view']);assert.equal((await call(f.accounts.custom,'/master-data/classes')).status,200);assert.equal((await call(f.accounts.custom,'/master-data/classes','POST',{name:'Forbidden'})).status,403);});
test('BUG-007 teacher communications remain denied',async()=>assert.equal((await call(f.accounts.teacher,'/communication/overview')).status,403));
test('BUG-019 exact Staff attendance/assignments denial stays authoritative',async()=>{assert.equal((await call(f.accounts.staff,'/staff/assignments')).status,403);assert.equal((await call(f.accounts.staff,'/attendance/roster')).status,403);const me=await call(f.accounts.staff,'/auth/me');assert.ok(!me.data.user.permissions.includes('attendance.view'));});
test('BUG-004 foreign finance references rejected without expense/income records',async()=>{const other=(await call(f.accounts.foreign,'/finance/accounts')).data,otherCash=(await call(f.accounts.foreign,'/finance/cash-bank-accounts')).data;for(const [route,type] of [['expenses','EXPENSE'],['other-income','INCOME']]){const r=await call(owner(),'/finance/'+route,'POST',{title:'Forbidden foreign reference',account_id:other.find(a=>a.account_type===type).id,payment_account_id:otherCash[0].id,amount:10,date:'2026-10-05'});assert.equal(r.status,422);}assert.equal((await pool.query("SELECT id FROM expenses WHERE tenant_id=$1 AND title='Forbidden foreign reference'",[owner().tenantId])).rowCount,0);});

test('BUG-008 Accountant reminder uses existing database communications.send grant',async()=>{const r=await call(acct(),'/communication/fee-reminders','POST',{feeAssignmentId:f.assignment.id});assert.equal(r.status,200);assert.equal((await call(f.accounts.teacher,'/communication/fee-reminders','POST',{feeAssignmentId:f.assignment.id})).status,403);});

test('BUG-004 finance lists preserve calendar dates without ambiguous ordering',async()=>{for(const route of ['/finance/expenses','/finance/other-income']){const r=await call(owner(),route);assert.equal(r.status,200);assert.ok(r.data.length>0);assert.ok(r.data.every(row=>row.date==='2026-10-05'));}});
