import test,{after}from'node:test';import assert from'node:assert/strict';import{fixture,pool}from'./operations-fixture.mjs';let f;
test('Phase 11D transport PostgreSQL workflow',async t=>{f=await fixture('transport');const{request:r,admin,teacher,foreignAdmin}=f;const driver=await f.staff(),foreignDriver=await f.staff(f.otherTenant),enrollment=await f.enrollment(),second=await f.enrollment(),foreignEnrollment=await f.enrollment(f.otherTenant);let vehicle,route,stop,assignment;
 await t.test('vehicle validates permissions positive capacity and tenant driver',async()=>{assert.equal((await r(teacher,'/vehicles','POST',{registrationNumber:'X',vehicleType:'BUS',capacity:1})).status,403);assert.equal((await r(admin,'/vehicles','POST',{registrationNumber:'X',vehicleType:'BUS',capacity:0})).status,422);assert.equal((await r(admin,'/vehicles','POST',{registrationNumber:'X',vehicleType:'BUS',capacity:1,driverId:foreignDriver})).status,422);const x=await r(admin,'/vehicles','POST',{registrationNumber:'BUS-01',vehicleType:'BUS',capacity:1,driverId:driver});assert.equal(x.status,201);vehicle=x.data.id;});
 await t.test('route and ordered stops persist',async()=>{const x=await r(admin,'/routes','POST',{name:'North route',vehicleId:vehicle});assert.equal(x.status,201);route=x.data.id;stop=(await r(admin,'/stops','POST',{routeId:route,name:'First stop',sequence:1})).data.id;assert.equal((await r(admin,'/stops','POST',{routeId:route,name:'Second stop',sequence:2})).status,201);assert.deepEqual((await r(admin,'')).data.stops.map(s=>s.sequence),[1,2]);});
 await t.test('cross-tenant enrollment and vehicle relations rejected',async()=>{assert.equal((await r(admin,'/assignments','POST',{enrollmentId:foreignEnrollment,routeId:route,stopId:stop})).status,422);assert.equal((await r(foreignAdmin,'/routes','POST',{name:'Unsafe route',vehicleId:vehicle})).status,422);});
 await t.test('concurrent assignments enforce capacity across shared routes',async()=>{const otherRoute=(await r(admin,'/routes','POST',{name:'Second route',vehicleId:vehicle})).data.id;const otherStop=(await r(admin,'/stops','POST',{routeId:otherRoute,name:'Other stop',sequence:1})).data.id;const x=await Promise.all([r(admin,'/assignments','POST',{enrollmentId:enrollment,routeId:route,stopId:stop}),r(admin,'/assignments','POST',{enrollmentId:second,routeId:otherRoute,stopId:otherStop})]);assert.deepEqual(x.map(a=>a.status).sort(),[201,409]);assignment=x.find(a=>a.status===201).data.id;assert.equal((await r(admin,'')).data.vehicles[0].occupancy,1);assert.equal((await r(admin,`/vehicles/${vehicle}`,'PATCH',{status:'ARCHIVED'})).status,409);});
 await t.test('end preserves history and releases capacity',async()=>{assert.equal((await r(admin,`/assignments/${assignment}/end`,'POST')).status,200);assert.equal((await r(admin,'')).data.vehicles[0].occupancy,0);assert.ok((await r(admin,'')).data.assignments[0].ended_at);});
 await t.test('driver updates and database tenant relations protected and audited',async()=>{assert.equal((await r(admin,`/vehicles/${vehicle}`,'PATCH',{driverId:foreignDriver})).status,422);await assert.rejects(()=>pool.query('UPDATE transport_vehicles SET driver_id=$2 WHERE id=$1',[vehicle,foreignDriver]),e=>e.code==='23503');assert.equal((await pool.query(`SELECT COUNT(*)::int n FROM audit_logs WHERE tenant_id=$1 AND action='TRANSPORT_ASSIGNED'`,[f.tenant])).rows[0].n,1);});
});after(async()=>{if(f)await f.close();else await pool.end();});
