import React from'react';import{OperationsWorkbench,OperationForm,OperationTable}from'../operations/OperationsWorkbench';
const forms:OperationForm[]=[
 {title:'Update vehicle capacity and status',path:b=>`/vehicles/${b.id}`,method:'PATCH',permission:'transport.manage',fields:[{name:'id',label:'Vehicle',type:'select',source:'vehicles'},{name:'capacity',label:'Capacity',type:'number',min:1},{name:'status',label:'Status',type:'select',options:['ACTIVE','INACTIVE','ARCHIVED']}],transform:b=>({capacity:b.capacity,status:b.status})},
 {title:'Add vehicle',path:'/vehicles',permission:'transport.manage',fields:[{name:'registrationNumber',label:'Registration number'},{name:'vehicleType',label:'Vehicle type'},{name:'capacity',label:'Capacity',type:'number',min:1},{name:'driverId',label:'Staff driver',type:'select',source:'staff',optional:true},{name:'insuranceUntil',label:'Insurance expiry',type:'date',optional:true},{name:'permitUntil',label:'Permit expiry',type:'date',optional:true}]},
 {title:'Assign driver to vehicle',path:b=>`/vehicles/${b.id}`,method:'PATCH',permission:'transport.manage',fields:[{name:'id',label:'Vehicle',type:'select',source:'vehicles'},{name:'driverId',label:'Staff driver',type:'select',source:'staff'}],transform:b=>({driverId:b.driverId,status:'ACTIVE'})},
 {title:'Add route',path:'/routes',permission:'transport.manage',fields:[{name:'name',label:'Route name'},{name:'vehicleId',label:'Vehicle',type:'select',source:'vehicles'}]},
 {title:'Update route vehicle / activate legacy route',path:b=>`/routes/${b.id}`,method:'PATCH',permission:'transport.manage',fields:[{name:'id',label:'Route',type:'select',source:'routes'},{name:'vehicleId',label:'Vehicle',type:'select',source:'vehicles'}],transform:b=>({vehicleId:b.vehicleId,status:'ACTIVE'})},
 {title:'Add ordered stop',path:'/stops',permission:'transport.manage',fields:[{name:'routeId',label:'Route',type:'select',source:'routes'},{name:'name',label:'Stop name'},{name:'sequence',label:'Stop sequence',type:'number',min:1}]},
 {title:'Assign student transport',path:'/assignments',permission:'transport.manage',fields:[{name:'enrollmentId',label:'Student enrollment',type:'select',source:'enrollments'},{name:'routeId',label:'Route',type:'select',source:'routes'},{name:'stopId',label:'Matching route stop',type:'select',source:'stops'}]}
];
const tables:OperationTable[]=[{title:'Vehicles and occupancy',source:'vehicles',columns:{registration_number:'Registration',vehicle_type:'Type',driver_name:'Driver',capacity:'Capacity',occupancy:'Occupied',status:'Status',insurance_until:'Insurance',permit_until:'Permit'},action:{label:'Archive',permission:'transport.manage',method:'PATCH',path:r=>`/vehicles/${r.id}`,body:()=>({status:'ARCHIVED'}),show:r=>r.status!=='ARCHIVED'}},{title:'Routes',source:'routes',columns:{name:'Route',vehicle:'Vehicle',status:'Status'},action:{label:'Archive',permission:'transport.manage',method:'PATCH',path:r=>`/routes/${r.id}`,body:()=>({status:'ARCHIVED'}),show:r=>r.status!=='ARCHIVED'}},{title:'Ordered stops',source:'stops',columns:{route_name:'Route',name:'Stop',sequence:'Sequence'}},{title:'Student assignments',source:'assignments',columns:{student_name:'Student',route_name:'Route',stop_name:'Stop',assigned_at:'Assigned',ended_at:'Ended'},action:{label:'End assignment',permission:'transport.manage',path:r=>`/assignments/${r.id}/end`,show:r=>!r.ended_at}}];
export const TransportOperationsModule:React.FC=()=> <OperationsWorkbench title="Transport" module="transport" forms={forms} tables={tables} note="Capacity is enforced across all routes sharing a vehicle. Assign an active staff driver before assigning students."/>;
