import { Router, Request, Response } from 'express';
import { createHash, randomBytes } from 'node:crypto';
import { z } from 'zod';
import { query, transaction } from '../db.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { tenantContext } from '../middleware/tenantContext.js';
import { requirePermission } from '../middleware/permission.js';
import { validateBody } from '../middleware/validation.js';
import { AppError } from '../middleware/errorHandler.js';
import { writeAudit } from '../services/auditService.js';

const router=Router(); router.use(tenantContext(true));
const staffSchema=z.object({employeeId:z.string().trim().min(1).max(100),name:z.string().trim().min(2).max(255),email:z.string().email().optional().nullable(),phone:z.string().max(50).optional().nullable(),designation:z.string().trim().min(2).max(100),department:z.string().trim().min(2).max(100),branchId:z.string().uuid().optional().nullable(),employmentType:z.enum(['FULL_TIME','PART_TIME','CONTRACT','TEMPORARY']).default('FULL_TIME'),joinedDate:z.string().date().optional().nullable(),status:z.enum(['ACTIVE','INACTIVE','ON_LEAVE']).default('ACTIVE'),address:z.string().max(2000).optional().nullable(),emergencyContact:z.string().max(100).optional().nullable(),teacherProfile:z.object({qualification:z.string().max(1000).optional().nullable(),specialization:z.string().max(1000).optional().nullable(),experienceYears:z.number().int().min(0).max(80).default(0),bio:z.string().max(4000).optional().nullable()}).optional()});
const assignmentSchema=z.object({teacherId:z.string().uuid(),subjectId:z.string().uuid(),classId:z.string().uuid(),sectionId:z.string().uuid().optional().nullable(),academicYearId:z.string().uuid(),isPrimary:z.boolean().default(false)});
const selectStaff=`SELECT s.*,b.name branch_name,tp.qualification,tp.specialization,tp.experience_years,tp.bio,u.email account_email FROM staff s LEFT JOIN branches b ON b.id=s.branch_id AND b.tenant_id=s.tenant_id LEFT JOIN teacher_profiles tp ON tp.staff_id=s.id AND tp.tenant_id=s.tenant_id LEFT JOIN users u ON u.id=s.user_id`;
const map=(s:any)=>({id:s.id,tenantId:s.tenant_id,userId:s.user_id,employeeId:s.employee_id,name:s.name,email:s.email,phone:s.phone,designation:s.designation,department:s.department,branchId:s.branch_id,branchName:s.branch_name,employmentType:s.employment_type,status:s.status,joinedDate:s.joined_date,address:s.address,emergencyContact:s.emergency_contact,accountEmail:s.account_email,teacherProfile:s.qualification!==null||s.specialization!==null||s.bio!==null?{qualification:s.qualification,specialization:s.specialization,experienceYears:s.experience_years,bio:s.bio}:null,createdAt:s.created_at,updatedAt:s.updated_at});

router.get('/',requirePermission('staff.view'),asyncHandler(async(req:Request,res:Response)=>{const r=await query(`${selectStaff} WHERE s.tenant_id=$1 ORDER BY s.name`,[req.tenantId]);res.json({data:r.rows.map(map),meta:{total:r.rowCount},requestId:req.id,timestamp:new Date().toISOString()});}));
router.post('/',requirePermission('staff.manage'),validateBody(staffSchema),asyncHandler(async(req:Request,res:Response)=>{const b=req.body;const id=await transaction(async c=>{if(b.branchId&&!await c.query('SELECT 1 FROM branches WHERE id=$1 AND tenant_id=$2',[b.branchId,req.tenantId]).then(x=>x.rowCount))throw new AppError('Branch not found.',422,'INVALID_BRANCH');const s=(await c.query(`INSERT INTO staff(tenant_id,employee_id,name,email,phone,designation,department,branch_id,employment_type,joined_date,status,address,emergency_contact) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[req.tenantId,b.employeeId,b.name,b.email||null,b.phone||null,b.designation,b.department,b.branchId||null,b.employmentType,b.joinedDate||null,b.status,b.address||null,b.emergencyContact||null])).rows[0];if(b.teacherProfile)await c.query(`INSERT INTO teacher_profiles(staff_id,tenant_id,qualification,specialization,experience_years,bio) VALUES($1,$2,$3,$4,$5,$6)`,[s.id,req.tenantId,b.teacherProfile.qualification||null,b.teacherProfile.specialization||null,b.teacherProfile.experienceYears,b.teacherProfile.bio||null]);await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'STAFF_CREATED',module:'staff',entityId:s.id,details:{employeeId:b.employeeId,teacher:Boolean(b.teacherProfile)},request:req},c);return s.id;});const r=await query(`${selectStaff} WHERE s.id=$1 AND s.tenant_id=$2`,[id,req.tenantId]);res.status(201).json({data:map(r.rows[0]),requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/assignments',requirePermission('teaching_assignments.view'),asyncHandler(async(req:Request,res:Response)=>{const restricted=!req.user.isSuperAdmin&&req.user.role!=='TENANT_ADMIN';const r=await query(`SELECT a.*,s.name teacher_name,sub.name subject_name,c.name class_name,se.name section_name,y.name academic_year_name FROM teacher_subject_assignments a JOIN staff s ON s.id=a.teacher_id AND s.tenant_id=a.tenant_id JOIN subjects sub ON sub.id=a.subject_id AND sub.tenant_id=a.tenant_id JOIN classes c ON c.id=a.class_id AND c.tenant_id=a.tenant_id LEFT JOIN sections se ON se.id=a.section_id AND se.tenant_id=a.tenant_id JOIN academic_years y ON y.id=a.academic_year_id AND y.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND ($2::boolean=false OR s.user_id=$3) ORDER BY s.name,c.name,se.name NULLS FIRST,sub.name`,[req.tenantId,restricted,req.user.id]);res.json({data:r.rows,meta:{total:r.rowCount},requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/teaching-context',requirePermission('teaching_assignments.view'),asyncHandler(async(req:Request,res:Response)=>{const r=await query(`SELECT DISTINCT a.academic_year_id,y.name academic_year_name,a.class_id,c.name class_name,a.section_id,se.name section_name,a.subject_id,sub.name subject_name FROM staff s JOIN teacher_subject_assignments a ON a.teacher_id=s.id AND a.tenant_id=s.tenant_id JOIN academic_years y ON y.id=a.academic_year_id AND y.tenant_id=a.tenant_id JOIN classes c ON c.id=a.class_id AND c.tenant_id=a.tenant_id LEFT JOIN sections se ON se.id=a.section_id AND se.tenant_id=a.tenant_id JOIN subjects sub ON sub.id=a.subject_id AND sub.tenant_id=a.tenant_id WHERE s.tenant_id=$1 AND s.user_id=$2 AND s.status='ACTIVE' ORDER BY y.name,c.name,se.name NULLS FIRST,sub.name`,[req.tenantId,req.user.id]);res.json({data:r.rows,requestId:req.id,timestamp:new Date().toISOString()});}));
router.post('/assignments',requirePermission('teaching_assignments.manage'),validateBody(assignmentSchema),asyncHandler(async(req:Request,res:Response)=>{const b=req.body;const r=await query(`INSERT INTO teacher_subject_assignments(tenant_id,teacher_id,subject_id,class_id,section_id,academic_year_id,is_primary) SELECT $1,$2,$3,$4,$5,$6,$7 WHERE EXISTS(SELECT 1 FROM teacher_profiles WHERE staff_id=$2 AND tenant_id=$1) RETURNING *`,[req.tenantId,b.teacherId,b.subjectId,b.classId,b.sectionId||null,b.academicYearId,b.isPrimary]);if(!r.rowCount)throw new AppError('Teacher profile not found.',422,'INVALID_TEACHER');await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'TEACHING_ASSIGNMENT_CREATED',module:'academics',entityId:r.rows[0].id,details:b,request:req});res.status(201).json({data:r.rows[0],requestId:req.id,timestamp:new Date().toISOString()});}));
router.delete('/assignments/:id',requirePermission('teaching_assignments.manage'),asyncHandler(async(req:Request,res:Response)=>{const r=await query('DELETE FROM teacher_subject_assignments WHERE id=$1 AND tenant_id=$2 RETURNING id',[req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Assignment not found.',404,'NOT_FOUND');await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'TEACHING_ASSIGNMENT_DELETED',module:'academics',entityId:req.params.id,request:req});res.json({data:{success:true},requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/:id',requirePermission('staff.view'),asyncHandler(async(req:Request,res:Response)=>{const r=await query(`${selectStaff} WHERE s.id=$1 AND s.tenant_id=$2`,[req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Staff member not found.',404,'NOT_FOUND');res.json({data:map(r.rows[0]),requestId:req.id,timestamp:new Date().toISOString()});}));
router.patch('/:id',requirePermission('staff.manage'),validateBody(staffSchema.partial().omit({employeeId:true})),asyncHandler(async(req:Request,res:Response)=>{const b=req.body;const cols:Record<string,string>={name:'name',email:'email',phone:'phone',designation:'designation',department:'department',branchId:'branch_id',employmentType:'employment_type',joinedDate:'joined_date',status:'status',address:'address',emergencyContact:'emergency_contact'};const values:any[]=[];const sets:string[]=[];for(const[k,col]of Object.entries(cols))if(b[k]!==undefined){values.push(b[k]);sets.push(`${col}=$${values.length}`)}if(!sets.length&&!b.teacherProfile)throw new AppError('No changes supplied.',422,'VALIDATION_ERROR');await transaction(async c=>{if(sets.length){values.push(req.params.id,req.tenantId);const r=await c.query(`UPDATE staff SET ${sets.join(',')},updated_at=NOW() WHERE id=$${values.length-1} AND tenant_id=$${values.length}`,values);if(!r.rowCount)throw new AppError('Staff member not found.',404,'NOT_FOUND');}if(b.teacherProfile)await c.query(`INSERT INTO teacher_profiles(staff_id,tenant_id,qualification,specialization,experience_years,bio) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(staff_id) DO UPDATE SET qualification=EXCLUDED.qualification,specialization=EXCLUDED.specialization,experience_years=EXCLUDED.experience_years,bio=EXCLUDED.bio,updated_at=NOW()`,[req.params.id,req.tenantId,b.teacherProfile.qualification||null,b.teacherProfile.specialization||null,b.teacherProfile.experienceYears||0,b.teacherProfile.bio||null]);await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'STAFF_UPDATED',module:'staff',entityId:req.params.id,details:b,request:req},c);});const r=await query(`${selectStaff} WHERE s.id=$1 AND s.tenant_id=$2`,[req.params.id,req.tenantId]);res.json({data:map(r.rows[0]),requestId:req.id,timestamp:new Date().toISOString()});}));
router.post('/:id/invitation',requirePermission('teacher_accounts.manage'),validateBody(z.object({email:z.string().email().optional(),displayName:z.string().min(2).max(255).optional()})),asyncHandler(async(req:Request,res:Response)=>{const token=randomBytes(32).toString('base64url');const hash=createHash('sha256').update(token).digest('hex');const data=await transaction(async c=>{const s=(await c.query(`SELECT s.* FROM staff s JOIN teacher_profiles tp ON tp.staff_id=s.id AND tp.tenant_id=s.tenant_id WHERE s.id=$1 AND s.tenant_id=$2 FOR UPDATE`,[req.params.id,req.tenantId])).rows[0];if(!s)throw new AppError('Teacher profile not found.',404,'NOT_FOUND');if(s.user_id)throw new AppError('Teacher already has a user account.',409,'ACCOUNT_EXISTS');const email=(req.body.email||s.email||'').trim().toLowerCase();if(!email)throw new AppError('Teacher email is required.',422,'EMAIL_REQUIRED');const role=(await c.query(`SELECT id FROM roles WHERE key='TEACHER' AND tenant_id IS NULL`)).rows[0];await c.query(`UPDATE user_invitations SET status='revoked' WHERE tenant_id=$1 AND staff_id=$2 AND status='pending'`,[req.tenantId,s.id]);const i=(await c.query(`INSERT INTO user_invitations(tenant_id,email,display_name,role_id,token_hash,invited_by,expires_at,staff_id) VALUES($1,$2,$3,$4,$5,$6,NOW()+INTERVAL '7 days',$7) RETURNING id,email,expires_at`,[req.tenantId,email,req.body.displayName||s.name,role.id,hash,req.user.id,s.id])).rows[0];await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'TEACHER_ACCOUNT_INVITED',module:'staff',entityId:s.id,details:{invitationId:i.id,email},request:req},c);return i;});res.status(201).json({data:{...data,onboardingToken:token},requestId:req.id,timestamp:new Date().toISOString()});}));
export default router;
