import { Router,Request,Response } from 'express'; import { z } from 'zod';
import { query,transaction } from '../db.js'; import { asyncHandler } from '../middleware/asyncHandler.js'; import { tenantContext } from '../middleware/tenantContext.js'; import { requirePermission } from '../middleware/permission.js'; import { validateBody } from '../middleware/validation.js'; import { AppError } from '../middleware/errorHandler.js'; import { writeAudit } from '../services/auditService.js'; import { requireTeachingScope } from '../services/teachingAccess.js';
const router=Router();router.use(tenantContext(true));
const bulk=z.object({academicYearId:z.string().uuid(),classId:z.string().uuid(),sectionId:z.string().uuid(),date:z.string().date(),records:z.array(z.object({enrollmentId:z.string().uuid(),status:z.enum(['PRESENT','ABSENT','LATE','EXCUSED','HALF_DAY']),remarks:z.string().max(1000).optional().nullable()})).min(1).max(200)});
function filters(req:Request){const year=String(req.query.academicYearId||''),classId=String(req.query.classId||''),section=String(req.query.sectionId||''),date=String(req.query.date||'');if(!year||!classId||!section||!date)throw new AppError('academicYearId, classId, sectionId, and date are required.',422,'ROSTER_SCOPE_REQUIRED');return{year,classId,section,date};}
router.get('/roster',requirePermission('attendance.view'),asyncHandler(async(req:Request,res:Response)=>{const f=filters(req);await requireTeachingScope(req,f.year,f.classId,f.section);const r=await query(`SELECT e.id enrollment_id,e.student_id,e.roll_no,s.admission_no,s.first_name,s.last_name,a.id attendance_id,a.status,a.remarks FROM enrollments e JOIN students s ON s.id=e.student_id AND s.tenant_id=e.tenant_id LEFT JOIN attendance_records a ON a.enrollment_id=e.id AND a.tenant_id=e.tenant_id AND a.attendance_date=$5 WHERE e.tenant_id=$1 AND e.academic_year_id=$2 AND e.class_id=$3 AND e.section_id=$4 AND e.status='enrolled' AND e.start_date<=$5 AND (e.end_date IS NULL OR e.end_date>=$5) ORDER BY e.roll_no NULLS LAST,s.first_name,s.last_name`,[req.tenantId,f.year,f.classId,f.section,f.date]);res.json({data:r.rows,meta:{total:r.rowCount},requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/',requirePermission('attendance.view'),asyncHandler(async(req:Request,res:Response)=>{const f=filters(req);await requireTeachingScope(req,f.year,f.classId,f.section);const r=await query(`SELECT a.*,e.class_id,e.roll_no,s.admission_no,s.first_name,s.last_name FROM attendance_records a JOIN enrollments e ON e.id=a.enrollment_id AND e.tenant_id=a.tenant_id JOIN students s ON s.id=a.student_id AND s.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND a.academic_year_id=$2 AND e.class_id=$3 AND a.section_id=$4 AND a.attendance_date=$5 ORDER BY e.roll_no NULLS LAST,s.first_name`,[req.tenantId,f.year,f.classId,f.section,f.date]);res.json({data:r.rows,meta:{total:r.rowCount},requestId:req.id,timestamp:new Date().toISOString()});}));
router.post('/bulk',requirePermission('attendance.manage'),validateBody(bulk),asyncHandler(async(req:Request,res:Response)=>{const b=req.body;await requireTeachingScope(req,b.academicYearId,b.classId,b.sectionId);const saved=await transaction(async c=>{const ids=b.records.map((x:any)=>x.enrollmentId);const valid=await c.query(`SELECT id,student_id FROM enrollments WHERE tenant_id=$1 AND academic_year_id=$2 AND class_id=$3 AND section_id=$4 AND id=ANY($5::uuid[]) AND status='enrolled' AND start_date<=$6 AND (end_date IS NULL OR end_date>=$6)`,[req.tenantId,b.academicYearId,b.classId,b.sectionId,ids,b.date]);if(valid.rowCount!==new Set(ids).size)throw new AppError('Every attendance record must reference an active enrollment in the selected class.',422,'INVALID_ENROLLMENT');const students=new Map(valid.rows.map(x=>[x.id,x.student_id]));const out=[];for(const item of b.records){const r=await c.query(`INSERT INTO attendance_records(tenant_id,student_id,enrollment_id,academic_year_id,section_id,attendance_date,status,remarks,marked_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(tenant_id,enrollment_id,attendance_date) DO UPDATE SET status=EXCLUDED.status,remarks=EXCLUDED.remarks,marked_by=EXCLUDED.marked_by,updated_at=NOW() RETURNING *`,[req.tenantId,students.get(item.enrollmentId),item.enrollmentId,b.academicYearId,b.sectionId,b.date,item.status,item.remarks||null,req.user.id]);out.push(r.rows[0]);}await writeAudit({tenantId:req.tenantId!,userId:req.user.id,action:'ATTENDANCE_BULK_RECORDED',module:'attendance',details:{academicYearId:b.academicYearId,classId:b.classId,sectionId:b.sectionId,date:b.date,count:out.length},request:req},c);return out;});res.status(201).json({data:saved,meta:{total:saved.length},requestId:req.id,timestamp:new Date().toISOString()});}));
export default router;
