import{Router}from'express';import{z}from'zod';import{query,transaction}from'../db.js';import{tenantContext}from'../middleware/tenantContext.js';import{requirePermission}from'../middleware/permission.js';import{asyncHandler}from'../middleware/asyncHandler.js';import{validateBody}from'../middleware/validation.js';import{AppError}from'../middleware/errorHandler.js';import{id,state,validateId,logOperation,operationError}from'./operationsSupport.js';const router=Router();router.use(tenantContext(true));
router.get('/',requirePermission('hostel.view'),asyncHandler(async(req,res)=>{const t=req.tenantId;const[buildings,rooms,beds,allocations,enrollments]=await Promise.all([
 query('SELECT * FROM hostel_buildings WHERE tenant_id=$1 ORDER BY name',[t]),
 query(`SELECT r.id,r.room_number name,b.name building,r.lifecycle_status status,COUNT(bed.id)::int capacity,COUNT(bed.id) FILTER(WHERE bed.status='LEGACY_HOLD' OR EXISTS(SELECT 1 FROM hostel_allocations a WHERE a.bed_id=bed.id AND a.checked_out_at IS NULL))::int occupied,COUNT(bed.id) FILTER(WHERE b.status='ACTIVE' AND r.lifecycle_status='ACTIVE' AND bed.status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM hostel_allocations a WHERE a.bed_id=bed.id AND a.checked_out_at IS NULL))::int available FROM hostel_rooms r JOIN hostel_buildings b ON b.id=r.building_id AND b.tenant_id=r.tenant_id LEFT JOIN hostel_beds bed ON bed.room_id=r.id AND bed.tenant_id=r.tenant_id WHERE r.tenant_id=$1 GROUP BY r.id,b.name ORDER BY b.name,r.room_number`,[t]),
 query(`SELECT bed.*,b.name||' / '||r.room_number||' / '||bed.label name,CASE WHEN b.status<>'ACTIVE' THEN b.status WHEN r.lifecycle_status<>'ACTIVE' THEN r.lifecycle_status WHEN EXISTS(SELECT 1 FROM hostel_allocations a WHERE a.bed_id=bed.id AND a.checked_out_at IS NULL) THEN 'OCCUPIED' ELSE bed.status END availability FROM hostel_beds bed JOIN hostel_rooms r ON r.id=bed.room_id AND r.tenant_id=bed.tenant_id JOIN hostel_buildings b ON b.id=r.building_id AND b.tenant_id=r.tenant_id WHERE bed.tenant_id=$1 ORDER BY b.name,r.room_number,bed.label`,[t]),
 query(`SELECT a.*,s.first_name||' '||s.last_name student_name,bed.label bed,r.room_number room,b.name building FROM hostel_allocations a JOIN students s ON s.id=a.student_id AND s.tenant_id=a.tenant_id JOIN hostel_beds bed ON bed.id=a.bed_id AND bed.tenant_id=a.tenant_id JOIN hostel_rooms r ON r.id=bed.room_id AND r.tenant_id=bed.tenant_id JOIN hostel_buildings b ON b.id=r.building_id AND b.tenant_id=r.tenant_id WHERE a.tenant_id=$1 ORDER BY a.allocated_at DESC`,[t]),
 query(`SELECT e.id,s.first_name||' '||s.last_name||' · '||y.name name FROM enrollments e JOIN students s ON s.id=e.student_id AND s.tenant_id=e.tenant_id JOIN academic_years y ON y.id=e.academic_year_id AND y.tenant_id=e.tenant_id WHERE e.tenant_id=$1 AND e.status='enrolled' ORDER BY s.first_name`,[t])]);res.json({data:{buildings:buildings.rows,rooms:rooms.rows,beds:beds.rows,allocations:allocations.rows,enrollments:enrollments.rows}});
}));
router.post('/buildings',requirePermission('hostel.manage'),validateBody(z.object({name:z.string().trim().min(2).max(100)})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const r=(await c.query('INSERT INTO hostel_buildings(tenant_id,name) VALUES($1,$2) RETURNING *',[req.tenantId,req.body.name])).rows[0];await logOperation(req,c,'hostel','HOSTEL_BUILDING_CREATED',r.id);return r;});res.status(201).json({data});}));
router.post('/rooms',requirePermission('hostel.manage'),validateBody(z.object({buildingId:id,roomNumber:z.string().trim().min(1).max(50),capacity:z.number().int().min(1).max(1000)})),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{const building=(await c.query(`SELECT name FROM hostel_buildings WHERE id=$1 AND tenant_id=$2 AND status='ACTIVE' FOR UPDATE`,[b.buildingId,req.tenantId])).rows[0];if(!building)throw new AppError('Active building not found.',422,'INVALID_REFERENCE');if((await c.query('SELECT id FROM hostel_rooms WHERE building_id=$1 AND tenant_id=$2 AND room_number=$3',[b.buildingId,req.tenantId,b.roomNumber])).rowCount)throw new AppError('Room number already exists in this building.',409,'ROOM_EXISTS');const r=(await c.query('INSERT INTO hostel_rooms(tenant_id,building_id,hostel_name,room_number,capacity,occupied) VALUES($1,$2,$3,$4,$5,0) RETURNING *',[req.tenantId,b.buildingId,building.name,b.roomNumber,b.capacity])).rows[0];await c.query(`INSERT INTO hostel_beds(tenant_id,room_id,label) SELECT $1,$2,'Bed '||n FROM generate_series(1,$3::int) n`,[req.tenantId,r.id,b.capacity]);await logOperation(req,c,'hostel','HOSTEL_ROOM_CREATED',r.id,{capacity:b.capacity});return r;});res.status(201).json({data});}));
router.patch('/buildings/:id',validateId,requirePermission('hostel.manage'),validateBody(z.object({status:state})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const b=(await c.query('SELECT id FROM hostel_buildings WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,req.tenantId])).rows[0];if(!b)throw new AppError('Building not found.',404,'NOT_FOUND');if(req.body.status!=='ACTIVE'&&(await c.query(`SELECT 1 FROM hostel_beds bed JOIN hostel_rooms r ON r.id=bed.room_id AND r.tenant_id=bed.tenant_id WHERE r.building_id=$1 AND r.tenant_id=$2 AND (bed.status='LEGACY_HOLD' OR EXISTS(SELECT 1 FROM hostel_allocations a WHERE a.bed_id=bed.id AND a.checked_out_at IS NULL))`,[b.id,req.tenantId])).rowCount)throw new AppError('Building has occupied or legacy-held beds.',409,'BUILDING_OCCUPIED');const r=(await c.query('UPDATE hostel_buildings SET status=$3 WHERE id=$1 AND tenant_id=$2 RETURNING *',[b.id,req.tenantId,req.body.status])).rows[0];await logOperation(req,c,'hostel','HOSTEL_BUILDING_UPDATED',r.id,req.body);return r;});res.json({data});}));
router.post('/allocations',requirePermission('hostel.manage'),validateBody(z.object({bedId:id,enrollmentId:id})),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{
 const initial=(await c.query(`SELECT r.building_id FROM hostel_beds bed JOIN hostel_rooms r ON r.id=bed.room_id AND r.tenant_id=bed.tenant_id WHERE bed.id=$1 AND bed.tenant_id=$2`,[b.bedId,req.tenantId])).rows[0];if(!initial)throw new AppError('Bed not found.',422,'INVALID_REFERENCE');
 const building=(await c.query('SELECT status FROM hostel_buildings WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[initial.building_id,req.tenantId])).rows[0];
 const bed=(await c.query(`SELECT bed.*,r.lifecycle_status room_status FROM hostel_beds bed JOIN hostel_rooms r ON r.id=bed.room_id AND r.tenant_id=bed.tenant_id WHERE bed.id=$1 AND bed.tenant_id=$2 FOR UPDATE OF bed`,[b.bedId,req.tenantId])).rows[0];if(building.status!=='ACTIVE'||bed.status!=='ACTIVE'||bed.room_status!=='ACTIVE')throw new AppError('Bed unavailable.',409,'BED_UNAVAILABLE');
 const e=(await c.query(`SELECT e.student_id FROM enrollments e JOIN students s ON s.id=e.student_id AND s.tenant_id=e.tenant_id WHERE e.id=$1 AND e.tenant_id=$2 AND e.status='enrolled' AND s.status='ACTIVE'`,[b.enrollmentId,req.tenantId])).rows[0];if(!e)throw new AppError('Active enrollment not found.',422,'INVALID_REFERENCE');
 await c.query('SELECT id FROM students WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[e.student_id,req.tenantId]);
 if((await c.query(`SELECT 1 FROM hostel_allocations WHERE tenant_id=$1 AND checked_out_at IS NULL AND (bed_id=$2 OR student_id=$3)`,[req.tenantId,bed.id,e.student_id])).rowCount)throw new AppError('Bed or student already allocated.',409,'ALREADY_ALLOCATED');
 const r=(await c.query('INSERT INTO hostel_allocations(tenant_id,bed_id,enrollment_id,student_id) VALUES($1,$2,$3,$4) RETURNING *',[req.tenantId,bed.id,b.enrollmentId,e.student_id])).rows[0];await logOperation(req,c,'hostel','HOSTEL_BED_ALLOCATED',r.id);return r;
 });res.status(201).json({data});
}));
router.post('/allocations/:id/checkout',validateId,requirePermission('hostel.manage'),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const target=(await c.query('SELECT bed_id FROM hostel_allocations WHERE id=$1 AND tenant_id=$2',[req.params.id,req.tenantId])).rows[0];if(!target)throw new AppError('Allocation not found.',404,'NOT_FOUND');await c.query('SELECT id FROM hostel_beds WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[target.bed_id,req.tenantId]);const r=(await c.query('UPDATE hostel_allocations SET checked_out_at=NOW() WHERE id=$1 AND tenant_id=$2 AND checked_out_at IS NULL RETURNING *',[req.params.id,req.tenantId])).rows[0];if(!r)throw new AppError('Allocation already checked out.',409,'INVALID_ALLOCATION_STATE');await logOperation(req,c,'hostel','HOSTEL_CHECKOUT',r.id);return r;});res.json({data});}));
router.use((_req,_res,next)=>next(new AppError('Hostel endpoint not found.',404,'NOT_FOUND')));router.use(operationError);export default router;
