import {Router} from 'express';import{z}from'zod';import{query,transaction}from'../db.js';import{tenantContext}from'../middleware/tenantContext.js';import{requirePermission}from'../middleware/permission.js';import{asyncHandler}from'../middleware/asyncHandler.js';import{validateBody}from'../middleware/validation.js';import{AppError}from'../middleware/errorHandler.js';import{id,text,state,validateId,logOperation,operationError}from'./operationsSupport.js';
const router=Router();router.use(tenantContext(true));
router.get('/',requirePermission('inventory.view'),asyncHandler(async(req,res)=>{const t=req.tenantId;const[items,categories,locations,movements,balances]=await Promise.all([
 query(`SELECT i.id,i.name,i.sku,i.item_type,i.unit,i.min_stock_alert,i.lifecycle_status status,c.name category,COALESCE(SUM(st.quantity_delta),0)::int stock,COALESCE(SUM(st.quantity_delta),0)<=i.min_stock_alert low_stock FROM inventory_items i LEFT JOIN inventory_categories c ON c.id=i.category_id AND c.tenant_id=i.tenant_id LEFT JOIN stock_transactions st ON st.item_id=i.id AND st.tenant_id=i.tenant_id WHERE i.tenant_id=$1 GROUP BY i.id,c.name ORDER BY i.name`,[t]),query('SELECT * FROM inventory_categories WHERE tenant_id=$1 ORDER BY name',[t]),query('SELECT * FROM inventory_locations WHERE tenant_id=$1 ORDER BY name',[t]),
 query(`SELECT st.*,i.name item_name,l.name location_name,st.type||' · '||i.name||' · '||l.name||' · '||st.quantity_delta name FROM stock_transactions st JOIN inventory_items i ON i.id=st.item_id AND i.tenant_id=st.tenant_id JOIN inventory_locations l ON l.id=st.location_id AND l.tenant_id=st.tenant_id WHERE st.tenant_id=$1 ORDER BY st.created_at DESC`,[t]),
 query(`SELECT i.id::text||':'||l.id::text id,i.name item_name,l.name location_name,SUM(st.quantity_delta)::int stock FROM stock_transactions st JOIN inventory_items i ON i.id=st.item_id AND i.tenant_id=st.tenant_id JOIN inventory_locations l ON l.id=st.location_id AND l.tenant_id=st.tenant_id WHERE st.tenant_id=$1 GROUP BY i.id,l.id ORDER BY i.name,l.name`,[t])]);res.json({data:{items:items.rows,categories:categories.rows,locations:locations.rows,movements:movements.rows,issues:movements.rows.filter(x=>x.type==='ISSUE'),balances:balances.rows}});
}));
for(const name of ['categories','locations'] as const)router.post(`/${name}`,requirePermission('inventory.manage'),validateBody(z.object({name:z.string().trim().min(1).max(100)})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const r=(await c.query(`INSERT INTO inventory_${name}(tenant_id,name) VALUES($1,$2) RETURNING *`,[req.tenantId,req.body.name])).rows[0];await logOperation(req,c,'inventory',`INVENTORY_${name.toUpperCase()}_CREATED`,r.id);return r;});res.status(201).json({data});}));
router.post('/items',requirePermission('inventory.manage'),validateBody(z.object({name:text,sku:z.string().trim().min(1).max(100),categoryId:id,itemType:z.enum(['CONSUMABLE','ASSET']),unit:z.string().trim().min(1).max(50),minStockAlert:z.number().int().min(0).max(1000000)})),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{const category=(await c.query('SELECT name FROM inventory_categories WHERE id=$1 AND tenant_id=$2',[b.categoryId,req.tenantId])).rows[0];if(!category)throw new AppError('Category not found.',422,'INVALID_REFERENCE');const r=(await c.query(`INSERT INTO inventory_items(tenant_id,name,sku,category,category_id,item_type,unit,min_stock_alert,quantity) VALUES($1,$2,$3,$4,$5,$6,$7,$8,0) RETURNING *`,[req.tenantId,b.name,b.sku,category.name,b.categoryId,b.itemType,b.unit,b.minStockAlert])).rows[0];await logOperation(req,c,'inventory','INVENTORY_ITEM_CREATED',r.id);return r;});res.status(201).json({data});}));
router.patch('/items/:id',validateId,requirePermission('inventory.manage'),validateBody(z.object({status:state})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const r=(await c.query('UPDATE inventory_items SET lifecycle_status=$3 WHERE id=$1 AND tenant_id=$2 RETURNING *',[req.params.id,req.tenantId,req.body.status])).rows[0];if(!r)throw new AppError('Item not found.',404,'NOT_FOUND');await logOperation(req,c,'inventory','INVENTORY_ITEM_UPDATED',r.id,req.body);return r;});res.json({data});}));
router.post('/movements',requirePermission('inventory.transact'),validateBody(z.object({itemId:id,locationId:id,type:z.enum(['RECEIPT','ISSUE','RETURN','ADJUSTMENT']),quantity:z.number().int().min(-1000000).max(1000000).refine(x=>x!==0),reason:z.string().trim().min(3).max(2000),sourceIssueId:id.optional()}).refine(b=>b.type==='ADJUSTMENT'||b.quantity>0,'Quantity must be positive.').refine(b=>(b.type==='RETURN')===Boolean(b.sourceIssueId),'Returns require a source issue only.')),asyncHandler(async(req,res)=>{
 const b=req.body;const data=await transaction(async c=>{
 const item=(await c.query(`SELECT id FROM inventory_items WHERE id=$1 AND tenant_id=$2 AND lifecycle_status='ACTIVE' FOR UPDATE`,[b.itemId,req.tenantId])).rows[0];if(!item||!(await c.query('SELECT id FROM inventory_locations WHERE id=$1 AND tenant_id=$2',[b.locationId,req.tenantId])).rowCount)throw new AppError('Active item or location not found.',422,'INVALID_REFERENCE');
 const delta=b.type==='ISSUE'?-b.quantity:b.quantity;
 const balance=Number((await c.query('SELECT COALESCE(SUM(quantity_delta),0) stock FROM stock_transactions WHERE tenant_id=$1 AND item_id=$2 AND location_id=$3',[req.tenantId,b.itemId,b.locationId])).rows[0].stock);
 if(balance+delta<0)throw new AppError('Insufficient stock at this location.',409,'INSUFFICIENT_STOCK');
 if(b.type==='RETURN'){const issue=(await c.query(`SELECT quantity_delta FROM stock_transactions WHERE id=$1 AND tenant_id=$2 AND item_id=$3 AND location_id=$4 AND type='ISSUE'`,[b.sourceIssueId,req.tenantId,b.itemId,b.locationId])).rows[0];if(!issue)throw new AppError('Matching source issue not found.',422,'INVALID_REFERENCE');const returned=Number((await c.query(`SELECT COALESCE(SUM(quantity_delta),0) qty FROM stock_transactions WHERE source_issue_id=$1 AND tenant_id=$2`,[b.sourceIssueId,req.tenantId])).rows[0].qty);if(returned+b.quantity>-issue.quantity_delta)throw new AppError('Return exceeds issued quantity.',409,'EXCESS_RETURN');}
 const r=(await c.query('INSERT INTO stock_transactions(tenant_id,item_id,location_id,type,quantity_delta,source_issue_id,reason,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.tenantId,b.itemId,b.locationId,b.type,delta,b.sourceIssueId||null,b.reason,req.user.id])).rows[0];await logOperation(req,c,'inventory','STOCK_MOVEMENT_RECORDED',r.id,{type:b.type,delta,balanceAfter:balance+delta});return r;
 });res.status(201).json({data});
}));
router.use((_req,_res,next)=>next(new AppError('Inventory endpoint not found.',404,'NOT_FOUND')));router.use(operationError);export default router;
