import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { query, transaction } from '../db.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { tenantContext } from '../middleware/tenantContext.js';
import { requirePermission } from '../middleware/permission.js';
import { validateBody } from '../middleware/validation.js';
import { AppError } from '../middleware/errorHandler.js';
import { writeAudit } from '../services/auditService.js';

const router = Router();
router.use(tenantContext(true));
const uuid = z.string().uuid();
const emptyToNull = (schema: z.ZodTypeAny) =>
  z.preprocess(val => (typeof val === 'string' && val.trim() === '' ? null : val), schema);

const profileSchema = z.object({
  name: z.string().trim().min(2).max(255).optional(),
  email: emptyToNull(z.string().email().nullable()).optional(),
  phone: emptyToNull(z.string().max(50).nullable()).optional(),
  website: emptyToNull(z.string().url().nullable()).optional(),
  logoUrl: emptyToNull(z.string().url().nullable()).optional(),
  timezone: z.string().min(1).max(50).optional(),
  addressLine1: emptyToNull(z.string().max(500).nullable()).optional(),
  addressLine2: emptyToNull(z.string().max(500).nullable()).optional(),
  city: emptyToNull(z.string().max(100).nullable()).optional(),
  state: emptyToNull(z.string().max(100).nullable()).optional(),
  postalCode: emptyToNull(z.string().max(20).nullable()).optional(),
  country: z.string().max(100).optional()
});
const yearBaseSchema = z.object({ name:z.string().trim().min(4).max(100), startDate:z.string().date(), endDate:z.string().date(), status:z.enum(['upcoming','active','closed','archived']).default('upcoming'), isCurrent:z.boolean().default(false) });
const yearSchema = yearBaseSchema.refine(v=>v.endDate>v.startDate,{message:'End date must be after start date'});
const branchSchema = z.object({ name:z.string().trim().min(2).max(255), code:z.string().trim().regex(/^[A-Z0-9_-]{2,50}$/), email:emptyToNull(z.string().email().nullable()).optional(), phone:emptyToNull(z.string().max(50).nullable()).optional(), addressLine1:emptyToNull(z.string().max(500).nullable()).optional(), city:emptyToNull(z.string().max(100).nullable()).optional(), state:emptyToNull(z.string().max(100).nullable()).optional(), postalCode:emptyToNull(z.string().max(20).nullable()).optional(), isMain:z.boolean().default(false), status:z.enum(['active','inactive']).default('active') });
const classSchema = z.object({ name:z.string().trim().min(1).max(100), numericLevel:z.number().int().min(0).max(20).nullable().optional(), stream:z.string().max(100).default('General'), branchId:uuid.nullable().optional(), academicYearId:uuid.nullable().optional() });
const sectionSchema = z.object({ classId:uuid, name:z.string().trim().min(1).max(50), capacity:z.number().int().min(1).max(500).default(40), classTeacherId:uuid.nullable().optional() });
const subjectBaseSchema = z.object({ name:z.string().trim().min(2).max(100), code:z.string().trim().regex(/^[A-Z0-9_-]{2,50}$/), department:z.string().max(100).nullable().optional(), isElective:z.boolean().default(false), weeklyPeriods:z.number().int().min(1).max(20).default(1), passingMarks:z.number().min(0).default(33), maxMarks:z.number().positive().default(100) });
const subjectSchema = subjectBaseSchema.refine(v=>v.passingMarks<=v.maxMarks,{message:'Passing marks cannot exceed maximum marks'});
const assignmentSchema = z.object({ teacherId:uuid, subjectId:uuid, classId:uuid.nullable().optional(), academicYearId:uuid.nullable().optional(), isPrimary:z.boolean().default(false) });
const respond = (res:Response, req:Request, data:any, status=200) => res.status(status).json({data,requestId:req.id,timestamp:new Date().toISOString()});
const audit = (req:Request, action:string, entityId:string, details:Record<string,unknown>={}) => writeAudit({tenantId:req.tenantId!,userId:req.user.id,action,module:'master-data',entityId,details,request:req});
const ensureRef = async (table:'branches'|'academic_years'|'classes'|'staff'|'subjects', id:string|null|undefined, tenantId:string, label:string) => {
  if (!id) return;
  const result = await query(`SELECT id FROM ${table} WHERE id=$1 AND tenant_id=$2`,[id,tenantId]);
  if (!result.rowCount) throw new AppError(`${label} is outside this institution or does not exist.`,422,'INVALID_REFERENCE');
};

router.get('/profile',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query('SELECT * FROM tenants WHERE id=$1',[req.tenantId]);respond(res,req,r.rows[0]);}));
const handleProfileUpdate = asyncHandler(async(req:Request,res:Response)=>{const map:Record<string,string>={name:'name',email:'email',phone:'phone',website:'website',logoUrl:'logo_url',timezone:'timezone',addressLine1:'address_line_1',addressLine2:'address_line_2',city:'city',state:'state',postalCode:'postal_code',country:'country'};const entries=Object.entries(req.body).filter(([key])=>map[key]);if(!entries.length)throw new AppError('No profile fields supplied.',422,'VALIDATION_ERROR');const values=entries.map(([,v])=>v);const sets=entries.map(([k],i)=>`${map[k]}=$${i+1}`);values.push(req.tenantId);const r=await query(`UPDATE tenants SET ${sets.join(',')},updated_at=NOW() WHERE id=$${values.length} RETURNING *`,values);await audit(req,'SCHOOL_PROFILE_UPDATED',req.tenantId!,{fields:entries.map(([k])=>k)});respond(res,req,r.rows[0]);});
router.patch('/profile',requirePermission('master_data.manage'),validateBody(profileSchema),handleProfileUpdate);
router.put('/profile',requirePermission('master_data.manage'),validateBody(profileSchema),handleProfileUpdate);

router.get('/academic-years',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query('SELECT * FROM academic_years WHERE tenant_id=$1 ORDER BY start_date DESC',[req.tenantId]);respond(res,req,r.rows);}));
router.post('/academic-years',requirePermission('master_data.manage'),validateBody(yearSchema),asyncHandler(async(req,res)=>{const b=req.body;const row=await transaction(async c=>{if(b.isCurrent||b.status==='active')await c.query(`UPDATE academic_years SET is_current=false,status=CASE WHEN status='active' THEN 'closed' ELSE status END,updated_at=NOW() WHERE tenant_id=$1`,[req.tenantId]);return(await c.query(`INSERT INTO academic_years(tenant_id,name,start_date,end_date,is_current,status) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.tenantId,b.name,b.startDate,b.endDate,b.isCurrent||b.status==='active',b.status])).rows[0];});await audit(req,'ACADEMIC_YEAR_CREATED',row.id,{name:b.name});respond(res,req,row,201);}));
router.patch('/academic-years/:id',requirePermission('master_data.manage'),validateBody(yearBaseSchema.partial()),asyncHandler(async(req,res)=>{const b=req.body;if(b.isCurrent||b.status==='active')await query(`UPDATE academic_years SET is_current=false,status=CASE WHEN status='active' THEN 'closed' ELSE status END WHERE tenant_id=$1 AND id<>$2`,[req.tenantId,req.params.id]);const r=await query(`UPDATE academic_years SET name=COALESCE($1,name),start_date=COALESCE($2,start_date),end_date=COALESCE($3,end_date),status=COALESCE($4,status),is_current=COALESCE($5,is_current),updated_at=NOW() WHERE id=$6 AND tenant_id=$7 RETURNING *`,[b.name||null,b.startDate||null,b.endDate||null,b.status||null,b.isCurrent??null,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Academic year not found.',404,'NOT_FOUND');await audit(req,'ACADEMIC_YEAR_UPDATED',req.params.id);respond(res,req,r.rows[0]);}));

router.get('/branches',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query('SELECT * FROM branches WHERE tenant_id=$1 ORDER BY is_main DESC,name',[req.tenantId]);respond(res,req,r.rows);}));
router.post('/branches',requirePermission('master_data.manage'),validateBody(branchSchema),asyncHandler(async(req,res)=>{const b=req.body;const row=await transaction(async c=>{if(b.isMain)await c.query('UPDATE branches SET is_main=false WHERE tenant_id=$1',[req.tenantId]);return(await c.query(`INSERT INTO branches(tenant_id,name,code,email,phone,address_line_1,city,state,postal_code,is_main,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[req.tenantId,b.name,b.code,b.email||null,b.phone||null,b.addressLine1||null,b.city||null,b.state||null,b.postalCode||null,b.isMain,b.status])).rows[0];});await audit(req,'BRANCH_CREATED',row.id,{code:b.code});respond(res,req,row,201);}));
router.patch('/branches/:id',requirePermission('master_data.manage'),validateBody(branchSchema.partial()),asyncHandler(async(req,res)=>{const b=req.body;if(b.isMain)await query('UPDATE branches SET is_main=false WHERE tenant_id=$1 AND id<>$2',[req.tenantId,req.params.id]);const r=await query(`UPDATE branches SET name=COALESCE($1,name),code=COALESCE($2,code),email=COALESCE($3,email),phone=COALESCE($4,phone),city=COALESCE($5,city),state=COALESCE($6,state),is_main=COALESCE($7,is_main),status=COALESCE($8,status),updated_at=NOW() WHERE id=$9 AND tenant_id=$10 RETURNING *`,[b.name||null,b.code||null,b.email??null,b.phone??null,b.city??null,b.state??null,b.isMain??null,b.status||null,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Branch not found.',404,'NOT_FOUND');await audit(req,'BRANCH_UPDATED',req.params.id);respond(res,req,r.rows[0]);}));

router.get('/classes',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query(`SELECT c.*,b.name branch_name,a.name academic_year_name,(SELECT count(*)::int FROM sections s WHERE s.class_id=c.id) section_count FROM classes c LEFT JOIN branches b ON b.id=c.branch_id LEFT JOIN academic_years a ON a.id=c.academic_year_id WHERE c.tenant_id=$1 ORDER BY c.numeric_level NULLS LAST,c.name`,[req.tenantId]);respond(res,req,r.rows);}));
router.post('/classes',requirePermission('master_data.manage'),validateBody(classSchema),asyncHandler(async(req,res)=>{const b=req.body;await ensureRef('branches',b.branchId,req.tenantId!,'Branch');await ensureRef('academic_years',b.academicYearId,req.tenantId!,'Academic year');const r=await query(`INSERT INTO classes(tenant_id,name,numeric_level,stream,branch_id,academic_year_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.tenantId,b.name,b.numericLevel??null,b.stream,b.branchId||null,b.academicYearId||null]);await audit(req,'CLASS_CREATED',r.rows[0].id,{name:b.name});respond(res,req,r.rows[0],201);}));
router.patch('/classes/:id',requirePermission('master_data.manage'),validateBody(classSchema.partial()),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`UPDATE classes SET name=COALESCE($1,name),numeric_level=COALESCE($2,numeric_level),stream=COALESCE($3,stream),branch_id=COALESCE($4,branch_id),academic_year_id=COALESCE($5,academic_year_id),updated_at=NOW() WHERE id=$6 AND tenant_id=$7 RETURNING *`,[b.name||null,b.numericLevel??null,b.stream||null,b.branchId||null,b.academicYearId||null,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Class not found.',404,'NOT_FOUND');await audit(req,'CLASS_UPDATED',req.params.id);respond(res,req,r.rows[0]);}));

router.get('/sections',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query(`SELECT s.*,c.name class_name,st.name class_teacher_name FROM sections s JOIN classes c ON c.id=s.class_id LEFT JOIN staff st ON st.id=s.class_teacher_id WHERE s.tenant_id=$1 ORDER BY c.name,s.name`,[req.tenantId]);respond(res,req,r.rows);}));
router.post('/sections',requirePermission('master_data.manage'),validateBody(sectionSchema),asyncHandler(async(req,res)=>{const b=req.body;await ensureRef('classes',b.classId,req.tenantId!,'Class');await ensureRef('staff',b.classTeacherId,req.tenantId!,'Class teacher');const r=await query(`INSERT INTO sections(tenant_id,class_id,name,capacity,class_teacher_id) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.tenantId,b.classId,b.name,b.capacity,b.classTeacherId||null]);await audit(req,'SECTION_CREATED',r.rows[0].id,{classId:b.classId});respond(res,req,r.rows[0],201);}));
router.patch('/sections/:id',requirePermission('master_data.manage'),validateBody(sectionSchema.partial()),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`UPDATE sections SET class_id=COALESCE($1,class_id),name=COALESCE($2,name),capacity=COALESCE($3,capacity),class_teacher_id=COALESCE($4,class_teacher_id),updated_at=NOW() WHERE id=$5 AND tenant_id=$6 RETURNING *`,[b.classId||null,b.name||null,b.capacity??null,b.classTeacherId||null,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Section not found.',404,'NOT_FOUND');await audit(req,'SECTION_UPDATED',req.params.id);respond(res,req,r.rows[0]);}));

router.get('/subjects',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query('SELECT * FROM subjects WHERE tenant_id=$1 ORDER BY name',[req.tenantId]);respond(res,req,r.rows);}));
router.post('/subjects',requirePermission('master_data.manage'),validateBody(subjectSchema),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`INSERT INTO subjects(tenant_id,name,code,department,is_elective,weekly_periods,passing_marks,max_marks) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.tenantId,b.name,b.code,b.department||null,b.isElective,b.weeklyPeriods,b.passingMarks,b.maxMarks]);await audit(req,'SUBJECT_CREATED',r.rows[0].id,{code:b.code});respond(res,req,r.rows[0],201);}));
router.patch('/subjects/:id',requirePermission('master_data.manage'),validateBody(subjectBaseSchema.partial()),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`UPDATE subjects SET name=COALESCE($1,name),code=COALESCE($2,code),department=COALESCE($3,department),is_elective=COALESCE($4,is_elective),weekly_periods=COALESCE($5,weekly_periods),passing_marks=COALESCE($6,passing_marks),max_marks=COALESCE($7,max_marks),updated_at=NOW() WHERE id=$8 AND tenant_id=$9 RETURNING *`,[b.name||null,b.code||null,b.department??null,b.isElective??null,b.weeklyPeriods??null,b.passingMarks??null,b.maxMarks??null,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Subject not found.',404,'NOT_FOUND');await audit(req,'SUBJECT_UPDATED',req.params.id);respond(res,req,r.rows[0]);}));

router.get('/teacher-assignments',requirePermission('master_data.view'),asyncHandler(async(req,res)=>{const r=await query(`SELECT a.*,st.name teacher_name,s.name subject_name,c.name class_name,y.name academic_year_name FROM teacher_subject_assignments a JOIN staff st ON st.id=a.teacher_id JOIN subjects s ON s.id=a.subject_id LEFT JOIN classes c ON c.id=a.class_id LEFT JOIN academic_years y ON y.id=a.academic_year_id WHERE a.tenant_id=$1 ORDER BY st.name,s.name`,[req.tenantId]);respond(res,req,r.rows);}));
router.post('/teacher-assignments',requirePermission('master_data.manage'),validateBody(assignmentSchema),asyncHandler(async(req,res)=>{const b=req.body;await ensureRef('staff',b.teacherId,req.tenantId!,'Teacher');await ensureRef('subjects',b.subjectId,req.tenantId!,'Subject');await ensureRef('classes',b.classId,req.tenantId!,'Class');await ensureRef('academic_years',b.academicYearId,req.tenantId!,'Academic year');const r=await query(`INSERT INTO teacher_subject_assignments(tenant_id,teacher_id,subject_id,class_id,academic_year_id,is_primary) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.tenantId,b.teacherId,b.subjectId,b.classId||null,b.academicYearId||null,b.isPrimary]);await audit(req,'TEACHER_SUBJECT_ASSIGNED',r.rows[0].id,{teacherId:b.teacherId,subjectId:b.subjectId});respond(res,req,r.rows[0],201);}));
router.delete('/teacher-assignments/:id',requirePermission('master_data.manage'),asyncHandler(async(req,res)=>{const r=await query('DELETE FROM teacher_subject_assignments WHERE id=$1 AND tenant_id=$2 RETURNING id',[req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Assignment not found.',404,'NOT_FOUND');await audit(req,'TEACHER_SUBJECT_UNASSIGNED',req.params.id);respond(res,req,{success:true});}));

export default router;

