import { Router } from 'express';
import { z } from 'zod';
import { query,transaction } from '../db.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { tenantContext } from '../middleware/tenantContext.js';
import { requirePermission } from '../middleware/permission.js';
import { validateBody } from '../middleware/validation.js';
import { AppError } from '../middleware/errorHandler.js';

const router=Router();router.use(tenantContext(true),requirePermission('notifications.view_own'));
router.get('/',asyncHandler(async(req,res)=>{const limit=Math.min(Math.max(Number(req.query.limit)||30,1),100),offset=Math.max(Number(req.query.offset)||0,0);const r=await query(`SELECT n.id,n.event_type,n.title,n.message,n.priority,n.created_at,n.data,nr.read_at FROM notification_recipients nr JOIN notifications n ON n.id=nr.notification_id AND n.tenant_id=nr.tenant_id JOIN notification_jobs j ON j.recipient_id=nr.id AND j.channel='IN_APP' AND j.status IN ('SENT','DELIVERED') WHERE nr.tenant_id=$1 AND nr.user_id=$2 ORDER BY n.created_at DESC LIMIT $3 OFFSET $4`,[req.tenantId,req.user.id,limit,offset]);res.json({data:r.rows.map(x=>({id:x.id,eventType:x.event_type,title:x.title,message:x.message,priority:x.priority,createdAt:x.created_at,readAt:x.read_at,linkUrl:x.data?.link_url||null})),meta:{limit,offset},requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/unread-count',asyncHandler(async(req,res)=>{const r=await query(`SELECT COUNT(*)::int count FROM notification_recipients nr JOIN notification_jobs j ON j.recipient_id=nr.id AND j.channel='IN_APP' AND j.status IN ('SENT','DELIVERED') WHERE nr.tenant_id=$1 AND nr.user_id=$2 AND nr.read_at IS NULL`,[req.tenantId,req.user.id]);res.json({data:{count:r.rows[0].count},requestId:req.id,timestamp:new Date().toISOString()});}));
router.patch('/:id/read',asyncHandler(async(req,res)=>{const r=await query(`UPDATE notification_recipients nr SET read_at=COALESCE(read_at,NOW()) FROM notifications n WHERE nr.notification_id=n.id AND n.id=$1 AND nr.tenant_id=$2 AND nr.user_id=$3 RETURNING nr.read_at`,[req.params.id,req.tenantId,req.user.id]);if(!r.rowCount)throw new AppError('Notification not found.',404,'NOT_FOUND');res.json({data:{id:req.params.id,readAt:r.rows[0].read_at},requestId:req.id,timestamp:new Date().toISOString()});}));
router.post('/read-all',asyncHandler(async(req,res)=>{const r=await query(`UPDATE notification_recipients SET read_at=NOW() WHERE tenant_id=$1 AND user_id=$2 AND read_at IS NULL`,[req.tenantId,req.user.id]);res.json({data:{updated:r.rowCount||0},requestId:req.id,timestamp:new Date().toISOString()});}));
router.get('/preferences',asyncHandler(async(req,res)=>{const events=await query(`SELECT DISTINCT code event_type,category FROM notification_templates WHERE is_active=true AND (tenant_id=$1 OR tenant_id IS NULL) ORDER BY code`,[req.tenantId]);const prefs=await query(`SELECT event_type,channel,is_enabled FROM notification_preferences WHERE tenant_id=$1 AND user_id=$2`,[req.tenantId,req.user.id]);res.json({data:{events:events.rows,preferences:prefs.rows},requestId:req.id,timestamp:new Date().toISOString()});}));
router.put('/preferences',validateBody(z.object({eventType:z.string().regex(/^[A-Z0-9_]+$/),channel:z.enum(['IN_APP','EMAIL']),isEnabled:z.boolean()})),asyncHandler(async(req,res)=>{const template=await query(`SELECT category FROM notification_templates WHERE code=$1 AND channel=$2 AND is_active=true AND (tenant_id=$3 OR tenant_id IS NULL) ORDER BY (tenant_id IS NOT NULL) DESC LIMIT 1`,[req.body.eventType,req.body.channel,req.tenantId]);if(!template.rowCount)throw new AppError('Notification preference is not available.',404,'NOT_FOUND');if(template.rows[0].category!=='OPTIONAL'&&!req.body.isEnabled)throw new AppError('Transactional and security notifications cannot be disabled.',422,'MANDATORY_NOTIFICATION');const r=await query(`INSERT INTO notification_preferences(tenant_id,user_id,event_type,channel,is_enabled) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,user_id,event_type,channel) DO UPDATE SET is_enabled=EXCLUDED.is_enabled,updated_at=NOW() RETURNING event_type,channel,is_enabled`,[req.tenantId,req.user.id,req.body.eventType,req.body.channel,req.body.isEnabled]);res.json({data:r.rows[0],requestId:req.id,timestamp:new Date().toISOString()});}));
export default router;
