import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { query, transaction } from '../db.js';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { tenantContext } from '../middleware/tenantContext.js';
import { requirePermission } from '../middleware/permission.js';
import { validateBody } from '../middleware/validation.js';
import { AppError } from '../middleware/errorHandler.js';
import { writeAudit } from '../services/auditService.js';

const router=Router();router.use(tenantContext(true));const uuid=z.string().uuid();
const identity=z.object({admissionNo:z.string().trim().min(1).max(100),firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().max(100).default(''),gender:z.enum(['MALE','FEMALE','OTHER']),dob:z.string().date().nullable().optional(),email:z.string().email().nullable().optional(),phone:z.string().max(50).nullable().optional(),photoUrl:z.string().url().nullable().optional(),address:z.string().max(1000).nullable().optional(),status:z.enum(['ACTIVE','INACTIVE','ALUMNI','TRANSFERRED','ARCHIVED']).default('ACTIVE'),admissionDate:z.string().date().optional(),bloodGroup:z.string().max(10).nullable().optional(),nationality:z.string().max(100).optional(),notes:z.string().max(2000).nullable().optional()});
const enrollment=z.object({academicYearId:uuid,classId:uuid,sectionId:uuid,rollNo:z.string().max(50).nullable().optional(),status:z.enum(['enrolled','completed','withdrawn','transferred']).default('enrolled'),startDate:z.string().date().optional(),endDate:z.string().date().nullable().optional(),remarks:z.string().max(1000).nullable().optional()});
const parent=z.object({firstName:z.string().trim().min(1).max(100),lastName:z.string().trim().max(100).default(''),phone:z.string().trim().min(5).max(50),email:z.string().email().nullable().optional(),relation:z.string().max(50).default('GUARDIAN'),occupation:z.string().max(150).nullable().optional(),address:z.string().max(1000).nullable().optional()});
const relationship=z.object({parentId:uuid.optional(),parent:parent.optional(),relationshipType:z.string().max(30).default('GUARDIAN'),isPrimary:z.boolean().default(false),canPickup:z.boolean().default(true),receivesNotifications:z.boolean().default(true)}).refine(v=>v.parentId||v.parent,'parentId or parent is required');
const admission=identity.extend({enrollment,guardian:parent.extend({relationshipType:z.string().max(30).default('GUARDIAN'),isPrimary:z.boolean().default(true),canPickup:z.boolean().default(true),receivesNotifications:z.boolean().default(true)}).optional()});
const documentSchema=z.object({documentType:z.string().trim().min(1).max(50),fileName:z.string().trim().min(1).max(255),storageKey:z.string().trim().min(1).max(1000),mimeType:z.string().trim().min(1).max(100),sizeBytes:z.number().int().nonnegative(),notes:z.string().max(1000).nullable().optional()});
const respond=(res:Response,req:Request,data:any,status=200,meta?:any)=>res.status(status).json({data,...(meta?{meta}:{}),requestId:req.id,timestamp:new Date().toISOString()});
const audit=(req:Request,action:string,entityId:string,details:Record<string,unknown>={},client?:any)=>writeAudit({tenantId:req.tenantId!,userId:req.user.id,action,module:'students',entityId,details,request:req},client);
async function validatePlacement(client:any,tenantId:string,e:any){const r=await client.query(`SELECT 1 FROM academic_years y JOIN classes c ON c.id=$2 AND c.tenant_id=y.tenant_id JOIN sections s ON s.id=$3 AND s.class_id=c.id AND s.tenant_id=c.tenant_id WHERE y.id=$1 AND y.tenant_id=$4`,[e.academicYearId,e.classId,e.sectionId,tenantId]);if(!r.rowCount)throw new AppError('Academic year, class, and section must belong to this institution and each other.',422,'INVALID_PLACEMENT');}

router.get('/',requirePermission('student_lifecycle.view'),asyncHandler(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),pageSize=Math.min(100,Math.max(1,Number(req.query.pageSize)||25)),offset=(page-1)*pageSize;const search=typeof req.query.search==='string'?req.query.search.trim():'';const status=typeof req.query.status==='string'?req.query.status:null;const classId=typeof req.query.classId==='string'?req.query.classId:null;const yearId=typeof req.query.academicYearId==='string'?req.query.academicYearId:null;const params=[req.tenantId,search?`%${search.toLowerCase()}%`:null,status,classId,yearId];const where=`s.tenant_id=$1 AND ($2::text IS NULL OR lower(s.first_name||' '||s.last_name) LIKE $2 OR lower(s.admission_no) LIKE $2 OR lower(COALESCE(s.email,'')) LIKE $2 OR s.phone LIKE $2) AND ($3::text IS NULL OR s.status=$3) AND ($4::uuid IS NULL OR e.class_id=$4) AND ($5::uuid IS NULL OR e.academic_year_id=$5)`;const count=await query(`SELECT count(DISTINCT s.id)::int total FROM students s LEFT JOIN enrollments e ON e.student_id=s.id AND e.tenant_id=s.tenant_id WHERE ${where}`,params);const rows=await query(`SELECT s.id,s.admission_no,s.first_name,s.last_name,s.gender,s.dob,s.email,s.phone,s.photo_url,s.status,s.admission_date,s.blood_group,s.nationality,s.created_at,e.id enrollment_id,e.roll_no,e.status enrollment_status,y.id academic_year_id,y.name academic_year_name,c.id class_id,c.name class_name,sec.id section_id,sec.name section_name FROM students s LEFT JOIN LATERAL(SELECT * FROM enrollments x WHERE x.student_id=s.id AND x.tenant_id=s.tenant_id ORDER BY (x.status='enrolled') DESC,x.start_date DESC,x.created_at DESC LIMIT 1)e ON true LEFT JOIN academic_years y ON y.id=e.academic_year_id LEFT JOIN classes c ON c.id=e.class_id LEFT JOIN sections sec ON sec.id=e.section_id WHERE ${where} ORDER BY s.created_at DESC LIMIT $6 OFFSET $7`,[...params,pageSize,offset]);respond(res,req,rows.rows,200,{page,pageSize,total:count.rows[0].total,totalPages:Math.ceil(count.rows[0].total/pageSize)});}));

router.post('/admissions',requirePermission('student_lifecycle.manage'),validateBody(admission),asyncHandler(async(req,res)=>{const b=req.body;const result=await transaction(async client=>{await validatePlacement(client,req.tenantId!,b.enrollment);const student=(await client.query(`INSERT INTO students(tenant_id,admission_no,first_name,last_name,gender,dob,email,phone,photo_url,address,status,admission_date,blood_group,nationality,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,COALESCE($12,CURRENT_DATE),$13,$14,$15) RETURNING *`,[req.tenantId,b.admissionNo,b.firstName,b.lastName,b.gender,b.dob||null,b.email||null,b.phone||null,b.photoUrl||null,b.address||null,b.status,b.admissionDate||null,b.bloodGroup||null,b.nationality||'Indian',b.notes||null])).rows[0];const enr=(await client.query(`INSERT INTO enrollments(tenant_id,student_id,academic_year_id,class_id,section_id,roll_no,status,start_date,end_date,remarks) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,CURRENT_DATE),$9,$10) RETURNING *`,[req.tenantId,student.id,b.enrollment.academicYearId,b.enrollment.classId,b.enrollment.sectionId,b.enrollment.rollNo||null,b.enrollment.status,b.enrollment.startDate||null,b.enrollment.endDate||null,b.enrollment.remarks||null])).rows[0];let guardian=null;if(b.guardian){guardian=(await client.query(`INSERT INTO parents(tenant_id,first_name,last_name,phone,email,relation,occupation,address) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.tenantId,b.guardian.firstName,b.guardian.lastName,b.guardian.phone,b.guardian.email||null,b.guardian.relation,b.guardian.occupation||null,b.guardian.address||null])).rows[0];await client.query(`INSERT INTO parent_students(tenant_id,parent_id,student_id,is_primary,relationship_type,can_pickup,receives_notifications) VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.tenantId,guardian.id,student.id,b.guardian.isPrimary,b.guardian.relationshipType,b.guardian.canPickup,b.guardian.receivesNotifications]);}await audit(req,'STUDENT_ADMITTED',student.id,{admissionNo:b.admissionNo,enrollmentId:enr.id,guardianId:guardian?.id},client);return{student,enrollment:enr,guardian};});respond(res,req,result,201);}));

router.get('/:id',requirePermission('student_lifecycle.view'),asyncHandler(async(req,res)=>{const s=await query('SELECT * FROM students WHERE id=$1 AND tenant_id=$2',[req.params.id,req.tenantId]);if(!s.rowCount)throw new AppError('Student not found.',404,'NOT_FOUND');const [parents,enrollments,documents]=await Promise.all([query(`SELECT p.*,ps.relationship_type,ps.is_primary,ps.can_pickup,ps.receives_notifications FROM parent_students ps JOIN parents p ON p.id=ps.parent_id WHERE ps.student_id=$1 AND ps.tenant_id=$2 ORDER BY ps.is_primary DESC,p.first_name`,[req.params.id,req.tenantId]),query(`SELECT e.*,y.name academic_year_name,c.name class_name,sec.name section_name FROM enrollments e LEFT JOIN academic_years y ON y.id=e.academic_year_id JOIN classes c ON c.id=e.class_id JOIN sections sec ON sec.id=e.section_id WHERE e.student_id=$1 AND e.tenant_id=$2 ORDER BY y.start_date DESC,e.start_date DESC`,[req.params.id,req.tenantId]),query('SELECT * FROM student_documents WHERE student_id=$1 AND tenant_id=$2 ORDER BY created_at DESC',[req.params.id,req.tenantId])]);respond(res,req,{student:s.rows[0],parents:parents.rows,enrollments:enrollments.rows,documents:documents.rows});}));

router.patch('/:id',requirePermission('student_lifecycle.manage'),validateBody(identity.partial().omit({admissionNo:true})),asyncHandler(async(req,res)=>{const map:Record<string,string>={firstName:'first_name',lastName:'last_name',gender:'gender',dob:'dob',email:'email',phone:'phone',photoUrl:'photo_url',address:'address',status:'status',admissionDate:'admission_date',bloodGroup:'blood_group',nationality:'nationality',notes:'notes'};const entries=Object.entries(req.body).filter(([k])=>map[k]);if(!entries.length)throw new AppError('No identity fields supplied.',422,'VALIDATION_ERROR');const values=entries.map(([,v])=>v);values.push(req.params.id,req.tenantId);const r=await query(`UPDATE students SET ${entries.map(([k],i)=>`${map[k]}=$${i+1}`).join(',')},updated_at=NOW() WHERE id=$${values.length-1} AND tenant_id=$${values.length} RETURNING *`,values);if(!r.rowCount)throw new AppError('Student not found.',404,'NOT_FOUND');await audit(req,'STUDENT_PROFILE_UPDATED',req.params.id,{fields:entries.map(([k])=>k)});respond(res,req,r.rows[0]);}));

router.post('/:id/parents',requirePermission('student_lifecycle.manage'),validateBody(relationship),asyncHandler(async(req,res)=>{const b=req.body;const row=await transaction(async client=>{const student=await client.query('SELECT id FROM students WHERE id=$1 AND tenant_id=$2',[req.params.id,req.tenantId]);if(!student.rowCount)throw new AppError('Student not found.',404,'NOT_FOUND');let parentId=b.parentId;if(parentId){const found=await client.query('SELECT id FROM parents WHERE id=$1 AND tenant_id=$2',[parentId,req.tenantId]);if(!found.rowCount)throw new AppError('Parent not found.',404,'NOT_FOUND');}else{const p=b.parent;parentId=(await client.query(`INSERT INTO parents(tenant_id,first_name,last_name,phone,email,relation,occupation,address) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[req.tenantId,p.firstName,p.lastName,p.phone,p.email||null,p.relation,p.occupation||null,p.address||null])).rows[0].id;}if(b.isPrimary)await client.query('UPDATE parent_students SET is_primary=false WHERE student_id=$1 AND tenant_id=$2',[req.params.id,req.tenantId]);const rel=(await client.query(`INSERT INTO parent_students(tenant_id,parent_id,student_id,is_primary,relationship_type,can_pickup,receives_notifications) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.tenantId,parentId,req.params.id,b.isPrimary,b.relationshipType,b.canPickup,b.receivesNotifications])).rows[0];await audit(req,'STUDENT_PARENT_LINKED',req.params.id,{parentId},client);return rel;});respond(res,req,row,201);}));
router.patch('/parents/:parentId',requirePermission('student_lifecycle.manage'),validateBody(parent.partial()),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`UPDATE parents SET first_name=COALESCE($1,first_name),last_name=COALESCE($2,last_name),phone=COALESCE($3,phone),email=COALESCE($4,email),relation=COALESCE($5,relation),occupation=COALESCE($6,occupation),address=COALESCE($7,address),updated_at=NOW() WHERE id=$8 AND tenant_id=$9 RETURNING *`,[b.firstName||null,b.lastName||null,b.phone||null,b.email??null,b.relation||null,b.occupation??null,b.address??null,req.params.parentId,req.tenantId]);if(!r.rowCount)throw new AppError('Parent not found.',404,'NOT_FOUND');await audit(req,'PARENT_UPDATED',req.params.parentId);respond(res,req,r.rows[0]);}));

router.post('/:id/enrollments',requirePermission('student_lifecycle.manage'),validateBody(enrollment),asyncHandler(async(req,res)=>{const b=req.body;const row=await transaction(async client=>{const student=await client.query('SELECT id FROM students WHERE id=$1 AND tenant_id=$2',[req.params.id,req.tenantId]);if(!student.rowCount)throw new AppError('Student not found.',404,'NOT_FOUND');await validatePlacement(client,req.tenantId!,b);await client.query(`UPDATE enrollments SET status='completed',end_date=COALESCE(end_date,CURRENT_DATE) WHERE student_id=$1 AND tenant_id=$2 AND status='enrolled'`,[req.params.id,req.tenantId]);const r=await client.query(`INSERT INTO enrollments(tenant_id,student_id,academic_year_id,class_id,section_id,roll_no,status,start_date,end_date,remarks) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,CURRENT_DATE),$9,$10) RETURNING *`,[req.tenantId,req.params.id,b.academicYearId,b.classId,b.sectionId,b.rollNo||null,b.status,b.startDate||null,b.endDate||null,b.remarks||null]);await audit(req,'STUDENT_ENROLLED',req.params.id,{enrollmentId:r.rows[0].id,academicYearId:b.academicYearId},client);return r.rows[0];});respond(res,req,row,201);}));

router.post('/:id/documents',requirePermission('student_documents.manage'),validateBody(documentSchema),asyncHandler(async(req,res)=>{const b=req.body;const r=await query(`INSERT INTO student_documents(tenant_id,student_id,document_type,file_name,storage_key,mime_type,size_bytes,notes,uploaded_by) SELECT $1,s.id,$3,$4,$5,$6,$7,$8,$9 FROM students s WHERE s.id=$2 AND s.tenant_id=$1 RETURNING *`,[req.tenantId,req.params.id,b.documentType,b.fileName,b.storageKey,b.mimeType,b.sizeBytes,b.notes||null,req.user.id]);if(!r.rowCount)throw new AppError('Student not found.',404,'NOT_FOUND');await audit(req,'STUDENT_DOCUMENT_ADDED',r.rows[0].id,{studentId:req.params.id,documentType:b.documentType});respond(res,req,r.rows[0],201);}));
router.delete('/:id/documents/:documentId',requirePermission('student_documents.manage'),asyncHandler(async(req,res)=>{const r=await query('DELETE FROM student_documents WHERE id=$1 AND student_id=$2 AND tenant_id=$3 RETURNING id,storage_key',[req.params.documentId,req.params.id,req.tenantId]);if(!r.rowCount)throw new AppError('Document not found.',404,'NOT_FOUND');await audit(req,'STUDENT_DOCUMENT_REMOVED',req.params.documentId,{studentId:req.params.id,storageKey:r.rows[0].storage_key});respond(res,req,{success:true});}));

export default router;
