import{Router}from'express';import{z}from'zod';import{query,transaction}from'../db.js';import{tenantContext}from'../middleware/tenantContext.js';import{requirePermission}from'../middleware/permission.js';import{asyncHandler}from'../middleware/asyncHandler.js';import{validateBody}from'../middleware/validation.js';import{AppError}from'../middleware/errorHandler.js';import{id,text,state,validateId,logOperation,operationError}from'./operationsSupport.js';
const router=Router();router.use(tenantContext(true));
const vehicle=z.object({registrationNumber:z.string().trim().min(1).max(50),vehicleType:z.string().trim().min(1).max(50),capacity:z.number().int().min(1).max(500),driverId:id.optional().nullable(),status:state.default('ACTIVE'),insuranceUntil:z.string().date().optional().nullable(),permitUntil:z.string().date().optional().nullable()});
router.get('/',requirePermission('transport.view'),asyncHandler(async(req,res)=>{const t=req.tenantId;const[vehicles,routes,stops,assignments,staff,enrollments]=await Promise.all([
 query(`SELECT v.*,v.registration_number name,s.name driver_name,(SELECT COUNT(*)::int FROM student_transport_assignments a JOIN transport_routes r ON r.id=a.route_id AND r.tenant_id=a.tenant_id WHERE r.vehicle_id=v.id AND a.ended_at IS NULL) occupancy FROM transport_vehicles v LEFT JOIN staff s ON s.id=v.driver_id AND s.tenant_id=v.tenant_id WHERE v.tenant_id=$1 ORDER BY v.registration_number`,[t]),query(`SELECT r.id,r.route_name name,r.operational_status status,r.vehicle_id,v.registration_number vehicle FROM transport_routes r LEFT JOIN transport_vehicles v ON v.id=r.vehicle_id AND v.tenant_id=r.tenant_id WHERE r.tenant_id=$1 ORDER BY r.route_name`,[t]),query(`SELECT s.*,r.route_name route_name,s.name||' · '||r.route_name name FROM route_stops s JOIN transport_routes r ON r.id=s.route_id AND r.tenant_id=s.tenant_id WHERE s.tenant_id=$1 ORDER BY r.route_name,s.sequence`,[t]),
 query(`SELECT a.*,s.first_name||' '||s.last_name student_name,r.route_name,st.name stop_name FROM student_transport_assignments a JOIN enrollments e ON e.id=a.enrollment_id AND e.tenant_id=a.tenant_id JOIN students s ON s.id=e.student_id AND s.tenant_id=e.tenant_id JOIN transport_routes r ON r.id=a.route_id AND r.tenant_id=a.tenant_id JOIN route_stops st ON st.id=a.stop_id AND st.tenant_id=a.tenant_id WHERE a.tenant_id=$1 ORDER BY a.assigned_at DESC`,[t]),query(`SELECT id,name FROM staff WHERE tenant_id=$1 AND status='ACTIVE' ORDER BY name`,[t]),query(`SELECT e.id,s.first_name||' '||s.last_name||' · '||y.name name FROM enrollments e JOIN students s ON s.id=e.student_id AND s.tenant_id=e.tenant_id JOIN academic_years y ON y.id=e.academic_year_id AND y.tenant_id=e.tenant_id WHERE e.tenant_id=$1 AND e.status='enrolled' ORDER BY s.first_name`,[t])]);res.json({data:{vehicles:vehicles.rows,routes:routes.rows,stops:stops.rows,assignments:assignments.rows,staff:staff.rows,enrollments:enrollments.rows}});
}));
router.post('/vehicles',requirePermission('transport.manage'),validateBody(vehicle),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{if(b.driverId&&!(await c.query(`SELECT 1 FROM staff WHERE id=$1 AND tenant_id=$2 AND status='ACTIVE'`,[b.driverId,req.tenantId])).rowCount)throw new AppError('Active staff driver not found.',422,'INVALID_DRIVER');const r=(await c.query(`INSERT INTO transport_vehicles(tenant_id,registration_number,vehicle_type,capacity,driver_id,status,insurance_until,permit_until) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[req.tenantId,b.registrationNumber,b.vehicleType,b.capacity,b.driverId||null,b.status,b.insuranceUntil||null,b.permitUntil||null])).rows[0];await logOperation(req,c,'transport','VEHICLE_CREATED',r.id);return r;});res.status(201).json({data});}));
router.patch('/vehicles/:id',validateId,requirePermission('transport.manage'),validateBody(vehicle.partial()),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{const old=(await c.query('SELECT * FROM transport_vehicles WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,req.tenantId])).rows[0];if(!old)throw new AppError('Vehicle not found.',404,'NOT_FOUND');const count=Number((await c.query(`SELECT COUNT(*) n FROM student_transport_assignments a JOIN transport_routes r ON r.id=a.route_id AND r.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND r.vehicle_id=$2 AND a.ended_at IS NULL`,[req.tenantId,old.id])).rows[0].n);if((b.capacity??old.capacity)<count||((b.status&&b.status!=='ACTIVE')||b.driverId===null)&&count>0)throw new AppError('Vehicle has active assignments; capacity and active driver must be preserved.',409,'VEHICLE_OCCUPIED');if(b.driverId&&!(await c.query(`SELECT 1 FROM staff WHERE id=$1 AND tenant_id=$2 AND status='ACTIVE'`,[b.driverId,req.tenantId])).rowCount)throw new AppError('Active staff driver not found.',422,'INVALID_DRIVER');const r=(await c.query(`UPDATE transport_vehicles SET registration_number=$3,vehicle_type=$4,capacity=$5,driver_id=$6,status=$7,insurance_until=$8,permit_until=$9 WHERE id=$1 AND tenant_id=$2 RETURNING *`,[old.id,req.tenantId,b.registrationNumber??old.registration_number,b.vehicleType??old.vehicle_type,b.capacity??old.capacity,b.driverId===undefined?old.driver_id:b.driverId,b.status??old.status,b.insuranceUntil===undefined?old.insurance_until:b.insuranceUntil,b.permitUntil===undefined?old.permit_until:b.permitUntil])).rows[0];await logOperation(req,c,'transport','VEHICLE_UPDATED',r.id,b);return r;});res.json({data});}));
router.post('/routes',requirePermission('transport.manage'),validateBody(z.object({name:z.string().trim().min(2).max(100),vehicleId:id})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const v=(await c.query(`SELECT * FROM transport_vehicles WHERE id=$1 AND tenant_id=$2 AND status='ACTIVE' FOR UPDATE`,[req.body.vehicleId,req.tenantId])).rows[0];if(!v)throw new AppError('Active vehicle not found.',422,'INVALID_REFERENCE');const r=(await c.query(`INSERT INTO transport_routes(tenant_id,route_name,vehicle_number,driver_name,vehicle_id,operational_status) VALUES($1,$2,$3,'',$4,'ACTIVE') RETURNING *`,[req.tenantId,req.body.name,v.registration_number,v.id])).rows[0];await logOperation(req,c,'transport','ROUTE_CREATED',r.id);return r;});res.status(201).json({data});}));
router.patch('/routes/:id',validateId,requirePermission('transport.manage'),validateBody(z.object({name:z.string().trim().min(2).max(100).optional(),status:state.optional(),vehicleId:id.optional()})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{
 const initial=(await c.query('SELECT vehicle_id FROM transport_routes WHERE id=$1 AND tenant_id=$2',[req.params.id,req.tenantId])).rows[0];if(!initial)throw new AppError('Route not found.',404,'NOT_FOUND');
 const vehicleId=req.body.vehicleId??initial.vehicle_id;const locked=await c.query('SELECT * FROM transport_vehicles WHERE tenant_id=$1 AND id=ANY($2::uuid[]) ORDER BY id FOR UPDATE',[req.tenantId,[initial.vehicle_id,vehicleId].filter(Boolean)]);const v=locked.rows.find(x=>x.id===vehicleId);if(!v)throw new AppError('Vehicle not found.',422,'INVALID_REFERENCE');
 const old=(await c.query('SELECT * FROM transport_routes WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,req.tenantId])).rows[0];if(old.vehicle_id!==initial.vehicle_id)throw new AppError('Route changed. Retry.',409,'CONCURRENT_CHANGE');
 const occupants=Number((await c.query('SELECT COUNT(*) n FROM student_transport_assignments WHERE tenant_id=$1 AND route_id=$2 AND ended_at IS NULL',[req.tenantId,old.id])).rows[0].n);
 if(req.body.status&&req.body.status!=='ACTIVE'&&occupants)throw new AppError('End active assignments before archiving a route.',409,'ROUTE_OCCUPIED');
 const total=Number((await c.query(`SELECT COUNT(*) n FROM student_transport_assignments a JOIN transport_routes r ON r.id=a.route_id AND r.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND r.vehicle_id=$2 AND a.route_id<>$3 AND a.ended_at IS NULL`,[req.tenantId,vehicleId,old.id])).rows[0].n);
 if(total+occupants>v.capacity||(occupants>0&&(v.status!=='ACTIVE'||!v.driver_id)))throw new AppError('Vehicle capacity or active driver required.',409,'VEHICLE_CAPACITY');
 const r=(await c.query('UPDATE transport_routes SET route_name=$3,operational_status=$4,vehicle_id=$5 WHERE id=$1 AND tenant_id=$2 RETURNING *',[old.id,req.tenantId,req.body.name??old.route_name,req.body.status??old.operational_status,vehicleId])).rows[0];await logOperation(req,c,'transport','ROUTE_UPDATED',r.id,req.body);return r;
 });res.json({data});}));
router.post('/stops',requirePermission('transport.manage'),validateBody(z.object({routeId:id,name:text,sequence:z.number().int().min(1).max(1000)})),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{if(!(await c.query(`SELECT 1 FROM transport_routes WHERE id=$1 AND tenant_id=$2 AND operational_status='ACTIVE'`,[req.body.routeId,req.tenantId])).rowCount)throw new AppError('Active route not found.',422,'INVALID_REFERENCE');const r=(await c.query('INSERT INTO route_stops(tenant_id,route_id,name,sequence) VALUES($1,$2,$3,$4) RETURNING *',[req.tenantId,req.body.routeId,req.body.name,req.body.sequence])).rows[0];await logOperation(req,c,'transport','ROUTE_STOP_CREATED',r.id);return r;});res.status(201).json({data});}));
router.post('/assignments',requirePermission('transport.manage'),validateBody(z.object({enrollmentId:id,routeId:id,stopId:id})),asyncHandler(async(req,res)=>{const b=req.body;const data=await transaction(async c=>{
 const initial=(await c.query('SELECT vehicle_id FROM transport_routes WHERE id=$1 AND tenant_id=$2',[b.routeId,req.tenantId])).rows[0];if(!initial?.vehicle_id)throw new AppError('Route vehicle not found.',422,'INVALID_REFERENCE');
 const v=(await c.query(`SELECT v.* FROM transport_vehicles v JOIN staff s ON s.id=v.driver_id AND s.tenant_id=v.tenant_id WHERE v.id=$1 AND v.tenant_id=$2 AND v.status='ACTIVE' AND s.status='ACTIVE' FOR UPDATE OF v`,[initial.vehicle_id,req.tenantId])).rows[0];if(!v)throw new AppError('An active vehicle and staff driver are required.',422,'INVALID_DRIVER');
 const route=(await c.query(`SELECT * FROM transport_routes WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[b.routeId,req.tenantId])).rows[0];if(route.vehicle_id!==v.id||route.operational_status!=='ACTIVE')throw new AppError('Route unavailable or changed. Retry.',409,'CONCURRENT_CHANGE');
 if(!(await c.query(`SELECT id FROM enrollments WHERE id=$1 AND tenant_id=$2 AND status='enrolled' FOR UPDATE`,[b.enrollmentId,req.tenantId])).rowCount||!(await c.query('SELECT 1 FROM route_stops WHERE id=$1 AND route_id=$2 AND tenant_id=$3',[b.stopId,b.routeId,req.tenantId])).rowCount)throw new AppError('Enrollment or matching route stop not found.',422,'INVALID_REFERENCE');
 if((await c.query('SELECT 1 FROM student_transport_assignments WHERE enrollment_id=$1 AND ended_at IS NULL',[b.enrollmentId])).rowCount)throw new AppError('Enrollment already has transport.',409,'ALREADY_ASSIGNED');
 const count=Number((await c.query(`SELECT COUNT(*) n FROM student_transport_assignments a JOIN transport_routes r ON r.id=a.route_id AND r.tenant_id=a.tenant_id WHERE a.tenant_id=$1 AND r.vehicle_id=$2 AND a.ended_at IS NULL`,[req.tenantId,v.id])).rows[0].n);if(count>=v.capacity)throw new AppError('Vehicle capacity reached.',409,'VEHICLE_CAPACITY');
 const r=(await c.query('INSERT INTO student_transport_assignments(tenant_id,enrollment_id,route_id,stop_id) VALUES($1,$2,$3,$4) RETURNING *',[req.tenantId,b.enrollmentId,b.routeId,b.stopId])).rows[0];await logOperation(req,c,'transport','TRANSPORT_ASSIGNED',r.id);return r;
 });res.status(201).json({data});
}));
router.post('/assignments/:id/end',validateId,requirePermission('transport.manage'),asyncHandler(async(req,res)=>{const data=await transaction(async c=>{const r=(await c.query('UPDATE student_transport_assignments SET ended_at=NOW() WHERE id=$1 AND tenant_id=$2 AND ended_at IS NULL RETURNING *',[req.params.id,req.tenantId])).rows[0];if(!r)throw new AppError('Active assignment not found.',404,'NOT_FOUND');await logOperation(req,c,'transport','TRANSPORT_ASSIGNMENT_ENDED',r.id);return r;});res.json({data});}));
router.use((_req,_res,next)=>next(new AppError('Transport endpoint not found.',404,'NOT_FOUND')));router.use(operationError);export default router;
