import React, { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useTenant } from '../../context/TenantContext';
import { apiClient } from '../../services/api/apiClient';
import { Button } from '../../components/ui/Button';
import type { Permission } from '../../types';
export type Field = { name:string;label:string;type?:'text'|'number'|'date'|'select';source?:string;options?:string[];min?:number;optional?:boolean };
export type OperationForm = { title:string;path:string|((body:any)=>string);method?:'POST'|'PATCH';permission:Permission;fields:Field[];transform?:(body:any)=>any };
export type OperationTable = { title:string;source:string;columns:Record<string,string>;action?:{label:string;permission:Permission;path:(row:any)=>string;method?:'POST'|'PATCH';body?:(row:any)=>any;show?:(row:any)=>boolean} };
export const OperationsWorkbench:React.FC<{title:string;module:string;forms:OperationForm[];tables:OperationTable[];note?:string}>=({title,module,forms,tables,note})=>{
 const{currentTenant}=useTenant();const{can}=useAuth();const[data,setData]=useState<Record<string,any[]>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const load=async()=>{setBusy(true);try{setData((await apiClient.request<any>(`/api/v1/${module}`,{tenantId:currentTenant.id})).data);}catch(e:any){setMessage(e.message||'Unable to load records.');}finally{setBusy(false);}};
 useEffect(()=>{setData({});setMessage('');void load();},[currentTenant.id,module]);
 const save=async(path:string,body:any,method:'POST'|'PATCH'='POST')=>{await apiClient.request(`/api/v1/${module}${path}`,{tenantId:currentTenant.id,method,body});await load();};
 const submit=async(e:React.FormEvent<HTMLFormElement>,form:OperationForm)=>{e.preventDefault();const element=e.currentTarget;let body:any=Object.fromEntries(new FormData(element));for(const f of form.fields){if(f.type==='number')body[f.name]=Number(body[f.name]);if(f.optional&&!body[f.name])delete body[f.name];}setBusy(true);setMessage('');try{await save(typeof form.path==='function'?form.path(body):form.path,form.transform?form.transform(body):body,form.method);element.reset();setMessage('Saved.');}catch(e:any){setMessage(e.message||'Unable to save.');}finally{setBusy(false);}};
 const run=async(table:OperationTable,row:any)=>{setBusy(true);try{await save(table.action!.path(row),table.action!.body?.(row)||{},table.action!.method);setMessage('Saved.');}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
 const input='w-full rounded-lg border border-slate-200 p-2 text-sm';
 return <div className="space-y-5"><div className="flex justify-between"><h2 className="text-2xl font-bold">{title}</h2><Button disabled={busy} onClick={()=>void load()}>Refresh</Button></div>{note&&<p className="text-sm text-slate-500">{note}</p>}{message&&<p role="status" className="border rounded-lg p-3">{message}</p>}
 <div className="grid lg:grid-cols-2 gap-4">{forms.filter(f=>can(f.permission)).map(f=><section key={f.title} className="bg-white rounded-xl border p-4"><h3 className="font-semibold mb-3">{f.title}</h3><form onSubmit={e=>void submit(e,f)} className="space-y-3">{f.fields.map(field=><label key={field.name} className="block text-sm">{field.label}{field.type==='select'?<select name={field.name} required={!field.optional} className={input}><option value="">Select {field.label.toLowerCase()}</option>{field.options?field.options.map(x=><option key={x}>{x}</option>):(data[field.source||'']||[]).map(x=><option key={x.id} value={x.id}>{x.name||x.title||x.accession_number||x.employee_id||x.id}{x.availability?` · ${x.availability}`:''}{x.student_name?` · ${x.student_name}`:''}</option>)}</select>:<input name={field.name} type={field.type||'text'} required={!field.optional} min={field.min} step={field.type==='number'?'1':undefined} maxLength={2000} className={input}/>}</label>)}<Button disabled={busy}>Save</Button></form></section>)}</div>
 <label className="block text-sm">Search records<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search loaded records" className={input}/></label>
 {tables.map(table=><section key={table.source} className="bg-white rounded-xl border overflow-hidden"><h3 className="font-semibold p-4">{table.title}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{Object.values(table.columns).map(x=><th key={x} className="p-3 text-left">{x}</th>)}{table.action&&can(table.action.permission)&&<th>Action</th>}</tr></thead><tbody>{(data[table.source]||[]).filter(row=>Object.keys(table.columns).some(k=>String(row[k]??'').toLowerCase().includes(search.toLowerCase()))).map(row=><tr key={row.id} className="border-t">{Object.keys(table.columns).map(k=><td key={k} className="p-3">{String(row[k]??'—')}</td>)}{table.action&&can(table.action.permission)&&<td className="p-3">{(!table.action.show||table.action.show(row))&&<Button disabled={busy} onClick={()=>void run(table,row)}>{table.action.label}</Button>}</td>}</tr>)}</tbody></table>{!(data[table.source]||[]).length&&<p className="p-4 text-slate-500">No records.</p>}</div></section>)}{busy&&<p role="status">Loading…</p>}</div>;
};
