import fs from'node:fs';import dotenv from'dotenv';import pg from'pg';
const dir=new URL('./artifacts/',import.meta.url),state=JSON.parse(fs.readFileSync(new URL('state.json',dir))),env=dotenv.parse(fs.readFileSync(new URL('../backend/.env',import.meta.url))),u=new URL(env.DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname)||!state.database.startsWith('edunexus_qa_'))throw Error('Local QA only');u.pathname='/'+state.database;const db=new pg.Client({connectionString:u.href});await db.connect();const results=[];
async function api(name,role,path,expected,options={}){const{tenant=state.tenant,body,method='GET',token=state.accounts[role]?.token}=options;const r=await fetch('http://127.0.0.1:5105'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),'x-tenant-id':tenant},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{}results.push({name,role,path,status:r.status,expected,pass:expected.includes(r.status),response:data||text.slice(0,500)});fs.writeFileSync(new URL('api-audit.json',dir),JSON.stringify(results,null,2));return data;}
await api('Health and PostgreSQL','TENANT_ADMIN','/health',[200]);await api('Unauthenticated protected API','NONE','/api/v1/master-data/profile',[401]);await api('Invalid JWT','TENANT_ADMIN','/api/v1/master-data/profile',[401],{token:'invalid'});
for(const[role,path]of [['TEACHER','/api/v1/finance/accounts'],['PARENT','/api/v1/finance/accounts'],['STUDENT','/api/v1/organization/users'],['ACCOUNTANT','/api/v1/hr/dashboard'],['ADMIN','/api/v1/tenants']])await api('Server denial '+role+' '+path,role,path,[403]);
for(const role of ['TENANT_ADMIN','TEACHER','PARENT','ACCOUNTANT','ADMIN'])await api('Cross-tenant selector denied '+role,role,'/api/v1/master-data/profile',[403],{tenant:state.otherTenant});
await api('Teacher student listing scope','TEACHER','/api/v1/students',[403]);await api('Notification inbox route','PARENT','/api/v1/notifications',[200]);await api('Owner finance accounts','TENANT_ADMIN','/api/v1/finance/accounts',[200]);await api('Owner finance ledger','TENANT_ADMIN','/api/v1/finance/reports/ledger',[200]);await api('Student listing','TENANT_ADMIN','/api/v1/students?pageSize=100',[200]);
const year=(await db.query('SELECT id FROM academic_years WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 1',[state.tenant])).rows[0];const klass=(await db.query('SELECT id FROM classes WHERE tenant_id=$1 AND academic_year_id=$2 LIMIT 1',[state.tenant,year.id])).rows[0];const section=(await db.query('SELECT id FROM sections WHERE tenant_id=$1 AND class_id=$2 LIMIT 1',[state.tenant,klass.id])).rows[0];
state.fixtures={year:year.id,class:klass.id,section:section.id};
for(let i=1;i<=3;i++){const r=await api('API fixture admission '+i,'TENANT_ADMIN','/api/v1/students/admissions',[201],{method:'POST',body:{admissionNo:'QA-API-'+i,firstName:'QA Child '+i,lastName:'Audit',gender:'OTHER',enrollment:{academicYearId:year.id,classId:klass.id,sectionId:section.id,rollNo:String(i)},guardian:{firstName:'QA Guardian '+i,lastName:'Audit',phone:'0000000000',email:state.accounts.PARENT.email}}});if(r?.data)state.fixtures['child'+i]=r.data;}
if(state.fixtures.child1){for(const i of [1,2])await api('Link existing parent account '+i,'TENANT_ADMIN',`/api/v1/fees/parent-access/${state.fixtures['child'+i].guardian.id}/invitation`,[201],{method:'POST',body:{email:state.accounts.PARENT.email}});await api('Parent denied unrelated student detail','PARENT',`/api/v1/students/${state.fixtures.child3.student.id}`,[403]);await api('Teacher denied unassigned student detail','TEACHER',`/api/v1/students/${state.fixtures.child3.student.id}`,[403]);}
const snapshot={tables:(await db.query("SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename")).rows,permissions:(await db.query('SELECT key FROM permissions ORDER BY key')).rows,enrollmentColumns:(await db.query("SELECT column_name FROM information_schema.columns WHERE table_name='enrollments' ORDER BY ordinal_position")).rows};
for(const table of ['students','parents','parent_students','enrollments','audit_logs','fee_assignments','payments','fee_receipts','finance_journals','library_titles','inventory_movements']){try{snapshot[table]=(await db.query(`SELECT COUNT(*)::int count FROM ${table} WHERE tenant_id=$1`,[state.tenant])).rows[0].count}catch(e){snapshot[table]={error:e.message}}}
fs.writeFileSync(new URL('state.json',dir),JSON.stringify(state,null,2));fs.writeFileSync(new URL('database-snapshot.json',dir),JSON.stringify(snapshot,null,2));console.log(JSON.stringify({checks:results.length,passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).map(r=>({name:r.name,status:r.status})),enrollmentColumns:snapshot.enrollmentColumns}));await db.end();
