import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{chromium}from'playwright';
const dir=process.env.BATCH3_ARTIFACT_DIR,f=JSON.parse(fs.readFileSync(path.join(dir,'batch3-api-fixtures.json'))),browser=await chromium.launch({headless:true}),results=[];
for(const key of ['owner','accountant','teacher','parent','custom','super','student','staff']){
 const c=await browser.newContext({viewport:{width:1440,height:1000}}),e={key,steps:[],responses:[],console:[],pageErrors:[],failedRequests:[],externalBlocked:[],expectedDenials:[]};await c.route('**/*',r=>{if(!['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)){e.externalBlocked.push(r.request().url());return r.abort();}return r.continue();});const p=await c.newPage();p.setDefaultTimeout(20000);p.on('console',m=>{if(['error','warning'].includes(m.type()))e.console.push({type:m.type(),text:m.text(),url:m.location().url});});p.on('pageerror',x=>e.pageErrors.push(x.message));p.on('requestfailed',r=>e.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));p.on('response',r=>{if(r.url().includes('/api/'))e.responses.push({url:r.url(),method:r.request().method(),status:r.status()});});
 const nav=async(module)=>{await p.goto('http://127.0.0.1:5189/#/app/'+module);await p.getByTitle('Notifications',{exact:true}).waitFor();};
 const api=async(route,status=200)=>{if(status>=400)e.expectedDenials.push({url:'http://127.0.0.1:5109/api/v1'+route,status});const r=await p.evaluate(async route=>{const r=await fetch('http://127.0.0.1:5109/api/v1'+route,{headers:{Authorization:`Bearer ${localStorage.getItem('edunexus_auth_token')}`}});return{status:r.status,body:await r.json()}},route);assert.equal(r.status,status);return r.body.data;};
 const refreshed=async(text)=>{await p.reload();await p.getByText(text,{exact:true}).first().waitFor();e.steps.push('Refresh persists '+text);};
 try{await p.goto('http://127.0.0.1:5189/#/login');await p.locator('input[type=email]').fill(f.accounts[key].email);await p.locator('input[type=password]').fill(f.password);const signin=p.waitForResponse(r=>r.url().endsWith('/auth/signin'));await p.getByRole('button',{name:'Sign in',exact:true}).click();const login=await signin;assert.equal(login.status(),200);e.user=(await login.json()).data.user;await p.getByTitle('Notifications',{exact:true}).waitFor();e.steps.push('Real login and shell');e.sidebar=await p.locator('aside [data-module]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-module')));
 if(['owner','accountant'].includes(key)){
  if(key==='accountant'){await nav('fees');await p.getByRole('heading',{name:'Fee Management',exact:true}).waitFor();await p.getByText('Batch3Child Acceptance',{exact:true}).first().waitFor();assert.ok(!(await p.locator('body').innerText()).includes('This action is not permitted'));e.steps.push('Accountant real dues visible without student/master hydration');await p.getByRole('button',{name:'verify',exact:true}).click();await p.getByText(f.pending.transaction_reference||``,{exact:true}).count();assert.ok(await p.getByRole('button',{name:'Approve',exact:true}).count());e.steps.push('Pending proof list and authorized verification action');await p.getByRole('button',{name:'receipts',exact:true}).click();await p.getByText('Batch3Child Acceptance',{exact:true}).first().waitFor();e.steps.push('Approved receipt loads');await refreshed('Batch3Child Acceptance');await p.getByRole('button',{name:'reports',exact:true}).click();await p.getByText('Collected',{exact:true}).first().waitFor();e.steps.push('Authorized fee report loads');}
  await nav('finance');await p.getByText('General Expense',{exact:true}).waitFor();assert.equal(await p.locator('[aria-readonly=true]').count(),0);e.steps.push('Finance workspace and chart of accounts');await p.getByRole('button',{name:'Cash/Bank Accounts',exact:true}).click();await p.getByText('Main Cash Box',{exact:true}).waitFor();e.steps.push('Cash/bank selector records');await p.getByRole('button',{name:'Journals',exact:true}).click();await p.getByText(/STUDENT_FEE_PAYMENT/).first().waitFor();e.steps.push('Verified fee journal visible');
  if(key==='owner')for(const [tab,title,amount,account,submit,message] of [['Expenses','Batch 3 browser expense','150','General Expense','Post expense','Expense posted.'],['Other Income','Batch 3 browser income','250','Other Income','Post income','Other income posted.']]){await p.getByRole('button',{name:tab,exact:true}).click();await p.getByLabel('Title',{exact:true}).fill(title);await p.getByLabel('Amount',{exact:true}).fill(amount);await p.getByRole('combobox').nth(0).selectOption({label:account});await p.getByRole('combobox').nth(1).selectOption({label:'Main Cash Box'});const post=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/finance/'));await p.getByRole('button',{name:submit,exact:true}).click();assert.equal((await post).status(),201);await p.getByText(message,{exact:true}).waitFor();await p.getByText(title,{exact:true}).first().waitFor();e.steps.push('UI posts '+tab+' and displays persisted record');await p.reload();await p.getByText('General Expense',{exact:true}).waitFor();await p.getByRole('button',{name:tab,exact:true}).click();await p.getByText(title,{exact:true}).first().waitFor();e.steps.push('Refresh preserves '+tab);}
  for(const tab of ['Journals','General Ledger','Cash/Bank Book','Income/Expense Report','Fee Reconciliation']){await p.getByRole('button',{name:tab,exact:true}).click();await p.waitForTimeout(100);assert.equal(await p.getByRole('alert').count(),0);e.steps.push('Real '+tab+' renders');}
  const reconcile=p.waitForResponse(r=>r.url().endsWith('/reconcile/fee-payments'));await p.getByRole('button',{name:'Reconcile fee payments',exact:true}).click();assert.equal((await reconcile).status(),200);await p.getByText(/Reconciliation complete:/).waitFor();e.steps.push('Reconciliation normal API workflow');await p.reload();await p.getByText('General Expense',{exact:true}).waitFor();const ledger=await api('/finance/reports/ledger');await p.getByRole('button',{name:'General Ledger',exact:true}).click();const body=await p.locator('body').innerText();for(const a of ledger)assert.ok(body.includes(new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(a.balance)));e.steps.push('UI ledger totals match backend');
  if(key==='accountant'){assert.ok(!e.sidebar.includes('staff')&&!e.sidebar.includes('attendance')&&!e.sidebar.includes('master-data')&&!e.sidebar.includes('hr'));await nav('communication');await p.getByRole('heading',{name:'Communication & Notifications',exact:true}).waitFor();await p.getByPlaceholder('Fee assignment UUID').fill(f.assignment.id);const remind=p.waitForResponse(r=>r.url().endsWith('/communication/fee-reminders'));await p.getByRole('button',{name:'Queue reminder',exact:true}).click();assert.equal((await remind).status(),200);await p.getByText(/Fee reminder queued/).waitFor();e.steps.push('Accountant authorized reminder without HR or academic admin');}
 }else if(key==='custom'){assert.ok(e.sidebar.includes('master-data'));assert.ok(!e.sidebar.includes('finance')&&!e.sidebar.includes('organization')&&!e.sidebar.includes('attendance'));await nav('master-data');await p.getByRole('button',{name:'Years',exact:true}).click();await p.getByText('Batch 3 2026-27',{exact:true}).waitFor();assert.equal(await p.locator('form').count(),0);e.steps.push('Custom ADMIN actual view grant; write forms absent');await p.reload();await p.getByRole('button',{name:'Years',exact:true}).click();await p.getByText('Batch 3 2026-27',{exact:true}).waitFor();e.steps.push('Custom ADMIN permission preserved on refresh');}
 else if(key==='super'){await nav('superadmin-plans');await p.getByRole('heading',{name:'SaaS Billing Administration',exact:true}).waitFor();await p.getByRole('button',{name:'Tenant Subscriptions',exact:true}).click();await api('/admin/billing/plans');e.steps.push('Batch 2 platform billing remains accessible');}
 else if(key==='parent'){await nav('fees');await p.getByText('Proof History',{exact:true}).waitFor();e.steps.push('Own linked-child parent portal');}
 else{e.steps.push('Restricted role shell loads');}
 if(!['owner','accountant','super'].includes(key)){assert.ok(!e.sidebar.includes('finance'));await nav('finance');await p.getByRole('heading',{name:'Access Restricted',exact:true}).waitFor();await api('/finance/accounts',403);e.steps.push('Finance nav absent; direct UI and server RBAC deny');}
 if(key==='teacher'){await nav('communication');await p.getByRole('heading',{name:'Access Restricted',exact:true}).waitFor();assert.ok(!e.sidebar.includes('communication'));e.steps.push('BUG-007 original legacy communication route denied before loading');}
 if(key==='staff'){assert.ok(!e.sidebar.includes('attendance'));await nav('attendance');await p.getByRole('heading',{name:'Access Restricted',exact:true}).waitFor();assert.ok(!e.responses.some(r=>r.url.includes('/staff/assignments')));e.steps.push('BUG-019 exact Staff attendance reproduction: hidden and direct route denied without assignment loader');}
 await p.reload();await p.getByTitle('Notifications',{exact:true}).waitFor();assert.deepEqual((await api('/auth/me')).user.permissions,e.user.permissions);e.steps.push('Permission refresh equals authenticated server grants');if(key==='custom'){assert.equal(await p.getByTitle('Notifications',{exact:true}).isDisabled(),true);assert.ok(!e.responses.some(r=>r.url.includes('/notifications')));e.steps.push('Custom role shell makes no unauthorized notification requests');}else{await api('/notifications');await api('/notifications/preferences');e.steps.push('Previous notification shell regression passes');}await p.screenshot({path:path.join(dir,`batch3-${key}.png`),fullPage:true});await p.locator('header').getByRole('button').filter({hasText:e.user.name}).click();await p.getByRole('button',{name:'Sign Out',exact:true}).click();await p.waitForFunction(()=>localStorage.getItem('edunexus_auth_token')===null);e.steps.push('Logout reachable');
 e.unexpectedResponses=e.responses.filter(r=>r.status>=400&&!e.expectedDenials.some(d=>d.url===r.url&&d.status===r.status));assert.deepEqual(e.unexpectedResponses,[]);assert.deepEqual(e.pageErrors,[]);e.status='PASS';
 }catch(x){e.status='FAIL';e.error=x.stack;e.body=await p.locator('body').innerText();console.error(key,x.message);await p.screenshot({path:path.join(dir,`batch3-failed-${key}.png`),fullPage:true});process.exitCode=1;}finally{results.push(e);fs.writeFileSync(path.join(dir,'batch3-browser-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({key,status:e.status,steps:e.steps.length,errors:e.responses.filter(r=>r.status>=400)}));await c.close();}
}await browser.close();
