import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{chromium}from'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=path.join(root,'qa','artifacts'),statePath=path.join(dir,'state.json'),state=JSON.parse(fs.readFileSync(statePath));
const routes=['dashboard','master-data','organization','students','staff','attendance','timetable','exams','results','fees','finance','communication','hr','library','inventory','transport','hostel','mess','academics','homework','health','crm','reports','settings','roles-matrix','api-docs','schema','saas-billing','superadmin-tenants','superadmin-plans','superadmin-features','superadmin-dashboard'];
const requested=process.argv.slice(2),roles=requested.length?requested:['TENANT_ADMIN','SUPER_ADMIN','ADMIN','TEACHER','ACCOUNTANT','PARENT','STUDENT','STAFF'];
const browser=await chromium.launch({headless:true});const results=[];
for(const role of roles){const context=await browser.newContext({viewport:{width:1440,height:900}});const external=[];await context.route('**/*',async route=>{const u=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push({url:u.origin,kind:route.request().resourceType()});await route.abort();}else await route.continue();});const page=await context.newPage();let consoleEvents=[],network=[];page.on('console',m=>{if(['error','warning'].includes(m.type()))consoleEvents.push({type:m.type(),text:m.text()});});page.on('pageerror',e=>consoleEvents.push({type:'uncaught',text:e.message}));page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)network.push({url:r.url(),status:r.status()});});
await page.goto('http://127.0.0.1:5185/#/login');await page.locator('input[type=email]').fill(state.accounts[role].email);await page.locator('input[type=password]').fill(state.password);const response=page.waitForResponse(r=>r.url().endsWith('/auth/signin'));await page.getByRole('button',{name:'Sign in',exact:true}).click();const login=await(await response).json();if(login.data?.token){state.accounts[role].token=login.data.token;fs.writeFileSync(statePath,JSON.stringify(state,null,2));}await page.waitForTimeout(700);
results.push({role,route:'login',url:page.url(),body:(await page.locator('body').innerText()).slice(0,5000),console:consoleEvents,network});
for(const route of routes){consoleEvents=[];network=[];await page.goto(`http://127.0.0.1:5185/#/app/${route}`);await page.waitForTimeout(450);await page.locator('text=Loading').first().waitFor({state:'hidden',timeout:1500}).catch(()=>{});const body=(await page.locator('body').innerText()).slice(0,12000);const screen={role,route,url:page.url(),body,console:[...consoleEvents],network:[...network],controls:await page.locator('main input,main select,main button').evaluateAll(els=>els.map(e=>({tag:e.tagName,type:e.type,name:e.name,text:e.textContent?.trim().slice(0,100),placeholder:e.placeholder,disabled:e.disabled}))),overflow:await page.evaluate(()=>({documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}))};if(role==='TENANT_ADMIN'||['fees','dashboard','hr'].includes(route)){screen.screenshot=`${role}-${route}.png`;await page.screenshot({path:path.join(dir,screen.screenshot),fullPage:true});}results.push(screen);fs.writeFileSync(path.join(dir,`screens-${role}.json`),JSON.stringify(results.filter(x=>x.role===role),null,2));}
if(role==='TENANT_ADMIN'){for(const viewport of [{width:1366,height:768},{width:768,height:900},{width:390,height:844}]){await page.setViewportSize(viewport);for(const route of ['dashboard','master-data','fees','hr','library','transport','hostel','mess']){await page.goto(`http://127.0.0.1:5185/#/app/${route}`);await page.waitForTimeout(250);const overflow=await page.evaluate(()=>({documentWidth:document.documentElement.scrollWidth,viewport:innerWidth}));await page.screenshot({path:path.join(dir,`responsive-${viewport.width}-${route}.png`),fullPage:true});results.push({role,route,viewport,overflow,body:(await page.locator('body').innerText()).slice(0,4000)});}}}
console.log(JSON.stringify({role,screens:results.filter(x=>x.role===role).length,unexpectedNetwork:results.filter(x=>x.role===role).reduce((n,x)=>n+(x.network?.length||0),0),externalBlocked:external.length}));await context.close();}
fs.writeFileSync(path.join(dir,'screen-audit.json'),JSON.stringify(results,null,2));await browser.close();
