import fs from'node:fs';import{chromium}from'playwright';import dotenv from'dotenv';import pg from'pg';
const dir=new URL('./artifacts/',import.meta.url),state=JSON.parse(fs.readFileSync(new URL('state.json',dir))),f=state.fixtures,results=[];const env=dotenv.parse(fs.readFileSync(new URL('../backend/.env',import.meta.url))),u=new URL(env.DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname)||!state.database.startsWith('edunexus_qa_'))throw Error('Local QA only');u.pathname='/'+state.database;const db=new pg.Client({connectionString:u.href});await db.connect();
function record(name,status,evidence){results.push({name,status,evidence});fs.writeFileSync(new URL('fee-audit.json',dir),JSON.stringify(results,null,2));console.log(JSON.stringify({name,status}));}
async function api(name,role,path,method='GET',body,expected=[200]){const r=await fetch('http://127.0.0.1:5105/api/v1'+path,{method,headers:{Authorization:'Bearer '+state.accounts[role].token,'x-tenant-id':state.tenant,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();record(name,expected.includes(r.status)?'PASS':'FAIL',{http:r.status,data});return data.data;}
await api('Same parent linked to second child relationship','TENANT_ADMIN',`/students/${f.child2.student.id}/parents`,'POST',{parentId:f.child1.guardian.id,relationshipType:'GUARDIAN'},[201]);
await api('School manual payment settings','TENANT_ADMIN','/fees/settings','PUT',{payeeName:'QA School',upiId:'qa-only@invalid',instructions:'QA only. Never send money.'});
const structure=await api('Fee structure API fixture','TENANT_ADMIN','/fees/structures','POST',{name:'QA Tuition',academicYearId:f.year,classId:f.class,items:[{name:'QA tuition',amount:1000}]},[201]);
f.assignments=[];for(let i=1;i<=3;i++)f.assignments.push(await api('Fee assignment API fixture '+i,'TENANT_ADMIN','/fees/assignments','POST',{enrollmentId:f['child'+i].enrollment.id,feeStructureId:structure.id,concessionAmount:0,installments:[{name:'QA installment',dueDate:'2026-10-01',amount:1000}]},[201]));
const browser=await chromium.launch();const context=await browser.newContext();await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const page=await context.newPage();page.setDefaultTimeout(5000);await page.goto('http://127.0.0.1:5185/');await page.evaluate(token=>localStorage.setItem('edunexus_auth_token',token),state.accounts.PARENT.token);await page.goto('http://127.0.0.1:5185/#/app/fees');await page.getByRole('heading',{name:'Parent Fee Portal',exact:true}).waitFor();await page.waitForTimeout(500);record('Parent child selector and own fees','PASS',{body:(await page.locator('main').innerText()).slice(0,5000),selects:await page.locator('main select').count()});
const proofFile={name:'qa-proof.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64')};
const proofs=[];for(const[amount,reference]of [[400,'QA-PART-1'],[600,'QA-PART-2']]){await page.locator('form select').first().selectOption({index:1});await page.getByLabel('Amount paid',{exact:true}).fill(String(amount));await page.getByLabel('UPI transaction reference',{exact:true}).fill(reference);await page.locator('input[type=file]').setInputFiles(proofFile);const pending=page.waitForResponse(r=>r.url().endsWith('/fees/proofs')&&r.request().method()==='POST');await page.getByRole('button',{name:'Upload payment proof',exact:true}).click();const r=await pending,data=await r.json();record('Parent browser proof upload '+amount,r.status()===201?'PASS':'FAIL',{http:r.status(),data});if(data.data){proofs.push(data.data);await api('Accountant partial approval '+amount,'ACCOUNTANT',`/fees/proofs/${data.data.id}/verify`,'PATCH',{decision:'APPROVED',notes:'Local QA verified'});if(amount===400)await api('Duplicate approval rejected','ACCOUNTANT',`/fees/proofs/${data.data.id}/verify`,'PATCH',{decision:'APPROVED',notes:'QA retry'},[409]);}await page.reload();await page.waitForTimeout(500);record('Parent balance and receipt refresh '+amount,'PASS',{body:(await page.locator('main').innerText()).slice(0,6500)});}
const tiny='data:image/png;base64,'+proofFile.buffer.toString('base64');await api('Overpayment rejected by backend','PARENT','/fees/proofs','POST',{feeAssignmentId:f.assignments[0].id,amount:1,transactionReference:'QA-OVERPAY',paymentDate:'2026-10-03',fileName:'qa.png',proofDataUrl:tiny},[422]);await api('Unrelated child proof denied','PARENT','/fees/proofs','POST',{feeAssignmentId:f.assignments[2].id,amount:1,transactionReference:'QA-UNRELATED',paymentDate:'2026-10-03',fileName:'qa.png',proofDataUrl:tiny},[403]);await api('Parent cannot verify proof','PARENT',`/fees/proofs/${proofs[0]?.id}/verify`,'PATCH',{decision:'APPROVED',notes:'QA forbidden'},[403]);
await page.evaluate(token=>localStorage.setItem('edunexus_auth_token',token),state.accounts.ACCOUNTANT.token);await page.goto('http://127.0.0.1:5185/#/app/fees');await page.waitForTimeout(600);await page.getByRole('button',{name:'verify',exact:true}).click();record('Accountant browser verification usable','FAIL',{body:(await page.locator('main').innerText()).slice(0,5000),reason:'Student list failure prevents fee screen data hydration; approvals above exercised API, not browser.'});
const consistency={assignments:(await db.query('SELECT id,total_amount,paid_amount,balance_amount,status FROM fee_assignments WHERE tenant_id=$1',[state.tenant])).rows,payments:(await db.query('SELECT id,receipt_no,amount,payment_proof_id FROM payments WHERE tenant_id=$1',[state.tenant])).rows,journals:(await db.query('SELECT * FROM finance_journals WHERE tenant_id=$1',[state.tenant])).rows,notifications:(await db.query('SELECT event_type,COUNT(*)::int count FROM notifications WHERE tenant_id=$1 GROUP BY event_type',[state.tenant])).rows};fs.writeFileSync(new URL('fee-consistency.json',dir),JSON.stringify(consistency,null,2));fs.writeFileSync(new URL('state.json',dir),JSON.stringify(state,null,2));await page.screenshot({path:new URL('accountant-fee-verification.png',dir).pathname.replace(/^\/C:/,'C:')});await browser.close();await db.end();
