import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {observe} from './rc-observe.mjs';
const dir='qa/artifacts/rc',s=JSON.parse(fs.readFileSync(dir+'/state.json')),f=JSON.parse(fs.readFileSync(dir+'/rc-api-fixtures.json')),out=[];const base='http://127.0.0.1:5111/api/v1',web='http://127.0.0.1:5191';
async function api(role,method,path,body){const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+s.accounts[role].token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};}
const browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:1440,height:900}});await observe(ctx);await ctx.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const page=await ctx.newPage();page.setDefaultTimeout(7000);page.setDefaultNavigationTimeout(45000);let events=[];page.on('response',async r=>{if(r.url().includes('/api/')&&(r.request().method()!=='GET'||r.status()>=400))events.push({url:r.url(),method:r.request().method(),status:r.status(),body:await r.text().catch(()=> '')});});
async function test(name,fn,negative=false){events=[];let status='PASS',error;try{await fn();await page.waitForTimeout(350);if(!negative&&events.some(x=>x.status>=400))status='FAIL';}catch(e){status='BLOCKED';error=e.message;}out.push({name,status,negative,error,events:[...events],url:page.url(),body:(await page.locator('body').innerText()).slice(-18000)});fs.writeFileSync(dir+'/focused-workflows.json',JSON.stringify(out,null,2));console.log(JSON.stringify({name,status}));}
async function login(role){await ctx.clearCookies();await page.goto(web+'/#/login');await page.evaluate(()=>localStorage.removeItem('edunexus_auth_token'));await page.reload();await page.locator('input[type=email]').fill(s.accounts[role].email);await page.locator('input[type=password]').fill(s.password);const p=page.waitForResponse(r=>r.url().endsWith('/auth/signin'));await page.getByRole('button',{name:'Sign in',exact:true}).click();const r=await p;assert.equal(r.status(),200);const data=(await r.json()).data;s.accounts[role].token=data.token;fs.writeFileSync(dir+'/state.json',JSON.stringify(s,null,2));await page.waitForTimeout(500);}
async function go(route){await page.goto(web+'/#/app/'+route);await page.waitForTimeout(600);}
async function click(name){const response=page.waitForResponse(r=>r.url().includes('/api/')&&r.request().method()!=='GET');await page.getByRole('button',{name,exact:true}).click();const r=await response;await page.waitForTimeout(500);return {status:r.status(),body:await r.json()};}
await login('TENANT_ADMIN');
await test('School valid profile persists refresh and navigation',async()=>{await go('master-data');await page.getByRole('button',{name:'Profile',exact:true}).click();await page.getByLabel('School name',{exact:true}).fill('RC Certified School');await page.getByLabel('Email',{exact:true}).fill('school@rc.example.test');await page.getByLabel('Website',{exact:true}).fill('https://rc.example.test');await page.getByLabel('City',{exact:true}).fill('RC City');assert.equal((await click('Save profile')).status,200);await page.reload();await page.getByLabel('City',{exact:true}).waitFor();assert.equal(await page.getByLabel('City',{exact:true}).inputValue(),'RC City');await go('students');await go('master-data');assert.equal(await page.getByLabel('City',{exact:true}).inputValue(),'RC City');});
await test('Fee settings saved in browser',async()=>{await go('fees');await page.getByRole('button',{name:'settings',exact:true}).click();await page.getByLabel('Payee name',{exact:true}).fill('RC School');await page.getByLabel('UPI ID',{exact:true}).fill('rc-only@invalid');assert.equal((await click('Save payment settings')).status,200);await page.reload();await page.getByRole('button',{name:'settings',exact:true}).click();assert.equal(await page.getByLabel('UPI ID',{exact:true}).inputValue(),'rc-only@invalid');});
await test('Finance expense and income post through real forms',async()=>{await go('finance');for(const [tab,button,amount] of [['Expenses','Post expense','123.45'],['Other Income','Post income','234.56']]){await page.getByRole('button',{name:tab,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('RC '+tab);await page.getByLabel('Amount',{exact:true}).fill(amount);await page.getByLabel('Date',{exact:true}).fill('2026-10-05');await page.getByLabel(tab==='Expenses'?'Expense account':'Income account',{exact:true}).selectOption({index:1});await page.getByLabel('Cash/Bank account',{exact:true}).selectOption({index:1});assert.equal((await click(button)).status,201);await page.reload();await page.getByRole('button',{name:tab,exact:true}).click();await page.getByText('RC '+tab,{exact:true}).waitFor();}for(const tab of ['Journals','General Ledger','Cash/Bank Book','Income/Expense Report','Fee Reconciliation']){await page.getByRole('button',{name:tab,exact:true}).click();assert(!/NaN/.test(await page.locator('main').innerText()));}});
await test('Communication reminder queues and deduplicates UI action',async()=>{await go('communication');for(let i=0;i<2;i++){await page.getByPlaceholder('Fee assignment UUID').fill(f.assignment.id);assert.equal((await click('Queue reminder')).status,200);}await page.reload();await page.getByRole('heading',{name:'Active templates'}).waitFor();});
const ext=JSON.parse(fs.readFileSync(dir+'/extended-workflows.json'));const inv=JSON.parse(ext.find(x=>x.name==='Teacher invitation generation').events[0].body).data;
await test('Teacher actual invitation activated through onboarding UI',async()=>{await page.goto(web+'/#/onboarding?token='+inv.onboardingToken);await page.getByPlaceholder('New password',{exact:true}).fill(s.password);await page.getByPlaceholder('Confirm password',{exact:true}).fill(s.password);assert.equal((await click('Activate owner account')).status,200);s.accounts.TEACHER.email=inv.email;fs.writeFileSync(dir+'/state.json',JSON.stringify(s,null,2));});
await login('TEACHER');
await test('Linked teacher own class attendance and absent child',async()=>{await go('attendance');await page.getByLabel('Year',{exact:true}).selectOption({index:1});await page.getByLabel('Class',{exact:true}).selectOption({index:1});await page.getByLabel('Section',{exact:true}).selectOption({index:1});await page.getByLabel('Date',{exact:true}).fill('2026-10-05');await page.getByRole('button',{name:'Load roster',exact:true}).click();await page.locator('table select').first().waitFor();await page.locator('table select').first().selectOption('ABSENT');assert.equal((await click('Save attendance')).status,200);await page.reload();await page.getByLabel('Year',{exact:true}).selectOption({index:1});await page.getByLabel('Class',{exact:true}).selectOption({index:1});await page.getByLabel('Section',{exact:true}).selectOption({index:1});await page.getByRole('button',{name:'Load roster',exact:true}).click();await page.locator('table select').first().waitFor();assert.equal(await page.locator('table select').first().inputValue(),'ABSENT');});
await login('TENANT_ADMIN');
await test('HR type and teacher balance configured UI',async()=>{await go('hr');await page.getByLabel('Leave type name',{exact:true}).fill('RC Annual');assert.equal((await click('Add type')).status,201);const form=page.locator('form').filter({has:page.getByRole('button',{name:'Set balance',exact:true})});await form.getByLabel('Staff',{exact:true}).selectOption({index:1});await form.getByLabel('Leave type',{exact:true}).selectOption({index:1});await page.getByLabel('Entitlement days',{exact:true}).fill('10');assert.equal((await click('Set balance')).status,200);});
await login('TEACHER');
await test('Linked teacher requests own leave UI',async()=>{await go('hr');const form=page.locator('form').filter({has:page.getByRole('button',{name:'Request',exact:true})});await form.getByLabel('Leave type',{exact:true}).selectOption({index:1});await form.locator('[name=startDate]').fill('2026-10-12');await form.locator('[name=endDate]').fill('2026-10-12');await form.getByLabel('Reason',{exact:true}).fill('RC local audit');assert.equal((await click('Request')).status,201);});
await login('TENANT_ADMIN');
await test('HR leave approval and linked attendance UI',async()=>{await go('hr');assert.equal((await click('Approve')).status,200);await page.getByLabel('Date',{exact:true}).fill('2026-10-12');const form=page.locator('form').filter({has:page.getByRole('button',{name:'Save attendance',exact:true})});await form.getByLabel('Staff',{exact:true}).selectOption({index:1});await form.getByLabel('Attendance status',{exact:true}).selectOption('LEAVE');assert.equal((await click('Save attendance')).status,200);await page.reload();await page.getByText('APPROVED',{exact:true}).waitFor();});
await login('PARENT');
await test('Parent proof upload of remaining partial payment',async()=>{await go('fees');await page.getByLabel('Fee due',{exact:true}).selectOption(f.assignment.id);await page.getByLabel('Amount paid',{exact:true}).fill('500');await page.getByLabel('UPI transaction reference',{exact:true}).fill('RC-browser-500');await page.getByLabel('Payment date',{exact:true}).fill('2026-10-05');await page.locator('input[type=file]').setInputFiles({name:'rc-proof.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6r4cAAAAASUVORK5CYII=','base64')});assert.equal((await click('Upload payment proof')).status,201);await page.reload();await page.getByText('RC-browser-500',{exact:true}).waitFor();});
await login('ACCOUNTANT');
await test('Accountant approves uploaded proof UI',async()=>{await go('fees');await page.getByRole('button',{name:'verify',exact:true}).click();const row=page.locator('tr').filter({hasText:'RC-browser-500'});const response=page.waitForResponse(r=>r.url().includes('/verify'));await row.getByRole('button',{name:'Approve',exact:true}).click();assert.equal((await response).status(),200);await page.waitForTimeout(400);});
await login('PARENT');
await test('Parent receipt, verified balance and payment date survive navigation',async()=>{await go('fees');await page.getByText('RC-browser-500',{exact:true}).waitFor();await page.reload();await go('dashboard');await go('fees');assert((await page.locator('main').innerText()).includes('₹100.00'));assert(!(await page.locator('main').innerText()).includes('NaN'));});
await test('API final100 approval and overpayment proof boundary',async()=>{const approval=await api('TENANT_ADMIN','PATCH','/fees/proofs/'+f.pending.id+'/verify',{decision:'APPROVED'});assert.equal(approval.status,200);const result=await api('PARENT','POST','/fees/proofs',{feeAssignmentId:f.assignment.id,amount:1,transactionReference:'RC-overpaid-final',paymentDate:'2026-10-05',fileName:'proof.png',proofDataUrl:'data:image/png;base64,aGVsbG8='});out.push({name:'BUG-018 paid assignment positive proof',status:result.status===201?'REPRODUCED':'CHECK',evidence:result});});
await browser.close();
