// Audit-only local infrastructure. Existing databases are never dropped.
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';import{randomUUID,randomBytes}from'node:crypto';import{spawnSync}from'node:child_process';import dotenv from'dotenv';import pg from'pg';import bcrypt from'bcryptjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dir=path.join(root,'qa','artifacts');
const original=dotenv.parse(fs.readFileSync(path.join(root,'backend','.env'))),base=new URL(original.DATABASE_URL||'');
if(!['localhost','127.0.0.1','[::1]'].includes(base.hostname)||!/^postgres(ql)?:$/.test(base.protocol))throw Error('QA refuses non-local PostgreSQL.');
const action=process.argv[2],statePath=path.join(dir,'state.json');let state=fs.existsSync(statePath)?JSON.parse(fs.readFileSync(statePath)):null;
if(action==='inspect'){console.log(JSON.stringify({databaseHost:base.hostname,configuredDatabase:base.pathname.slice(1),configuredMode:original.NODE_ENV,emailMode:original.EMAIL_DELIVERY_MODE||'LOG',qaDatabase:state?.database||null,apiPort:5105,frontendPort:5185,externalNetwork:'blocked'},null,2));process.exit(0);}
fs.mkdirSync(dir,{recursive:true});
if(action==='setup'&&!state){state={database:`edunexus_qa_${Date.now()}_${randomBytes(3).toString('hex')}`,password:`QaOnly!${randomBytes(18).toString('hex')}`,accounts:{},tenant:randomUUID(),otherTenant:randomUUID()};const adminUrl=new URL(base);adminUrl.pathname='/postgres';const admin=new pg.Client({connectionString:adminUrl.href});await admin.connect();await admin.query(`CREATE DATABASE "${state.database}"`);await admin.end();fs.writeFileSync(statePath,JSON.stringify(state,null,2));}
if(!state||!/^edunexus_qa_\d+_[a-f0-9]{6}(_test)?$/.test(state.database))throw Error('Create isolated QA database first.');
if(action==='rename-test'&&!state.database.endsWith('_test')){const adminUrl=new URL(base);adminUrl.pathname='/postgres';const db=new pg.Client({connectionString:adminUrl.href});await db.connect();await db.query(`ALTER DATABASE "${state.database}" RENAME TO "${state.database}_test"`);await db.end();state.database+='_test';fs.writeFileSync(statePath,JSON.stringify(state,null,2));console.log('Renamed isolated QA database to satisfy existing test safety guard.');process.exit(0);}
base.pathname='/'+state.database;
Object.assign(process.env,{DATABASE_URL:base.href,NODE_ENV:'development',PORT:'5105',FRONTEND_URL:'http://127.0.0.1:5185',CORS_ORIGIN:'http://localhost:5185',APP_PUBLIC_URL:'http://127.0.0.1:5185',JWT_SECRET:'qa-local-only-jwt-secret-with-more-than-32-characters',JWT_EXPIRES_IN:'1h',JWT_ISSUER:'edunexus-api',JWT_AUDIENCE:'edunexus-web',EMAIL_DELIVERY_MODE:'LOG',EMAIL_FROM_ADDRESS:'qa@example.invalid',RAZORPAY_KEY_ID:'rzp_test_mock',RAZORPAY_KEY_SECRET:'rzp_secret_mock',RAZORPAY_WEBHOOK_SECRET:'rzp_webhook_mock',RESEND_API_KEY:'',VITE_API_URL:'http://127.0.0.1:5105/api/v1',VITE_GEMINI_API_KEY:''});
const nativeFetch=globalThis.fetch;globalThis.fetch=(input,options)=>{const url=new URL(typeof input==='string'?input:input.url||String(input));if(!['127.0.0.1','localhost','[::1]'].includes(url.hostname))throw Error('LOCAL_QA_EXTERNAL_NETWORK_BLOCKED');return nativeFetch(input,options);};
const command=(args,cwd=path.join(root,'backend'))=>{const r=spawnSync(process.execPath,args,{cwd,env:process.env,stdio:'inherit'});if(r.status!==0)process.exit(r.status||1);};
if(action==='setup'){command(['migrate.mjs','up']);const db=new pg.Client({connectionString:base.href});await db.connect();if(!state.seeded){
await db.query(`INSERT INTO tenants(id,name,slug,tenant_type,status) VALUES($1,'QA School 2026-27',$2,'school','active'),($3,'QA Other School',$4,'school','active')`,[state.tenant,`qa-${state.tenant}`,state.otherTenant,`qa-${state.otherTenant}`]);const hash=await bcrypt.hash(state.password,12);
for(const key of ['SUPER_ADMIN','TENANT_ADMIN','TEACHER','ACCOUNTANT','PARENT','STUDENT','STAFF']){const email=`${key.toLowerCase()}@qa.example.test`,u=(await db.query(`INSERT INTO users(email,password_hash,status) VALUES($1,$2,'ACTIVE') RETURNING id`,[email,hash])).rows[0];await db.query(`INSERT INTO profiles(id,display_name,status) VALUES($1,$2,'active')`,[u.id,`QA ${key}`]);const role=(await db.query(`SELECT id FROM roles WHERE key=$1 AND tenant_id IS NULL`,[key])).rows[0];await db.query(`INSERT INTO memberships(tenant_id,user_id,role_id,status) VALUES($1,$2,$3,'active')`,[state.tenant,u.id,role.id]);state.accounts[key]={id:u.id,email};}
const custom=(await db.query(`INSERT INTO roles(tenant_id,key,name) VALUES($1,'QA_ADMIN','QA Limited Admin') RETURNING id`,[state.tenant])).rows[0];await db.query(`INSERT INTO role_permissions(role_id,permission_id) SELECT $1,id FROM permissions WHERE key IN ('master_data.view','master_data.manage','student_lifecycle.view','students.create','students.update','notifications.view_own')`,[custom.id]);const u=(await db.query(`INSERT INTO users(email,password_hash,status) VALUES('admin@qa.example.test',$1,'ACTIVE') RETURNING id`,[hash])).rows[0];await db.query(`INSERT INTO profiles(id,display_name,status) VALUES($1,'QA Limited Admin','active')`,[u.id]);await db.query(`INSERT INTO memberships(tenant_id,user_id,role_id,status) VALUES($1,$2,$3,'active')`,[state.tenant,u.id,custom.id]);state.accounts.ADMIN={id:u.id,email:'admin@qa.example.test'};state.seeded=true;fs.writeFileSync(statePath,JSON.stringify(state,null,2));}console.log(JSON.stringify({qaDatabase:state.database,accounts:Object.keys(state.accounts),seeded:true}));await db.end();}
else if(action==='api')await import('../backend/src/server.ts');
else if(action==='worker'){const worker=await import('../backend/src/worker.ts');worker.startNotificationWorker();process.once('SIGTERM',()=>void worker.stopNotificationWorker('SIGTERM'));process.once('SIGINT',()=>void worker.stopNotificationWorker('SIGINT'));}
else if(action==='frontend')command([path.join(root,'node_modules','vite','bin','vite.js'),'--host','127.0.0.1','--port','5185','--strictPort'],path.join(root,'frontend'));
else if(action==='tests'){process.env.NODE_ENV='test';command(['--import','tsx','--test',...fs.readdirSync(path.join(root,'backend','tests')).filter(x=>x.endsWith('.test.mjs')).map(x=>'tests/'+x)]);}
else if(action==='status'){command(['migrate.mjs','status']);command(['verify-db.mjs']);}
