import fs from 'node:fs';import pg from 'pg';import dotenv from 'dotenv';
const dir='qa/artifacts/training',e=JSON.parse(fs.readFileSync(dir+'/login-verification.json')),s=JSON.parse(fs.readFileSync('qa/artifacts/rc/rc-state.json'));const u=new URL(dotenv.parse(fs.readFileSync('backend/.env')).DATABASE_URL);if(!['localhost','127.0.0.1'].includes(u.hostname)||!/^edunexus_rc_\d+_[a-f0-9]{6}_test$/.test(s.database))throw Error('Local QA only');u.pathname='/'+s.database;const db=new pg.Client({connectionString:u.href});await db.connect();const t=await db.query('SELECT id,name FROM tenants WHERE id=ANY($1::uuid[])',[e.results.map(r=>r.tenantId)]);await db.end();const names=Object.fromEntries(t.rows.map(x=>[x.id,x.name]));let priv=fs.readFileSync(dir+'/LOCAL_DEMO_CREDENTIALS.md','utf8');for(const r of e.results)priv=priv.replace(r.tenantId+' (existing QA school; confirm display name after login)',(names[r.tenantId]||'Local QA school')+' ('+r.tenantId+')');fs.writeFileSync(dir+'/LOCAL_DEMO_CREDENTIALS.md',priv);
export const pre='Prepared 6 October 2026. Local fictional training only. No product changes, deployment or new QA audit. All eight accounts passed a real Chromium login check. Passwords are only in Git-ignored qa/artifacts/training/LOCAL_DEMO_CREDENTIALS.md.\n\n';
export const foot='\n## Evidence boundary\n\nSources: the eleven requested certification/UI documents and current mounted App components, Sidebar, permission policy, manual fee/parent portal, finance and subscription code. Local release-candidate certification is reported by FINAL_RC_RECERTIFICATION_REPORT.md; this training does not recertify it or establish production/provider readiness. Current UI takes precedence over older prototype routes and tab names.\n';
export function write(file,title,body){fs.writeFileSync(file,'# '+title+'\n\n'+pre+body+foot);}
export const roles={
SUPER_ADMIN:['Platform operator managing institutions and the SaaS catalog','Other schools are separate tenants; school finance requires valid tenant context','A school software subscription is different from parent tuition payments',[['superadmin-dashboard','Platform Overview','Review the platform summary','We operate multiple independent institutions.','Overview appears; describe actual displayed counts only.'],['superadmin-tenants','Tenants & Schools','Search the existing school; inspect its status','Each institution owns a separate workspace.','The school is listed; do not suspend the rehearsal school.'],['superadmin-plans','Subscription Plans','Open Create Plan; inspect fields; Cancel','These plans price the software service paid by schools.','Modal closes; no plan or provider transaction created.'],['superadmin-features','Feature Catalog','Inspect catalog only','A catalog view does not prove automated feature provisioning.','Catalog renders; avoid transactional toggle claims.']]],
TENANT_ADMIN:['School owner/principal with school-wide responsibility','Other institutions and global SaaS plan administration remain outside this school workspace','Student identity stays permanent; year/class/section belong to enrollment',[['master-data','School Master Data','Open Profile, Years, Branches, Classes, Subjects and Assignments','We define one academic structure reused by other modules.','Existing structure appears. Section forms are inside Classes.'],['students','Students','Search a sample child; open profile and enrollment','Admission is the identity; enrollment is the academic placement.','Student and academic history appear.'],['staff','Staff & Teachers','Inspect the staff profile/account and teacher assignment','A staff record, login and teaching responsibility are linked but different.','Existing profile/assignments appear.'],['fees','Fees & Payments','Review dues, structures, assign, settings, parentAccess and verify','A structure becomes an obligation when assigned to an enrollment.','Dues and linked parents appear; some old sample fees are already paid.'],['organization','Users & Access','Inspect invitations, roles and grants without editing demo roles','People get the responsibilities they need.','Limited Admin grant is visible.'],['saas-billing','SaaS Subscription','Read catalog/entitlement; do not press Subscribe','This school pays EduNexus separately from tuition collections.','Catalog/access state appears; no live checkout claim.']]],
ADMIN:['Delegated custom administrator; this fixture has master_data.view only','Admission, fees, finance and staff administration are not granted','ADMIN is a custom permission set, not unrestricted school ownership',[['dashboard','Dashboard','Review the smaller sidebar','Delegated responsibility gives a smaller workspace.','Only two menu items appear.'],['master-data','School Master Data','Inspect Profile and Classes without saving','Viewing and managing are separate grants.','Readable school data, no authorized edit controls.']]],
TEACHER:['Instructor linked to staff and assigned classes/subjects','School finances, fee verification and unrelated class work are not granted','A Teacher login also needs its profile and teaching assignments',[['timetable','Timetable','Choose existing year/class/section if prompted','Teaching duties need a shared schedule.','Existing assigned slots appear; an empty week needs setup.'],['attendance','Attendance & QR','Select assigned year/class/section/date and inspect roster','Attendance belongs to students enrolled in this academic context.','Authorized roster appears. Save only a fictional practice date.'],['exams','Examinations','Select prepared exam and Marks','Marks access follows teacher subject/class assignments.','Assigned marking controls appear; publish is a separate authorized action.'],['hr','HR & Leave','Inspect own balance/request form','Teachers are employees too.','Own leave data/form appears.']]],
ACCOUNTANT:['School finance employee handling verified collections and accounts','Academic setup, student admission and teacher account administration are not granted','A screenshot is evidence for review, not proof of actual money received',[['fees','Fees & Payments','Open dues and verify; View a pending proof','Only verified collections reduce the balance.','Proof details appear; empty queue needs a new Parent submission.'],['fees','Fees & Payments','Approve fictional practice proof; open receipts','Approval completes a collection and generates its receipt.','Receipt matches approved amount; no real money is moved.'],['finance','Finance & Accounts','Find that fee in Journals and General Ledger','Collection, receipt and accounts use the same financial source.','Equal debit/credit totals appear.'],['finance','Finance & Accounts','Inspect Expenses, Other Income and Fee Reconciliation','Other money uses separate vouchers; reconciliation checks linkage.','Existing entries appear; do not repost fees as Other Income.']]],
PARENT:['Guardian linked to one or several children','Other families, payment approval and school books are not available','Online Pay label currently means external QR/UPI plus manual proof verification',[['fees','Fee Dues & Online Pay','Select Child and inspect the due','One account can cover several linked children.','Only linked children are selectable.'],['fees','Fee Dues & Online Pay','Read Payment Instructions and School payment QR','Parent pays the SCHOOL through an external app.','Configured instructions appear; never transfer real money in rehearsal.'],['fees','Fee Dues & Online Pay','Submit fictional partial proof with unique DEMO reference, date and screenshot','Submitted evidence still needs the school verification.','PENDING proof; verified balance unchanged.'],['fees','Fee Dues & Online Pay','Refresh after Accountant approval; inspect receipt/balance','Verification completes the collection record.','Receipt appears and outstanding decreases.']]],
STUDENT:['Student account with a limited current dashboard','No fee verification, school accounts or academic administration','Do not promise dedicated timetable/results/attendance portal screens from an older report',[['dashboard','Student Dashboard','Inspect visible cards only','The current student workspace is limited.','Only Student Dashboard sidebar entry. Show assessment as Owner/Teacher.']]],
STAFF:['Non-teaching school employee using own HR services','Student attendance registers, school accounts and payment approval are not granted','Staff is not an alternate Teacher role',[['hr','HR & Leave','View own balance; prepare leave type/dates and request','Employees request leave; school managers review it.','Own balances/request form; submit only clearly fictional practice request.'],['dashboard','Dashboard','Return and Sign Out','The workspace reflects the staff responsibilities.','Dashboard and HR are the only sidebar entries.']]]};
let body=`## Start the existing training environment

Open Docker Desktop and wait for its engine. From PowerShell:

\`\`\`powershell
cd C:\\Users\\asus\\Desktop\\ERP
docker start edunexus-pg
docker ps --filter name=edunexus-pg
\`\`\`

Do not recreate/reset the container or database. The existing isolated QA state and fictional fixtures are reused. Open three separate terminals from the repository root:

\`\`\`powershell
# Terminal 1: backend
node --import tsx qa/rc-local.mjs api
\`\`\`

\`\`\`powershell
# Terminal 2: frontend
node qa/rc-local.mjs frontend
\`\`\`

\`\`\`powershell
# Terminal 3: notifications, LOG email only
node qa/rc-local.mjs worker
\`\`\`

These existing commands select the isolated local QA database and local provider placeholders. Worker uses existing compiled backend; after any later backend change, build before using it. No build needed for these docs. Do not run setup, fixtures, migrations, full-tests or account resets for training.

Both 5111 and 5191 were already running during preparation. If a port is occupied, reuse the known healthy local service; do not kill an unknown process. Check http://127.0.0.1:5111/health for healthy and database connected true. Browser: http://127.0.0.1:5191/#/login. Ordinary 5000/5173 ports may use different data/credentials.

## Login and switch role

1. Open the private LOCAL_DEMO_CREDENTIALS.md locally; never screen-share it.
2. Copy the chosen email/password and click Sign in.
3. All eight profiles currently land at #/app/dashboard; Super Admin renders its platform workspace there.
4. Use the sidebar, or menu button on mobile.
5. Use user menu → Sign Out to switch profile. Use separate browser profiles/private contexts for simultaneous roles, not tabs sharing one session.
6. If later login fails, first check services and QA database. Self-service password recovery is unavailable; no working OTP/reset workflow is claimed.

`;
for(const r of e.results){const d=roles[r.role];body+='## '+r.role+'\n\n**Represents:** '+d[0]+'.\n\n**Tenant:** '+(r.role==='SUPER_ADMIN'?'Global platform':names[r.tenantId])+'. **Landing:** `'+r.landing+'`.\n\n**Should see / sidebar:** '+r.nav.map(n=>n.label).join('; ')+'.\n\n**Should not see:** '+d[1]+'.\n\n**Important actions:** '+d[3].map(s=>s[2]).join('; ')+'.\n\n**Best demonstration:** '+d[3][Math.min(1,d[3].length-1)][3]+'\n\n**Avoid misunderstanding:** '+d[2]+'.\n\n';}
body+='## Current UI differences from older reports\n\nAccountant currently has Dashboard, Fees & Payments and Finance & Accounts: no Communications item. Show notices as Owner unless an authorized permission grant is deliberately changed. Master Data uses Profile, Years, Branches, Classes, Subjects and Assignments; Sections are within Classes. Fee buttons use dues, structures, assign, settings, proofs, verify, receipts, reports and parentAccess, filtered by permissions. Examinations uses Exams, Schedules, Marks, Results, Grades and Report, filtered by grants. Hidden academics/homework/health/CRM prototypes are excluded.\n';write('ROLE_LOGIN_GUIDE.md','Role login guide',body);
let lessons='## First read, then rehearse\n\nStart with School Owner. Use existing school/child first. Story names Aarav/Imran are teaching characters, not new accounts created by this task. Create clearly named PRACTICE records through the UI only when you understand the read-only lesson. Do not delete seed records or change training school status/subscription. Every lesson begins with private credentials → Sign in → confirm school and ends with user menu → Sign Out.\n\n';let ix=0;for(const [role,d]of Object.entries(roles)){lessons+='## Lesson '+(++ix)+' — '+role+'\n\n**Who you are:** '+d[0]+'.\n\n';d[3].forEach((s,i)=>{lessons+='### Step '+(i+1)+' — '+s[1]+'\n\n- **Look at:** `#/app/'+s[0]+'`, '+s[1]+'.\n- **Why it exists:** gives this role its assigned responsibilities.\n- **Click:** '+s[2]+'.\n- **Tell your senior:** “'+s[3]+'”\n- **Expect:** '+s[4]+'\n\n';});lessons+='**Finish:** Sign Out. **Avoid:** '+d[2]+'.\n\n';}lessons+='## Repeatable practice\n\nUse new admission numbers and references. Never reapprove an approved proof. Prepare a fresh unpaid enrollment-linked assignment before partial-payment rehearsal; old fixtures may already be paid. Parent chooses one of their existing linked children. For exam publication prepare valid subjects, enrollment and marks first. If Teacher roster is empty, check assignment/year/class/section as Owner. If subscription blocks operations, inspect Owner billing recovery; do not alter the DB or attempt provider payment.\n';write('EDUNEXUS_ROLE_TRAINING.md','Role-by-role practice lessons',lessons);
console.log('Login guide and eight role lessons created; credentials enriched with local tenant names.');
