import fs from 'node:fs';import {chromium} from 'playwright';
const dir=new URL('./artifacts/',import.meta.url),state=JSON.parse(fs.readFileSync(new URL('state.json',dir)));const results=[];const browser=await chromium.launch();const context=await browser.newContext();await context.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());const page=await context.newPage();page.setDefaultTimeout(5000);let events=[];page.on('response',async r=>{if(r.url().includes('/api/')&&r.request().method()!=='GET')events.push({url:r.url(),method:r.request().method(),status:r.status(),body:await r.text().catch(()=> '')});});
async function test(name,fn){events=[];try{await fn();await page.waitForTimeout(350);results.push({name,status:events.some(e=>e.status>=400)?'FAIL':'PASS',events:[...events],body:(await page.locator('body').innerText()).slice(-6000)});}catch(e){results.push({name,status:'BLOCKED',error:e.message,events:[...events],body:(await page.locator('body').innerText()).slice(-6000)});}fs.writeFileSync(new URL('workflows.json',dir),JSON.stringify(results,null,2));console.log(JSON.stringify({name,status:results.at(-1).status}));}
async function fill(scope,values){for(const[label,value]of Object.entries(values)){const l=scope.getByLabel(label,{exact:false}).first();if(await l.evaluate(e=>e.tagName)==='SELECT'){if(value==='FIRST')await l.selectOption(await l.locator('option').nth(1).getAttribute('value'));else await l.selectOption({label:value});}else await l.fill(value);}}
async function generic(route,title,values){await page.goto(`http://127.0.0.1:5185/#/app/${route}`);await page.waitForTimeout(500);const scope=page.locator('section').filter({has:page.getByRole('heading',{name:title,exact:true})});await fill(scope,values);const response=page.waitForResponse(r=>r.request().method()!=='GET'&&r.url().includes('/api/'));await scope.getByRole('button',{name:'Save',exact:true}).click();await response;}
await page.goto('http://127.0.0.1:5185/#/login');await page.locator('input[type=email]').fill(state.accounts.TENANT_ADMIN.email);await page.locator('input[type=password]').fill(state.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForTimeout(700);
await test('School profile save and refresh',async()=>{await page.goto('http://127.0.0.1:5185/#/app/master-data');await page.getByLabel('School name',{exact:true}).fill('QA School 2026-27');await page.getByLabel('City',{exact:true}).fill('QA City');await page.getByRole('button',{name:'Save profile',exact:true}).click();await page.waitForTimeout(500);await page.reload();await page.getByLabel('City',{exact:true}).waitFor();if(await page.getByLabel('City',{exact:true}).inputValue()!=='QA City')throw Error('Profile state lost on refresh');});
for(const[tab,name,values,button]of [['Years','Academic year creation',{Name:'QA 2026-27',Start:'2026-04-01',End:'2027-03-31',Status:'Active'},'Add year'],['Branches','Branch creation',{Name:'QA Main B',Code:'QAMAINB',City:'QA City',State:'QA State'},'Add branch'],['Classes','Class creation',{'Class name':'QA Class 5','Numeric level':'5',Branch:'FIRST','Academic year':'FIRST'},'Add class'],['Classes','Section creation',{Class:'FIRST','Section name':'QA A',Capacity:'30'},'Add section'],['Subjects','Subject creation',{Name:'QA Mathematics B',Code:'QAMATHB',Department:'QA Academics','Weekly periods':'5'},'Add subject']])await test(name,async()=>{await page.locator('main').getByRole('button',{name:tab,exact:true}).click();const form=page.locator('form').filter({has:page.getByRole('button',{name:button,exact:true})});await fill(form,values);const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/api/'));await form.getByRole('button',{name:button,exact:true}).click();await response;});
await test('Student admission dropdown dependencies',async()=>{await page.goto('http://127.0.0.1:5185/#/app/students');await page.getByRole('button',{name:'Admit student',exact:true}).click();await fill(page.locator('form'),{'Admission number':'QA-001','First name':'QA Child','Last name':'One','Academic year':'FIRST',Class:'FIRST',Section:'FIRST'});await page.getByRole('button',{name:'Create identity and enrollment',exact:true}).click();});
for(const[route,title,values]of [['library','Add category',{'Category name':'QA Fiction B'}],['library','Add title',{Title:'QA Book',Author:'QA Author',Category:'FIRST'}],['library','Add physical copy',{Title:'FIRST','Accession number':'QA-COPY-001'}],['inventory','Add category',{'Category name':'QA Supplies B'}],['inventory','Add location',{'Location name':'QA Store B'}],['inventory','Add item',{'Item name':'QA Pencil',SKU:'QA-PENCIL',Category:'FIRST','Item type':'CONSUMABLE',Unit:'piece','Low-stock threshold':'2'}],['inventory','Stock movement',{Item:'FIRST',Location:'FIRST','Movement type':'RECEIPT','Quantity (signed for adjustments)':'10',Reason:'QA opening'}],['inventory','Stock movement',{Item:'FIRST',Location:'FIRST','Movement type':'ISSUE','Quantity (signed for adjustments)':'11',Reason:'QA negative stock check'}],['hostel','Add building',{'Building name':'QA Residence B'}],['hostel','Add room and beds',{Building:'FIRST','Room number':'QA101','Number of beds':'2'}],['mess','Add meal plan',{'Plan name':'QA Meals B',Description:'Local QA only'}],['mess','Configure weekly menu',{'Meal plan':'FIRST',Day:'MONDAY',Meal:'LUNCH','Menu items':'QA Rice'}],['transport','Add vehicle',{'Registration number':'QA-TEST-002','Vehicle type':'BUS',Capacity:'20'}],['transport','Add route',{'Route name':'QA Route',Vehicle:'FIRST'}],['transport','Add ordered stop',{Route:'FIRST','Stop name':'QA Stop','Stop sequence':'1'}]])await test(`${route}: ${title}${values['Movement type']?' '+values['Movement type']:''}`,()=>generic(route,title,values));
await test('Inventory search and refresh',async()=>{await page.goto('http://127.0.0.1:5185/#/app/inventory');await page.getByPlaceholder('Search loaded records').fill('QA Pencil');await page.reload();await page.getByText('QA Pencil',{exact:true}).first().waitFor();});
await browser.close();

